/* IComponent.c generated by valac 0.34.4, the Vala compiler
 * generated from IComponent.vala, do not modify */


#include <glib.h>
#include <glib-object.h>


#define TYPE_DARK_MATTER (dark_matter_get_type ())
#define DARK_MATTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DARK_MATTER, DarkMatter))
#define DARK_MATTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DARK_MATTER, DarkMatterClass))
#define IS_DARK_MATTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DARK_MATTER))
#define IS_DARK_MATTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DARK_MATTER))
#define DARK_MATTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DARK_MATTER, DarkMatterClass))

typedef struct _DarkMatter DarkMatter;
typedef struct _DarkMatterClass DarkMatterClass;

#define BOSCO_ECS_TYPE_ICOMPONENT (bosco_ecs_icomponent_get_type ())
#define BOSCO_ECS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ICOMPONENT, BoscoECSIComponent))
#define BOSCO_ECS_IS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ICOMPONENT))
#define BOSCO_ECS_ICOMPONENT_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_ICOMPONENT, BoscoECSIComponentIface))

typedef struct _BoscoECSIComponent BoscoECSIComponent;
typedef struct _BoscoECSIComponentIface BoscoECSIComponentIface;

struct _BoscoECSIComponentIface {
	GTypeInterface parent_iface;
};



gpointer dark_matter_ref (gpointer instance);
void dark_matter_unref (gpointer instance);
GParamSpec* param_spec_dark_matter (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_dark_matter (GValue* value, gpointer v_object);
void value_take_dark_matter (GValue* value, gpointer v_object);
gpointer value_get_dark_matter (const GValue* value);
GType dark_matter_get_type (void) G_GNUC_CONST;
GType bosco_ecs_icomponent_get_type (void) G_GNUC_CONST;


static void bosco_ecs_icomponent_base_init (BoscoECSIComponentIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType bosco_ecs_icomponent_get_type (void) {
	static volatile gsize bosco_ecs_icomponent_type_id__volatile = 0;
	if (g_once_init_enter (&bosco_ecs_icomponent_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BoscoECSIComponentIface), (GBaseInitFunc) bosco_ecs_icomponent_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType bosco_ecs_icomponent_type_id;
		bosco_ecs_icomponent_type_id = g_type_register_static (G_TYPE_INTERFACE, "BoscoECSIComponent", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (bosco_ecs_icomponent_type_id, TYPE_DARK_MATTER);
		g_once_init_leave (&bosco_ecs_icomponent_type_id__volatile, bosco_ecs_icomponent_type_id);
	}
	return bosco_ecs_icomponent_type_id__volatile;
}



