/* IMatcher.c generated by valac 0.34.4, the Vala compiler
 * generated from IMatcher.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_DARK_MATTER (dark_matter_get_type ())
#define DARK_MATTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DARK_MATTER, DarkMatter))
#define DARK_MATTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DARK_MATTER, DarkMatterClass))
#define IS_DARK_MATTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DARK_MATTER))
#define IS_DARK_MATTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DARK_MATTER))
#define DARK_MATTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DARK_MATTER, DarkMatterClass))

typedef struct _DarkMatter DarkMatter;
typedef struct _DarkMatterClass DarkMatterClass;

#define BOSCO_ECS_TYPE_IMATCHER (bosco_ecs_imatcher_get_type ())
#define BOSCO_ECS_IMATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_IMATCHER, BoscoECSIMatcher))
#define BOSCO_ECS_IS_IMATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_IMATCHER))
#define BOSCO_ECS_IMATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_IMATCHER, BoscoECSIMatcherIface))

typedef struct _BoscoECSIMatcher BoscoECSIMatcher;
typedef struct _BoscoECSIMatcherIface BoscoECSIMatcherIface;

#define BOSCO_ECS_TYPE_ENTITY_BASE (bosco_ecs_entity_base_get_type ())
#define BOSCO_ECS_ENTITY_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ENTITY_BASE, BoscoECSEntityBase))
#define BOSCO_ECS_ENTITY_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_ENTITY_BASE, BoscoECSEntityBaseClass))
#define BOSCO_ECS_IS_ENTITY_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ENTITY_BASE))
#define BOSCO_ECS_IS_ENTITY_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_ENTITY_BASE))
#define BOSCO_ECS_ENTITY_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_ENTITY_BASE, BoscoECSEntityBaseClass))

typedef struct _BoscoECSEntityBase BoscoECSEntityBase;
typedef struct _BoscoECSEntityBaseClass BoscoECSEntityBaseClass;

#define BOSCO_ECS_TYPE_ENTITY (bosco_ecs_entity_get_type ())
#define BOSCO_ECS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ENTITY, BoscoECSEntity))
#define BOSCO_ECS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_ENTITY, BoscoECSEntityClass))
#define BOSCO_ECS_IS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ENTITY))
#define BOSCO_ECS_IS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_ENTITY))
#define BOSCO_ECS_ENTITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_ENTITY, BoscoECSEntityClass))

typedef struct _BoscoECSEntity BoscoECSEntity;
typedef struct _BoscoECSEntityClass BoscoECSEntityClass;

#define BOSCO_ECS_TYPE_ICOMPOUND_MATCHER (bosco_ecs_icompound_matcher_get_type ())
#define BOSCO_ECS_ICOMPOUND_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ICOMPOUND_MATCHER, BoscoECSICompoundMatcher))
#define BOSCO_ECS_IS_ICOMPOUND_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ICOMPOUND_MATCHER))
#define BOSCO_ECS_ICOMPOUND_MATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_ICOMPOUND_MATCHER, BoscoECSICompoundMatcherIface))

typedef struct _BoscoECSICompoundMatcher BoscoECSICompoundMatcher;
typedef struct _BoscoECSICompoundMatcherIface BoscoECSICompoundMatcherIface;

#define BOSCO_ECS_TYPE_INONE_OF_MATCHER (bosco_ecs_inone_of_matcher_get_type ())
#define BOSCO_ECS_INONE_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_INONE_OF_MATCHER, BoscoECSINoneOfMatcher))
#define BOSCO_ECS_IS_INONE_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_INONE_OF_MATCHER))
#define BOSCO_ECS_INONE_OF_MATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_INONE_OF_MATCHER, BoscoECSINoneOfMatcherIface))

typedef struct _BoscoECSINoneOfMatcher BoscoECSINoneOfMatcher;
typedef struct _BoscoECSINoneOfMatcherIface BoscoECSINoneOfMatcherIface;

#define BOSCO_ECS_TYPE_IANY_OF_MATCHER (bosco_ecs_iany_of_matcher_get_type ())
#define BOSCO_ECS_IANY_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_IANY_OF_MATCHER, BoscoECSIAnyOfMatcher))
#define BOSCO_ECS_IS_IANY_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_IANY_OF_MATCHER))
#define BOSCO_ECS_IANY_OF_MATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_IANY_OF_MATCHER, BoscoECSIAnyOfMatcherIface))

typedef struct _BoscoECSIAnyOfMatcher BoscoECSIAnyOfMatcher;
typedef struct _BoscoECSIAnyOfMatcherIface BoscoECSIAnyOfMatcherIface;

#define BOSCO_ECS_TYPE_IALL_OF_MATCHER (bosco_ecs_iall_of_matcher_get_type ())
#define BOSCO_ECS_IALL_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_IALL_OF_MATCHER, BoscoECSIAllOfMatcher))
#define BOSCO_ECS_IS_IALL_OF_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_IALL_OF_MATCHER))
#define BOSCO_ECS_IALL_OF_MATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_IALL_OF_MATCHER, BoscoECSIAllOfMatcherIface))

typedef struct _BoscoECSIAllOfMatcher BoscoECSIAllOfMatcher;
typedef struct _BoscoECSIAllOfMatcherIface BoscoECSIAllOfMatcherIface;

struct _BoscoECSIMatcherIface {
	GTypeInterface parent_iface;
	gboolean (*matches) (BoscoECSIMatcher* self, BoscoECSEntity* entity);
	gchar* (*toString) (BoscoECSIMatcher* self);
	const gchar* (*get_id) (BoscoECSIMatcher* self);
	gint* (*get_indices) (BoscoECSIMatcher* self, int* result_length1);
};

struct _BoscoECSICompoundMatcherIface {
	GTypeInterface parent_iface;
	gint* (*get_allOfIndices) (BoscoECSICompoundMatcher* self, int* result_length1);
	gint* (*get_anyOfIndices) (BoscoECSICompoundMatcher* self, int* result_length1);
	gint* (*get_noneOfIndices) (BoscoECSICompoundMatcher* self, int* result_length1);
};

struct _BoscoECSINoneOfMatcherIface {
	GTypeInterface parent_iface;
};

struct _BoscoECSIAnyOfMatcherIface {
	GTypeInterface parent_iface;
	BoscoECSINoneOfMatcher* (*noneOf) (BoscoECSIAnyOfMatcher* self, gint* args, int args_length1);
};

struct _BoscoECSIAllOfMatcherIface {
	GTypeInterface parent_iface;
	BoscoECSIAnyOfMatcher* (*anyOf) (BoscoECSIAllOfMatcher* self, gint* args, int args_length1);
	BoscoECSINoneOfMatcher* (*noneOf) (BoscoECSIAllOfMatcher* self, gint* args, int args_length1);
};



gpointer dark_matter_ref (gpointer instance);
void dark_matter_unref (gpointer instance);
GParamSpec* param_spec_dark_matter (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_dark_matter (GValue* value, gpointer v_object);
void value_take_dark_matter (GValue* value, gpointer v_object);
gpointer value_get_dark_matter (const GValue* value);
GType dark_matter_get_type (void) G_GNUC_CONST;
GType bosco_ecs_entity_base_get_type (void) G_GNUC_CONST;
GType bosco_ecs_entity_get_type (void) G_GNUC_CONST;
GType bosco_ecs_imatcher_get_type (void) G_GNUC_CONST;
gboolean bosco_ecs_imatcher_matches (BoscoECSIMatcher* self, BoscoECSEntity* entity);
gchar* bosco_ecs_imatcher_toString (BoscoECSIMatcher* self);
const gchar* bosco_ecs_imatcher_get_id (BoscoECSIMatcher* self);
gint* bosco_ecs_imatcher_get_indices (BoscoECSIMatcher* self, int* result_length1);
GType bosco_ecs_icompound_matcher_get_type (void) G_GNUC_CONST;
gint* bosco_ecs_icompound_matcher_get_allOfIndices (BoscoECSICompoundMatcher* self, int* result_length1);
gint* bosco_ecs_icompound_matcher_get_anyOfIndices (BoscoECSICompoundMatcher* self, int* result_length1);
gint* bosco_ecs_icompound_matcher_get_noneOfIndices (BoscoECSICompoundMatcher* self, int* result_length1);
GType bosco_ecs_inone_of_matcher_get_type (void) G_GNUC_CONST;
GType bosco_ecs_iany_of_matcher_get_type (void) G_GNUC_CONST;
BoscoECSINoneOfMatcher* bosco_ecs_iany_of_matcher_noneOf (BoscoECSIAnyOfMatcher* self, gint* args, int args_length1);
GType bosco_ecs_iall_of_matcher_get_type (void) G_GNUC_CONST;
BoscoECSIAnyOfMatcher* bosco_ecs_iall_of_matcher_anyOf (BoscoECSIAllOfMatcher* self, gint* args, int args_length1);
BoscoECSINoneOfMatcher* bosco_ecs_iall_of_matcher_noneOf (BoscoECSIAllOfMatcher* self, gint* args, int args_length1);


gboolean bosco_ecs_imatcher_matches (BoscoECSIMatcher* self, BoscoECSEntity* entity) {
	g_return_val_if_fail (self != NULL, FALSE);
	return BOSCO_ECS_IMATCHER_GET_INTERFACE (self)->matches (self, entity);
}


gchar* bosco_ecs_imatcher_toString (BoscoECSIMatcher* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return BOSCO_ECS_IMATCHER_GET_INTERFACE (self)->toString (self);
}


const gchar* bosco_ecs_imatcher_get_id (BoscoECSIMatcher* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return BOSCO_ECS_IMATCHER_GET_INTERFACE (self)->get_id (self);
}


gint* bosco_ecs_imatcher_get_indices (BoscoECSIMatcher* self, int* result_length1) {
	g_return_val_if_fail (self != NULL, NULL);
	return BOSCO_ECS_IMATCHER_GET_INTERFACE (self)->get_indices (self, result_length1);
}


static void bosco_ecs_imatcher_base_init (BoscoECSIMatcherIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType bosco_ecs_imatcher_get_type (void) {
	static volatile gsize bosco_ecs_imatcher_type_id__volatile = 0;
	if (g_once_init_enter (&bosco_ecs_imatcher_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BoscoECSIMatcherIface), (GBaseInitFunc) bosco_ecs_imatcher_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType bosco_ecs_imatcher_type_id;
		bosco_ecs_imatcher_type_id = g_type_register_static (G_TYPE_INTERFACE, "BoscoECSIMatcher", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (bosco_ecs_imatcher_type_id, TYPE_DARK_MATTER);
		g_once_init_leave (&bosco_ecs_imatcher_type_id__volatile, bosco_ecs_imatcher_type_id);
	}
	return bosco_ecs_imatcher_type_id__volatile;
}


gint* bosco_ecs_icompound_matcher_get_allOfIndices (BoscoECSICompoundMatcher* self, int* result_length1) {
	g_return_val_if_fail (self != NULL, NULL);
	return BOSCO_ECS_ICOMPOUND_MATCHER_GET_INTERFACE (self)->get_allOfIndices (self, result_length1);
}


gint* bosco_ecs_icompound_matcher_get_anyOfIndices (BoscoECSICompoundMatcher* self, int* result_length1) {
	g_return_val_if_fail (self != NULL, NULL);
	return BOSCO_ECS_ICOMPOUND_MATCHER_GET_INTERFACE (self)->get_anyOfIndices (self, result_length1);
}


gint* bosco_ecs_icompound_matcher_get_noneOfIndices (BoscoECSICompoundMatcher* self, int* result_length1) {
	g_return_val_if_fail (self != NULL, NULL);
	return BOSCO_ECS_ICOMPOUND_MATCHER_GET_INTERFACE (self)->get_noneOfIndices (self, result_length1);
}


static void bosco_ecs_icompound_matcher_base_init (BoscoECSICompoundMatcherIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType bosco_ecs_icompound_matcher_get_type (void) {
	static volatile gsize bosco_ecs_icompound_matcher_type_id__volatile = 0;
	if (g_once_init_enter (&bosco_ecs_icompound_matcher_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BoscoECSICompoundMatcherIface), (GBaseInitFunc) bosco_ecs_icompound_matcher_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType bosco_ecs_icompound_matcher_type_id;
		bosco_ecs_icompound_matcher_type_id = g_type_register_static (G_TYPE_INTERFACE, "BoscoECSICompoundMatcher", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (bosco_ecs_icompound_matcher_type_id, TYPE_DARK_MATTER);
		g_once_init_leave (&bosco_ecs_icompound_matcher_type_id__volatile, bosco_ecs_icompound_matcher_type_id);
	}
	return bosco_ecs_icompound_matcher_type_id__volatile;
}


static void bosco_ecs_inone_of_matcher_base_init (BoscoECSINoneOfMatcherIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType bosco_ecs_inone_of_matcher_get_type (void) {
	static volatile gsize bosco_ecs_inone_of_matcher_type_id__volatile = 0;
	if (g_once_init_enter (&bosco_ecs_inone_of_matcher_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BoscoECSINoneOfMatcherIface), (GBaseInitFunc) bosco_ecs_inone_of_matcher_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType bosco_ecs_inone_of_matcher_type_id;
		bosco_ecs_inone_of_matcher_type_id = g_type_register_static (G_TYPE_INTERFACE, "BoscoECSINoneOfMatcher", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (bosco_ecs_inone_of_matcher_type_id, TYPE_DARK_MATTER);
		g_once_init_leave (&bosco_ecs_inone_of_matcher_type_id__volatile, bosco_ecs_inone_of_matcher_type_id);
	}
	return bosco_ecs_inone_of_matcher_type_id__volatile;
}


BoscoECSINoneOfMatcher* bosco_ecs_iany_of_matcher_noneOf (BoscoECSIAnyOfMatcher* self, gint* args, int args_length1) {
	g_return_val_if_fail (self != NULL, NULL);
	return BOSCO_ECS_IANY_OF_MATCHER_GET_INTERFACE (self)->noneOf (self, args, args_length1);
}


static void bosco_ecs_iany_of_matcher_base_init (BoscoECSIAnyOfMatcherIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType bosco_ecs_iany_of_matcher_get_type (void) {
	static volatile gsize bosco_ecs_iany_of_matcher_type_id__volatile = 0;
	if (g_once_init_enter (&bosco_ecs_iany_of_matcher_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BoscoECSIAnyOfMatcherIface), (GBaseInitFunc) bosco_ecs_iany_of_matcher_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType bosco_ecs_iany_of_matcher_type_id;
		bosco_ecs_iany_of_matcher_type_id = g_type_register_static (G_TYPE_INTERFACE, "BoscoECSIAnyOfMatcher", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (bosco_ecs_iany_of_matcher_type_id, TYPE_DARK_MATTER);
		g_once_init_leave (&bosco_ecs_iany_of_matcher_type_id__volatile, bosco_ecs_iany_of_matcher_type_id);
	}
	return bosco_ecs_iany_of_matcher_type_id__volatile;
}


BoscoECSIAnyOfMatcher* bosco_ecs_iall_of_matcher_anyOf (BoscoECSIAllOfMatcher* self, gint* args, int args_length1) {
	g_return_val_if_fail (self != NULL, NULL);
	return BOSCO_ECS_IALL_OF_MATCHER_GET_INTERFACE (self)->anyOf (self, args, args_length1);
}


BoscoECSINoneOfMatcher* bosco_ecs_iall_of_matcher_noneOf (BoscoECSIAllOfMatcher* self, gint* args, int args_length1) {
	g_return_val_if_fail (self != NULL, NULL);
	return BOSCO_ECS_IALL_OF_MATCHER_GET_INTERFACE (self)->noneOf (self, args, args_length1);
}


static void bosco_ecs_iall_of_matcher_base_init (BoscoECSIAllOfMatcherIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType bosco_ecs_iall_of_matcher_get_type (void) {
	static volatile gsize bosco_ecs_iall_of_matcher_type_id__volatile = 0;
	if (g_once_init_enter (&bosco_ecs_iall_of_matcher_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BoscoECSIAllOfMatcherIface), (GBaseInitFunc) bosco_ecs_iall_of_matcher_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType bosco_ecs_iall_of_matcher_type_id;
		bosco_ecs_iall_of_matcher_type_id = g_type_register_static (G_TYPE_INTERFACE, "BoscoECSIAllOfMatcher", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (bosco_ecs_iall_of_matcher_type_id, TYPE_DARK_MATTER);
		g_once_init_leave (&bosco_ecs_iall_of_matcher_type_id__volatile, bosco_ecs_iall_of_matcher_type_id);
	}
	return bosco_ecs_iall_of_matcher_type_id__volatile;
}



