/* ISystem.c generated by valac 0.34.4, the Vala compiler
 * generated from ISystem.vala, do not modify */


#include <glib.h>
#include <glib-object.h>


#define TYPE_DARK_MATTER (dark_matter_get_type ())
#define DARK_MATTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DARK_MATTER, DarkMatter))
#define DARK_MATTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DARK_MATTER, DarkMatterClass))
#define IS_DARK_MATTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DARK_MATTER))
#define IS_DARK_MATTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DARK_MATTER))
#define DARK_MATTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DARK_MATTER, DarkMatterClass))

typedef struct _DarkMatter DarkMatter;
typedef struct _DarkMatterClass DarkMatterClass;

#define BOSCO_ECS_TYPE_ISYSTEM (bosco_ecs_isystem_get_type ())
#define BOSCO_ECS_ISYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ISYSTEM, BoscoECSISystem))
#define BOSCO_ECS_IS_ISYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ISYSTEM))
#define BOSCO_ECS_ISYSTEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_ISYSTEM, BoscoECSISystemIface))

typedef struct _BoscoECSISystem BoscoECSISystem;
typedef struct _BoscoECSISystemIface BoscoECSISystemIface;

#define BOSCO_ECS_TYPE_ISET_WORLD (bosco_ecs_iset_world_get_type ())
#define BOSCO_ECS_ISET_WORLD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ISET_WORLD, BoscoECSISetWorld))
#define BOSCO_ECS_IS_ISET_WORLD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ISET_WORLD))
#define BOSCO_ECS_ISET_WORLD_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_ISET_WORLD, BoscoECSISetWorldIface))

typedef struct _BoscoECSISetWorld BoscoECSISetWorld;
typedef struct _BoscoECSISetWorldIface BoscoECSISetWorldIface;

#define BOSCO_ECS_TYPE_WORLD_BASE (bosco_ecs_world_base_get_type ())
#define BOSCO_ECS_WORLD_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_WORLD_BASE, BoscoECSWorldBase))
#define BOSCO_ECS_WORLD_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_WORLD_BASE, BoscoECSWorldBaseClass))
#define BOSCO_ECS_IS_WORLD_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_WORLD_BASE))
#define BOSCO_ECS_IS_WORLD_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_WORLD_BASE))
#define BOSCO_ECS_WORLD_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_WORLD_BASE, BoscoECSWorldBaseClass))

typedef struct _BoscoECSWorldBase BoscoECSWorldBase;
typedef struct _BoscoECSWorldBaseClass BoscoECSWorldBaseClass;

#define BOSCO_ECS_TYPE_WORLD (bosco_ecs_world_get_type ())
#define BOSCO_ECS_WORLD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_WORLD, BoscoECSWorld))
#define BOSCO_ECS_WORLD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_WORLD, BoscoECSWorldClass))
#define BOSCO_ECS_IS_WORLD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_WORLD))
#define BOSCO_ECS_IS_WORLD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_WORLD))
#define BOSCO_ECS_WORLD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_WORLD, BoscoECSWorldClass))

typedef struct _BoscoECSWorld BoscoECSWorld;
typedef struct _BoscoECSWorldClass BoscoECSWorldClass;

#define BOSCO_ECS_TYPE_IEXECUTE_SYSTEM (bosco_ecs_iexecute_system_get_type ())
#define BOSCO_ECS_IEXECUTE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_IEXECUTE_SYSTEM, BoscoECSIExecuteSystem))
#define BOSCO_ECS_IS_IEXECUTE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_IEXECUTE_SYSTEM))
#define BOSCO_ECS_IEXECUTE_SYSTEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_IEXECUTE_SYSTEM, BoscoECSIExecuteSystemIface))

typedef struct _BoscoECSIExecuteSystem BoscoECSIExecuteSystem;
typedef struct _BoscoECSIExecuteSystemIface BoscoECSIExecuteSystemIface;

#define BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM (bosco_ecs_iinitialize_system_get_type ())
#define BOSCO_ECS_IINITIALIZE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM, BoscoECSIInitializeSystem))
#define BOSCO_ECS_IS_IINITIALIZE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM))
#define BOSCO_ECS_IINITIALIZE_SYSTEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM, BoscoECSIInitializeSystemIface))

typedef struct _BoscoECSIInitializeSystem BoscoECSIInitializeSystem;
typedef struct _BoscoECSIInitializeSystemIface BoscoECSIInitializeSystemIface;

struct _BoscoECSISystemIface {
	GTypeInterface parent_iface;
};

struct _BoscoECSISetWorldIface {
	GTypeInterface parent_iface;
	void (*setWorld) (BoscoECSISetWorld* self, BoscoECSWorld* world);
};

struct _BoscoECSIExecuteSystemIface {
	GTypeInterface parent_iface;
	void (*execute) (BoscoECSIExecuteSystem* self);
};

struct _BoscoECSIInitializeSystemIface {
	GTypeInterface parent_iface;
	void (*initialize) (BoscoECSIInitializeSystem* self);
};



gpointer dark_matter_ref (gpointer instance);
void dark_matter_unref (gpointer instance);
GParamSpec* param_spec_dark_matter (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_dark_matter (GValue* value, gpointer v_object);
void value_take_dark_matter (GValue* value, gpointer v_object);
gpointer value_get_dark_matter (const GValue* value);
GType dark_matter_get_type (void) G_GNUC_CONST;
GType bosco_ecs_isystem_get_type (void) G_GNUC_CONST;
GType bosco_ecs_world_base_get_type (void) G_GNUC_CONST;
GType bosco_ecs_world_get_type (void) G_GNUC_CONST;
GType bosco_ecs_iset_world_get_type (void) G_GNUC_CONST;
void bosco_ecs_iset_world_setWorld (BoscoECSISetWorld* self, BoscoECSWorld* world);
GType bosco_ecs_iexecute_system_get_type (void) G_GNUC_CONST;
void bosco_ecs_iexecute_system_execute (BoscoECSIExecuteSystem* self);
GType bosco_ecs_iinitialize_system_get_type (void) G_GNUC_CONST;
void bosco_ecs_iinitialize_system_initialize (BoscoECSIInitializeSystem* self);


static void bosco_ecs_isystem_base_init (BoscoECSISystemIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType bosco_ecs_isystem_get_type (void) {
	static volatile gsize bosco_ecs_isystem_type_id__volatile = 0;
	if (g_once_init_enter (&bosco_ecs_isystem_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BoscoECSISystemIface), (GBaseInitFunc) bosco_ecs_isystem_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType bosco_ecs_isystem_type_id;
		bosco_ecs_isystem_type_id = g_type_register_static (G_TYPE_INTERFACE, "BoscoECSISystem", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (bosco_ecs_isystem_type_id, TYPE_DARK_MATTER);
		g_once_init_leave (&bosco_ecs_isystem_type_id__volatile, bosco_ecs_isystem_type_id);
	}
	return bosco_ecs_isystem_type_id__volatile;
}


void bosco_ecs_iset_world_setWorld (BoscoECSISetWorld* self, BoscoECSWorld* world) {
	g_return_if_fail (self != NULL);
	BOSCO_ECS_ISET_WORLD_GET_INTERFACE (self)->setWorld (self, world);
}


static void bosco_ecs_iset_world_base_init (BoscoECSISetWorldIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType bosco_ecs_iset_world_get_type (void) {
	static volatile gsize bosco_ecs_iset_world_type_id__volatile = 0;
	if (g_once_init_enter (&bosco_ecs_iset_world_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BoscoECSISetWorldIface), (GBaseInitFunc) bosco_ecs_iset_world_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType bosco_ecs_iset_world_type_id;
		bosco_ecs_iset_world_type_id = g_type_register_static (G_TYPE_INTERFACE, "BoscoECSISetWorld", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (bosco_ecs_iset_world_type_id, TYPE_DARK_MATTER);
		g_once_init_leave (&bosco_ecs_iset_world_type_id__volatile, bosco_ecs_iset_world_type_id);
	}
	return bosco_ecs_iset_world_type_id__volatile;
}


void bosco_ecs_iexecute_system_execute (BoscoECSIExecuteSystem* self) {
	g_return_if_fail (self != NULL);
	BOSCO_ECS_IEXECUTE_SYSTEM_GET_INTERFACE (self)->execute (self);
}


static void bosco_ecs_iexecute_system_base_init (BoscoECSIExecuteSystemIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType bosco_ecs_iexecute_system_get_type (void) {
	static volatile gsize bosco_ecs_iexecute_system_type_id__volatile = 0;
	if (g_once_init_enter (&bosco_ecs_iexecute_system_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BoscoECSIExecuteSystemIface), (GBaseInitFunc) bosco_ecs_iexecute_system_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType bosco_ecs_iexecute_system_type_id;
		bosco_ecs_iexecute_system_type_id = g_type_register_static (G_TYPE_INTERFACE, "BoscoECSIExecuteSystem", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (bosco_ecs_iexecute_system_type_id, TYPE_DARK_MATTER);
		g_once_init_leave (&bosco_ecs_iexecute_system_type_id__volatile, bosco_ecs_iexecute_system_type_id);
	}
	return bosco_ecs_iexecute_system_type_id__volatile;
}


void bosco_ecs_iinitialize_system_initialize (BoscoECSIInitializeSystem* self) {
	g_return_if_fail (self != NULL);
	BOSCO_ECS_IINITIALIZE_SYSTEM_GET_INTERFACE (self)->initialize (self);
}


static void bosco_ecs_iinitialize_system_base_init (BoscoECSIInitializeSystemIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType bosco_ecs_iinitialize_system_get_type (void) {
	static volatile gsize bosco_ecs_iinitialize_system_type_id__volatile = 0;
	if (g_once_init_enter (&bosco_ecs_iinitialize_system_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BoscoECSIInitializeSystemIface), (GBaseInitFunc) bosco_ecs_iinitialize_system_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType bosco_ecs_iinitialize_system_type_id;
		bosco_ecs_iinitialize_system_type_id = g_type_register_static (G_TYPE_INTERFACE, "BoscoECSIInitializeSystem", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (bosco_ecs_iinitialize_system_type_id, TYPE_DARK_MATTER);
		g_once_init_leave (&bosco_ecs_iinitialize_system_type_id__volatile, bosco_ecs_iinitialize_system_type_id);
	}
	return bosco_ecs_iinitialize_system_type_id__volatile;
}



