/* CollisionSystem.c generated by valac 0.34.4, the Vala compiler
 * generated from CollisionSystem.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <gobject/gvaluecollector.h>


#define TYPE_DARK_MATTER (dark_matter_get_type ())
#define DARK_MATTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DARK_MATTER, DarkMatter))
#define DARK_MATTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DARK_MATTER, DarkMatterClass))
#define IS_DARK_MATTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DARK_MATTER))
#define IS_DARK_MATTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DARK_MATTER))
#define DARK_MATTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DARK_MATTER, DarkMatterClass))

typedef struct _DarkMatter DarkMatter;
typedef struct _DarkMatterClass DarkMatterClass;
typedef struct _DarkMatterPrivate DarkMatterPrivate;

#define BOSCO_ECS_TYPE_ISYSTEM (bosco_ecs_isystem_get_type ())
#define BOSCO_ECS_ISYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ISYSTEM, BoscoECSISystem))
#define BOSCO_ECS_IS_ISYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ISYSTEM))
#define BOSCO_ECS_ISYSTEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_ISYSTEM, BoscoECSISystemIface))

typedef struct _BoscoECSISystem BoscoECSISystem;
typedef struct _BoscoECSISystemIface BoscoECSISystemIface;

#define BOSCO_ECS_TYPE_ISET_WORLD (bosco_ecs_iset_world_get_type ())
#define BOSCO_ECS_ISET_WORLD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ISET_WORLD, BoscoECSISetWorld))
#define BOSCO_ECS_IS_ISET_WORLD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ISET_WORLD))
#define BOSCO_ECS_ISET_WORLD_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_ISET_WORLD, BoscoECSISetWorldIface))

typedef struct _BoscoECSISetWorld BoscoECSISetWorld;
typedef struct _BoscoECSISetWorldIface BoscoECSISetWorldIface;

#define BOSCO_ECS_TYPE_WORLD_BASE (bosco_ecs_world_base_get_type ())
#define BOSCO_ECS_WORLD_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_WORLD_BASE, BoscoECSWorldBase))
#define BOSCO_ECS_WORLD_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_WORLD_BASE, BoscoECSWorldBaseClass))
#define BOSCO_ECS_IS_WORLD_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_WORLD_BASE))
#define BOSCO_ECS_IS_WORLD_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_WORLD_BASE))
#define BOSCO_ECS_WORLD_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_WORLD_BASE, BoscoECSWorldBaseClass))

typedef struct _BoscoECSWorldBase BoscoECSWorldBase;
typedef struct _BoscoECSWorldBaseClass BoscoECSWorldBaseClass;

#define BOSCO_ECS_TYPE_WORLD (bosco_ecs_world_get_type ())
#define BOSCO_ECS_WORLD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_WORLD, BoscoECSWorld))
#define BOSCO_ECS_WORLD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_WORLD, BoscoECSWorldClass))
#define BOSCO_ECS_IS_WORLD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_WORLD))
#define BOSCO_ECS_IS_WORLD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_WORLD))
#define BOSCO_ECS_WORLD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_WORLD, BoscoECSWorldClass))

typedef struct _BoscoECSWorld BoscoECSWorld;
typedef struct _BoscoECSWorldClass BoscoECSWorldClass;

#define BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM (bosco_ecs_iinitialize_system_get_type ())
#define BOSCO_ECS_IINITIALIZE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM, BoscoECSIInitializeSystem))
#define BOSCO_ECS_IS_IINITIALIZE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM))
#define BOSCO_ECS_IINITIALIZE_SYSTEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM, BoscoECSIInitializeSystemIface))

typedef struct _BoscoECSIInitializeSystem BoscoECSIInitializeSystem;
typedef struct _BoscoECSIInitializeSystemIface BoscoECSIInitializeSystemIface;

#define BOSCO_ECS_TYPE_IEXECUTE_SYSTEM (bosco_ecs_iexecute_system_get_type ())
#define BOSCO_ECS_IEXECUTE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_IEXECUTE_SYSTEM, BoscoECSIExecuteSystem))
#define BOSCO_ECS_IS_IEXECUTE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_IEXECUTE_SYSTEM))
#define BOSCO_ECS_IEXECUTE_SYSTEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_IEXECUTE_SYSTEM, BoscoECSIExecuteSystemIface))

typedef struct _BoscoECSIExecuteSystem BoscoECSIExecuteSystem;
typedef struct _BoscoECSIExecuteSystemIface BoscoECSIExecuteSystemIface;

#define TYPE_COLLISION_SYSTEM (collision_system_get_type ())
#define COLLISION_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COLLISION_SYSTEM, CollisionSystem))
#define COLLISION_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_COLLISION_SYSTEM, CollisionSystemClass))
#define IS_COLLISION_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COLLISION_SYSTEM))
#define IS_COLLISION_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_COLLISION_SYSTEM))
#define COLLISION_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_COLLISION_SYSTEM, CollisionSystemClass))

typedef struct _CollisionSystem CollisionSystem;
typedef struct _CollisionSystemClass CollisionSystemClass;
typedef struct _CollisionSystemPrivate CollisionSystemPrivate;

#define BOSCO_TYPE_ABSTRACT_GAME (bosco_abstract_game_get_type ())
#define BOSCO_ABSTRACT_GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_TYPE_ABSTRACT_GAME, BoscoAbstractGame))
#define BOSCO_ABSTRACT_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_TYPE_ABSTRACT_GAME, BoscoAbstractGameClass))
#define BOSCO_IS_ABSTRACT_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_TYPE_ABSTRACT_GAME))
#define BOSCO_IS_ABSTRACT_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_TYPE_ABSTRACT_GAME))
#define BOSCO_ABSTRACT_GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_TYPE_ABSTRACT_GAME, BoscoAbstractGameClass))

typedef struct _BoscoAbstractGame BoscoAbstractGame;
typedef struct _BoscoAbstractGameClass BoscoAbstractGameClass;

#define TYPE_GAME (game_get_type ())
#define GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAME, Game))
#define GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAME, GameClass))
#define IS_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAME))
#define IS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAME))
#define GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAME, GameClass))

typedef struct _Game Game;
typedef struct _GameClass GameClass;

#define TYPE_COLLISION_PAIR (collision_pair_get_type ())
#define COLLISION_PAIR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COLLISION_PAIR, CollisionPair))
#define COLLISION_PAIR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_COLLISION_PAIR, CollisionPairClass))
#define IS_COLLISION_PAIR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COLLISION_PAIR))
#define IS_COLLISION_PAIR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_COLLISION_PAIR))
#define COLLISION_PAIR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_COLLISION_PAIR, CollisionPairClass))

typedef struct _CollisionPair CollisionPair;
typedef struct _CollisionPairClass CollisionPairClass;
#define _dark_matter_unref0(var) ((var == NULL) ? NULL : (var = (dark_matter_unref (var), NULL)))

#define BOSCO_ECS_TYPE_IMATCHER (bosco_ecs_imatcher_get_type ())
#define BOSCO_ECS_IMATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_IMATCHER, BoscoECSIMatcher))
#define BOSCO_ECS_IS_IMATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_IMATCHER))
#define BOSCO_ECS_IMATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_IMATCHER, BoscoECSIMatcherIface))

typedef struct _BoscoECSIMatcher BoscoECSIMatcher;
typedef struct _BoscoECSIMatcherIface BoscoECSIMatcherIface;

#define BOSCO_ECS_TYPE_ENTITY_BASE (bosco_ecs_entity_base_get_type ())
#define BOSCO_ECS_ENTITY_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ENTITY_BASE, BoscoECSEntityBase))
#define BOSCO_ECS_ENTITY_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_ENTITY_BASE, BoscoECSEntityBaseClass))
#define BOSCO_ECS_IS_ENTITY_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ENTITY_BASE))
#define BOSCO_ECS_IS_ENTITY_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_ENTITY_BASE))
#define BOSCO_ECS_ENTITY_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_ENTITY_BASE, BoscoECSEntityBaseClass))

typedef struct _BoscoECSEntityBase BoscoECSEntityBase;
typedef struct _BoscoECSEntityBaseClass BoscoECSEntityBaseClass;

#define BOSCO_ECS_TYPE_ENTITY (bosco_ecs_entity_get_type ())
#define BOSCO_ECS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ENTITY, BoscoECSEntity))
#define BOSCO_ECS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_ENTITY, BoscoECSEntityClass))
#define BOSCO_ECS_IS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ENTITY))
#define BOSCO_ECS_IS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_ENTITY))
#define BOSCO_ECS_ENTITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_ENTITY, BoscoECSEntityClass))

typedef struct _BoscoECSEntity BoscoECSEntity;
typedef struct _BoscoECSEntityClass BoscoECSEntityClass;

#define BOSCO_ECS_TYPE_GROUP (bosco_ecs_group_get_type ())
#define BOSCO_ECS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_GROUP, BoscoECSGroup))
#define BOSCO_ECS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_GROUP, BoscoECSGroupClass))
#define BOSCO_ECS_IS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_GROUP))
#define BOSCO_ECS_IS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_GROUP))
#define BOSCO_ECS_GROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_GROUP, BoscoECSGroupClass))

typedef struct _BoscoECSGroup BoscoECSGroup;
typedef struct _BoscoECSGroupClass BoscoECSGroupClass;

#define TYPE_COMPONENT (component_get_type ())

#define TYPE_COLLISION_HANDLER (collision_handler_get_type ())
#define COLLISION_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COLLISION_HANDLER, CollisionHandler))
#define IS_COLLISION_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COLLISION_HANDLER))
#define COLLISION_HANDLER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_COLLISION_HANDLER, CollisionHandlerIface))

typedef struct _CollisionHandler CollisionHandler;
typedef struct _CollisionHandlerIface CollisionHandlerIface;
#define _collision_pair_unref0(var) ((var == NULL) ? NULL : (var = (collision_pair_unref (var), NULL)))
typedef struct _CollisionPairPrivate CollisionPairPrivate;

#define TYPE_POSITION_COMPONENT (position_component_get_type ())
#define POSITION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_POSITION_COMPONENT, PositionComponent))
#define POSITION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_POSITION_COMPONENT, PositionComponentClass))
#define IS_POSITION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_POSITION_COMPONENT))
#define IS_POSITION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_POSITION_COMPONENT))
#define POSITION_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_POSITION_COMPONENT, PositionComponentClass))

typedef struct _PositionComponent PositionComponent;
typedef struct _PositionComponentClass PositionComponentClass;

#define TYPE_HEALTH_COMPONENT (health_component_get_type ())
#define HEALTH_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_HEALTH_COMPONENT, HealthComponent))
#define HEALTH_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_HEALTH_COMPONENT, HealthComponentClass))
#define IS_HEALTH_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_HEALTH_COMPONENT))
#define IS_HEALTH_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_HEALTH_COMPONENT))
#define HEALTH_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_HEALTH_COMPONENT, HealthComponentClass))

typedef struct _HealthComponent HealthComponent;
typedef struct _HealthComponentClass HealthComponentClass;

#define BOSCO_ECS_TYPE_ICOMPONENT (bosco_ecs_icomponent_get_type ())
#define BOSCO_ECS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ICOMPONENT, BoscoECSIComponent))
#define BOSCO_ECS_IS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ICOMPONENT))
#define BOSCO_ECS_ICOMPONENT_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_ICOMPONENT, BoscoECSIComponentIface))

typedef struct _BoscoECSIComponent BoscoECSIComponent;
typedef struct _BoscoECSIComponentIface BoscoECSIComponentIface;
typedef struct _PositionComponentPrivate PositionComponentPrivate;
typedef struct _HealthComponentPrivate HealthComponentPrivate;
typedef struct _ParamSpecCollisionPair ParamSpecCollisionPair;

#define TYPE_BOUNDS_COMPONENT (bounds_component_get_type ())
#define BOUNDS_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BOUNDS_COMPONENT, BoundsComponent))
#define BOUNDS_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_BOUNDS_COMPONENT, BoundsComponentClass))
#define IS_BOUNDS_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BOUNDS_COMPONENT))
#define IS_BOUNDS_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_BOUNDS_COMPONENT))
#define BOUNDS_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_BOUNDS_COMPONENT, BoundsComponentClass))

typedef struct _BoundsComponent BoundsComponent;
typedef struct _BoundsComponentClass BoundsComponentClass;
typedef struct _BoundsComponentPrivate BoundsComponentPrivate;

struct _DarkMatter {
	GTypeInstance parent_instance;
	volatile int ref_count;
	DarkMatterPrivate * priv;
};

struct _DarkMatterClass {
	GTypeClass parent_class;
	void (*finalize) (DarkMatter *self);
};

struct _BoscoECSISystemIface {
	GTypeInterface parent_iface;
};

struct _BoscoECSISetWorldIface {
	GTypeInterface parent_iface;
	void (*setWorld) (BoscoECSISetWorld* self, BoscoECSWorld* world);
};

struct _BoscoECSIInitializeSystemIface {
	GTypeInterface parent_iface;
	void (*initialize) (BoscoECSIInitializeSystem* self);
};

struct _BoscoECSIExecuteSystemIface {
	GTypeInterface parent_iface;
	void (*execute) (BoscoECSIExecuteSystem* self);
};

struct _CollisionSystem {
	DarkMatter parent_instance;
	CollisionSystemPrivate * priv;
};

struct _CollisionSystemClass {
	DarkMatterClass parent_class;
};

struct _CollisionSystemPrivate {
	BoscoECSWorld* _world;
	Game* _game;
	CollisionPair** _collisionPairs;
	gint _collisionPairs_length1;
	gint __collisionPairs_size_;
};

struct _BoscoECSIMatcherIface {
	GTypeInterface parent_iface;
	gboolean (*matches) (BoscoECSIMatcher* self, BoscoECSEntity* entity);
	gchar* (*toString) (BoscoECSIMatcher* self);
	const gchar* (*get_id) (BoscoECSIMatcher* self);
	gint* (*get_indices) (BoscoECSIMatcher* self, int* result_length1);
};

typedef enum  {
	COMPONENT_Bounds,
	COMPONENT_Bullet,
	COMPONENT_ColorTween,
	COMPONENT_Destroy,
	COMPONENT_Enemy,
	COMPONENT_Expires,
	COMPONENT_Firing,
	COMPONENT_Health,
	COMPONENT_Layer,
	COMPONENT_Life,
	COMPONENT_Mine,
	COMPONENT_Mouse,
	COMPONENT_Player,
	COMPONENT_Position,
	COMPONENT_Resource,
	COMPONENT_ScaleTween,
	COMPONENT_Scale,
	COMPONENT_Score,
	COMPONENT_SoundEffect,
	COMPONENT_Tint,
	COMPONENT_Velocity,
	COMPONENT_TotalComponents
} Component;

struct _CollisionHandlerIface {
	GTypeInterface parent_iface;
	void (*handleCollision) (CollisionHandler* self, BoscoECSEntity* a, BoscoECSEntity* b);
	BoscoECSGroup* (*get_groupEntitiesA) (CollisionHandler* self);
	void (*set_groupEntitiesA) (CollisionHandler* self, BoscoECSGroup* value);
	BoscoECSGroup* (*get_groupEntitiesB) (CollisionHandler* self);
	void (*set_groupEntitiesB) (CollisionHandler* self, BoscoECSGroup* value);
};

struct _CollisionPair {
	GTypeInstance parent_instance;
	volatile int ref_count;
	CollisionPairPrivate * priv;
};

struct _CollisionPairClass {
	GTypeClass parent_class;
	void (*finalize) (CollisionPair *self);
};

struct _CollisionPairPrivate {
	BoscoECSGroup* _groupEntitiesA;
	BoscoECSGroup* _groupEntitiesB;
};

struct _BoscoECSIComponentIface {
	GTypeInterface parent_iface;
};

struct _PositionComponent {
	DarkMatter parent_instance;
	PositionComponentPrivate * priv;
	gdouble x;
	gdouble y;
};

struct _PositionComponentClass {
	DarkMatterClass parent_class;
};

struct _HealthComponent {
	DarkMatter parent_instance;
	HealthComponentPrivate * priv;
	gdouble health;
	gdouble maximumHealth;
};

struct _HealthComponentClass {
	DarkMatterClass parent_class;
};

struct _ParamSpecCollisionPair {
	GParamSpec parent_instance;
};

struct _BoundsComponent {
	DarkMatter parent_instance;
	BoundsComponentPrivate * priv;
	gdouble radius;
};

struct _BoundsComponentClass {
	DarkMatterClass parent_class;
};


static gpointer collision_system_parent_class = NULL;
static BoscoECSISystemIface* collision_system_bosco_ecs_isystem_parent_iface = NULL;
static BoscoECSISetWorldIface* collision_system_bosco_ecs_iset_world_parent_iface = NULL;
static BoscoECSIInitializeSystemIface* collision_system_bosco_ecs_iinitialize_system_parent_iface = NULL;
static BoscoECSIExecuteSystemIface* collision_system_bosco_ecs_iexecute_system_parent_iface = NULL;
static gpointer collision_pair_parent_class = NULL;
static CollisionHandlerIface* collision_pair_collision_handler_parent_iface = NULL;

gpointer dark_matter_ref (gpointer instance);
void dark_matter_unref (gpointer instance);
GParamSpec* param_spec_dark_matter (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_dark_matter (GValue* value, gpointer v_object);
void value_take_dark_matter (GValue* value, gpointer v_object);
gpointer value_get_dark_matter (const GValue* value);
GType dark_matter_get_type (void) G_GNUC_CONST;
GType bosco_ecs_isystem_get_type (void) G_GNUC_CONST;
GType bosco_ecs_world_base_get_type (void) G_GNUC_CONST;
GType bosco_ecs_world_get_type (void) G_GNUC_CONST;
GType bosco_ecs_iset_world_get_type (void) G_GNUC_CONST;
GType bosco_ecs_iinitialize_system_get_type (void) G_GNUC_CONST;
GType bosco_ecs_iexecute_system_get_type (void) G_GNUC_CONST;
GType collision_system_get_type (void) G_GNUC_CONST;
GType bosco_abstract_game_get_type (void) G_GNUC_CONST;
GType game_get_type (void) G_GNUC_CONST;
gpointer collision_pair_ref (gpointer instance);
void collision_pair_unref (gpointer instance);
GParamSpec* param_spec_collision_pair (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_collision_pair (GValue* value, gpointer v_object);
void value_take_collision_pair (GValue* value, gpointer v_object);
gpointer value_get_collision_pair (const GValue* value);
GType collision_pair_get_type (void) G_GNUC_CONST;
#define COLLISION_SYSTEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_COLLISION_SYSTEM, CollisionSystemPrivate))
enum  {
	COLLISION_SYSTEM_DUMMY_PROPERTY
};
CollisionSystem* collision_system_new (Game* game);
CollisionSystem* collision_system_construct (GType object_type, Game* game);
DarkMatter* dark_matter_new (void);
DarkMatter* dark_matter_construct (GType object_type);
static void collision_system_real_setWorld (BoscoECSISetWorld* base, BoscoECSWorld* world);
static void collision_system_real_initialize (BoscoECSIInitializeSystem* base);
GType bosco_ecs_entity_base_get_type (void) G_GNUC_CONST;
GType bosco_ecs_entity_get_type (void) G_GNUC_CONST;
GType bosco_ecs_imatcher_get_type (void) G_GNUC_CONST;
GType bosco_ecs_group_get_type (void) G_GNUC_CONST;
BoscoECSGroup* bosco_ecs_world_base_getGroup (BoscoECSWorldBase* self, BoscoECSIMatcher* matcher);
BoscoECSIMatcher* bosco_ecs_matcher_AllOf (gint* args, int args_length1);
GType component_get_type (void) G_GNUC_CONST;
CollisionPair* collision_pair_new (BoscoECSGroup* group1, BoscoECSGroup* group2);
CollisionPair* collision_pair_construct (GType object_type, BoscoECSGroup* group1, BoscoECSGroup* group2);
static void collision_system_real_execute (BoscoECSIExecuteSystem* base);
GType collision_handler_get_type (void) G_GNUC_CONST;
void collision_handler_checkForCollisions (CollisionHandler* self);
static void collision_system_finalize (DarkMatter* obj);
#define COLLISION_PAIR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_COLLISION_PAIR, CollisionPairPrivate))
enum  {
	COLLISION_PAIR_DUMMY_PROPERTY
};
static void collision_pair_real_handleCollision (CollisionHandler* base, BoscoECSEntity* bullet, BoscoECSEntity* ship);
GType position_component_get_type (void) G_GNUC_CONST;
PositionComponent* bosco_ecs_entity_get_position (BoscoECSEntity* self);
GType health_component_get_type (void) G_GNUC_CONST;
HealthComponent* bosco_ecs_entity_get_health (BoscoECSEntity* self);
GType bosco_ecs_icomponent_get_type (void) G_GNUC_CONST;
BoscoECSEntity* createBang (gdouble x, gdouble y);
BoscoECSEntity* createParticle (gdouble x, gdouble y);
gboolean bosco_ecs_entity_get_isDestroy (BoscoECSEntity* self);
BoscoECSEntity* bosco_ecs_entity_setDestroy (BoscoECSEntity* self, gboolean value);
BoscoECSEntity* createExplosion (gdouble x, gdouble y);
static void collision_pair_finalize (CollisionPair* obj);
void collision_handler_handleCollision (CollisionHandler* self, BoscoECSEntity* a, BoscoECSEntity* b);
BoscoECSGroup* collision_handler_get_groupEntitiesA (CollisionHandler* self);
BoscoECSEntity** bosco_ecs_group_getEntities (BoscoECSGroup* self, int* result_length1);
BoscoECSGroup* collision_handler_get_groupEntitiesB (CollisionHandler* self);
gboolean collision_handler_collisionExists (CollisionHandler* self, BoscoECSEntity* e1, BoscoECSEntity* e2);
GType bounds_component_get_type (void) G_GNUC_CONST;
BoundsComponent* bosco_ecs_entity_get_bounds (BoscoECSEntity* self);
void collision_handler_set_groupEntitiesA (CollisionHandler* self, BoscoECSGroup* value);
void collision_handler_set_groupEntitiesB (CollisionHandler* self, BoscoECSGroup* value);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gpointer _dark_matter_ref0 (gpointer self) {
	return self ? dark_matter_ref (self) : NULL;
}


CollisionSystem* collision_system_construct (GType object_type, Game* game) {
	CollisionSystem* self = NULL;
	Game* _tmp0_ = NULL;
	Game* _tmp1_ = NULL;
	g_return_val_if_fail (game != NULL, NULL);
	self = (CollisionSystem*) dark_matter_construct (object_type);
	_tmp0_ = game;
	_tmp1_ = _dark_matter_ref0 (_tmp0_);
	_dark_matter_unref0 (self->priv->_game);
	self->priv->_game = _tmp1_;
	return self;
}


CollisionSystem* collision_system_new (Game* game) {
	return collision_system_construct (TYPE_COLLISION_SYSTEM, game);
}


static void collision_system_real_setWorld (BoscoECSISetWorld* base, BoscoECSWorld* world) {
	CollisionSystem * self;
	BoscoECSWorld* _tmp0_ = NULL;
	BoscoECSWorld* _tmp1_ = NULL;
	self = (CollisionSystem*) base;
	g_return_if_fail (world != NULL);
	_tmp0_ = world;
	_tmp1_ = _dark_matter_ref0 (_tmp0_);
	_dark_matter_unref0 (self->priv->_world);
	self->priv->_world = _tmp1_;
}


static void collision_system_real_initialize (BoscoECSIInitializeSystem* base) {
	CollisionSystem * self;
	BoscoECSWorld* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint* _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	BoscoECSIMatcher* _tmp3_ = NULL;
	BoscoECSIMatcher* _tmp4_ = NULL;
	BoscoECSGroup* _tmp5_ = NULL;
	BoscoECSGroup* _tmp6_ = NULL;
	BoscoECSWorld* _tmp7_ = NULL;
	gint* _tmp8_ = NULL;
	gint* _tmp9_ = NULL;
	gint _tmp9__length1 = 0;
	BoscoECSIMatcher* _tmp10_ = NULL;
	BoscoECSIMatcher* _tmp11_ = NULL;
	BoscoECSGroup* _tmp12_ = NULL;
	BoscoECSGroup* _tmp13_ = NULL;
	CollisionPair* _tmp14_ = NULL;
	CollisionPair** _tmp15_ = NULL;
	self = (CollisionSystem*) base;
	_tmp0_ = self->priv->_world;
	_tmp1_ = g_new0 (gint, 1);
	_tmp1_[0] = (gint) COMPONENT_Bullet;
	_tmp2_ = _tmp1_;
	_tmp2__length1 = 1;
	_tmp3_ = bosco_ecs_matcher_AllOf (_tmp2_, 1);
	_tmp4_ = _tmp3_;
	_tmp5_ = bosco_ecs_world_base_getGroup ((BoscoECSWorldBase*) _tmp0_, _tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = self->priv->_world;
	_tmp8_ = g_new0 (gint, 1);
	_tmp8_[0] = (gint) COMPONENT_Enemy;
	_tmp9_ = _tmp8_;
	_tmp9__length1 = 1;
	_tmp10_ = bosco_ecs_matcher_AllOf (_tmp9_, 1);
	_tmp11_ = _tmp10_;
	_tmp12_ = bosco_ecs_world_base_getGroup ((BoscoECSWorldBase*) _tmp7_, _tmp11_);
	_tmp13_ = _tmp12_;
	_tmp14_ = collision_pair_new (_tmp6_, _tmp13_);
	_tmp15_ = g_new0 (CollisionPair*, 1 + 1);
	_tmp15_[0] = _tmp14_;
	self->priv->_collisionPairs = (_vala_array_free (self->priv->_collisionPairs, self->priv->_collisionPairs_length1, (GDestroyNotify) collision_pair_unref), NULL);
	self->priv->_collisionPairs = _tmp15_;
	self->priv->_collisionPairs_length1 = 1;
	self->priv->__collisionPairs_size_ = self->priv->_collisionPairs_length1;
	_dark_matter_unref0 (_tmp13_);
	_dark_matter_unref0 (_tmp11_);
	_tmp9_ = (g_free (_tmp9_), NULL);
	_dark_matter_unref0 (_tmp6_);
	_dark_matter_unref0 (_tmp4_);
	_tmp2_ = (g_free (_tmp2_), NULL);
}


static gpointer _collision_pair_ref0 (gpointer self) {
	return self ? collision_pair_ref (self) : NULL;
}


static void collision_system_real_execute (BoscoECSIExecuteSystem* base) {
	CollisionSystem * self;
	CollisionPair** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	self = (CollisionSystem*) base;
	_tmp0_ = self->priv->_collisionPairs;
	_tmp0__length1 = self->priv->_collisionPairs_length1;
	{
		CollisionPair** pair_collection = NULL;
		gint pair_collection_length1 = 0;
		gint _pair_collection_size_ = 0;
		gint pair_it = 0;
		pair_collection = _tmp0_;
		pair_collection_length1 = _tmp0__length1;
		for (pair_it = 0; pair_it < _tmp0__length1; pair_it = pair_it + 1) {
			CollisionPair* _tmp1_ = NULL;
			CollisionPair* pair = NULL;
			_tmp1_ = _collision_pair_ref0 (pair_collection[pair_it]);
			pair = _tmp1_;
			{
				CollisionPair* _tmp2_ = NULL;
				_tmp2_ = pair;
				collision_handler_checkForCollisions ((CollisionHandler*) _tmp2_);
				_collision_pair_unref0 (pair);
			}
		}
	}
}


static void collision_system_class_init (CollisionSystemClass * klass) {
	collision_system_parent_class = g_type_class_peek_parent (klass);
	((DarkMatterClass *) klass)->finalize = collision_system_finalize;
	g_type_class_add_private (klass, sizeof (CollisionSystemPrivate));
}


static void collision_system_bosco_ecs_isystem_interface_init (BoscoECSISystemIface * iface) {
	collision_system_bosco_ecs_isystem_parent_iface = g_type_interface_peek_parent (iface);
}


static void collision_system_bosco_ecs_iset_world_interface_init (BoscoECSISetWorldIface * iface) {
	collision_system_bosco_ecs_iset_world_parent_iface = g_type_interface_peek_parent (iface);
	iface->setWorld = (void (*)(BoscoECSISetWorld*, BoscoECSWorld*)) collision_system_real_setWorld;
}


static void collision_system_bosco_ecs_iinitialize_system_interface_init (BoscoECSIInitializeSystemIface * iface) {
	collision_system_bosco_ecs_iinitialize_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->initialize = (void (*)(BoscoECSIInitializeSystem*)) collision_system_real_initialize;
}


static void collision_system_bosco_ecs_iexecute_system_interface_init (BoscoECSIExecuteSystemIface * iface) {
	collision_system_bosco_ecs_iexecute_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->execute = (void (*)(BoscoECSIExecuteSystem*)) collision_system_real_execute;
}


static void collision_system_instance_init (CollisionSystem * self) {
	self->priv = COLLISION_SYSTEM_GET_PRIVATE (self);
}


static void collision_system_finalize (DarkMatter* obj) {
	CollisionSystem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_COLLISION_SYSTEM, CollisionSystem);
	_dark_matter_unref0 (self->priv->_world);
	_dark_matter_unref0 (self->priv->_game);
	self->priv->_collisionPairs = (_vala_array_free (self->priv->_collisionPairs, self->priv->_collisionPairs_length1, (GDestroyNotify) collision_pair_unref), NULL);
	DARK_MATTER_CLASS (collision_system_parent_class)->finalize (obj);
}


GType collision_system_get_type (void) {
	static volatile gsize collision_system_type_id__volatile = 0;
	if (g_once_init_enter (&collision_system_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CollisionSystemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) collision_system_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CollisionSystem), 0, (GInstanceInitFunc) collision_system_instance_init, NULL };
		static const GInterfaceInfo bosco_ecs_isystem_info = { (GInterfaceInitFunc) collision_system_bosco_ecs_isystem_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo bosco_ecs_iset_world_info = { (GInterfaceInitFunc) collision_system_bosco_ecs_iset_world_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo bosco_ecs_iinitialize_system_info = { (GInterfaceInitFunc) collision_system_bosco_ecs_iinitialize_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo bosco_ecs_iexecute_system_info = { (GInterfaceInitFunc) collision_system_bosco_ecs_iexecute_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType collision_system_type_id;
		collision_system_type_id = g_type_register_static (TYPE_DARK_MATTER, "CollisionSystem", &g_define_type_info, 0);
		g_type_add_interface_static (collision_system_type_id, BOSCO_ECS_TYPE_ISYSTEM, &bosco_ecs_isystem_info);
		g_type_add_interface_static (collision_system_type_id, BOSCO_ECS_TYPE_ISET_WORLD, &bosco_ecs_iset_world_info);
		g_type_add_interface_static (collision_system_type_id, BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM, &bosco_ecs_iinitialize_system_info);
		g_type_add_interface_static (collision_system_type_id, BOSCO_ECS_TYPE_IEXECUTE_SYSTEM, &bosco_ecs_iexecute_system_info);
		g_once_init_leave (&collision_system_type_id__volatile, collision_system_type_id);
	}
	return collision_system_type_id__volatile;
}


CollisionPair* collision_pair_construct (GType object_type, BoscoECSGroup* group1, BoscoECSGroup* group2) {
	CollisionPair* self = NULL;
	BoscoECSGroup* _tmp0_ = NULL;
	BoscoECSGroup* _tmp1_ = NULL;
	BoscoECSGroup* _tmp2_ = NULL;
	BoscoECSGroup* _tmp3_ = NULL;
	g_return_val_if_fail (group1 != NULL, NULL);
	g_return_val_if_fail (group2 != NULL, NULL);
	self = (CollisionPair*) g_type_create_instance (object_type);
	_tmp0_ = group1;
	_tmp1_ = _dark_matter_ref0 (_tmp0_);
	_dark_matter_unref0 (self->priv->_groupEntitiesA);
	self->priv->_groupEntitiesA = _tmp1_;
	_tmp2_ = group2;
	_tmp3_ = _dark_matter_ref0 (_tmp2_);
	_dark_matter_unref0 (self->priv->_groupEntitiesB);
	self->priv->_groupEntitiesB = _tmp3_;
	return self;
}


CollisionPair* collision_pair_new (BoscoECSGroup* group1, BoscoECSGroup* group2) {
	return collision_pair_construct (TYPE_COLLISION_PAIR, group1, group2);
}


static void collision_pair_real_handleCollision (CollisionHandler* base, BoscoECSEntity* bullet, BoscoECSEntity* ship) {
	CollisionPair * self;
	PositionComponent* bp = NULL;
	BoscoECSEntity* _tmp0_ = NULL;
	PositionComponent* _tmp1_ = NULL;
	PositionComponent* _tmp2_ = NULL;
	PositionComponent* _tmp3_ = NULL;
	HealthComponent* health = NULL;
	BoscoECSEntity* _tmp4_ = NULL;
	HealthComponent* _tmp5_ = NULL;
	HealthComponent* _tmp6_ = NULL;
	HealthComponent* _tmp7_ = NULL;
	PositionComponent* position = NULL;
	BoscoECSEntity* _tmp8_ = NULL;
	PositionComponent* _tmp9_ = NULL;
	PositionComponent* _tmp10_ = NULL;
	PositionComponent* _tmp11_ = NULL;
	gdouble x = 0.0;
	PositionComponent* _tmp12_ = NULL;
	gdouble _tmp13_ = 0.0;
	gdouble y = 0.0;
	PositionComponent* _tmp14_ = NULL;
	gdouble _tmp15_ = 0.0;
	gdouble _tmp16_ = 0.0;
	gdouble _tmp17_ = 0.0;
	BoscoECSEntity* _tmp18_ = NULL;
	BoscoECSEntity* _tmp19_ = NULL;
	gint i = 0;
	BoscoECSEntity* _tmp26_ = NULL;
	gboolean _tmp27_ = FALSE;
	gboolean _tmp28_ = FALSE;
	HealthComponent* _tmp32_ = NULL;
	HealthComponent* _tmp33_ = NULL;
	gdouble _tmp34_ = 0.0;
	HealthComponent* _tmp35_ = NULL;
	gdouble _tmp36_ = 0.0;
	self = (CollisionPair*) base;
	g_return_if_fail (bullet != NULL);
	g_return_if_fail (ship != NULL);
	_tmp0_ = bullet;
	_tmp1_ = bosco_ecs_entity_get_position (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = _dark_matter_ref0 (_tmp2_);
	bp = _tmp3_;
	_tmp4_ = ship;
	_tmp5_ = bosco_ecs_entity_get_health (_tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = _dark_matter_ref0 (_tmp6_);
	health = _tmp7_;
	_tmp8_ = ship;
	_tmp9_ = bosco_ecs_entity_get_position (_tmp8_);
	_tmp10_ = _tmp9_;
	_tmp11_ = _dark_matter_ref0 (_tmp10_);
	position = _tmp11_;
	_tmp12_ = bp;
	_tmp13_ = _tmp12_->x;
	x = _tmp13_;
	_tmp14_ = bp;
	_tmp15_ = _tmp14_->y;
	y = _tmp15_;
	_tmp16_ = x;
	_tmp17_ = y;
	_tmp18_ = createBang (_tmp16_, _tmp17_);
	_tmp19_ = _tmp18_;
	_dark_matter_unref0 (_tmp19_);
	i = 5;
	while (TRUE) {
		gint _tmp20_ = 0;
		gint _tmp21_ = 0;
		gdouble _tmp22_ = 0.0;
		gdouble _tmp23_ = 0.0;
		BoscoECSEntity* _tmp24_ = NULL;
		BoscoECSEntity* _tmp25_ = NULL;
		_tmp20_ = i;
		i = _tmp20_ - 1;
		_tmp21_ = i;
		if (!(_tmp21_ > 0)) {
			break;
		}
		_tmp22_ = x;
		_tmp23_ = y;
		_tmp24_ = createParticle (_tmp22_, _tmp23_);
		_tmp25_ = _tmp24_;
		_dark_matter_unref0 (_tmp25_);
	}
	_tmp26_ = bullet;
	_tmp27_ = bosco_ecs_entity_get_isDestroy (_tmp26_);
	_tmp28_ = _tmp27_;
	if (!_tmp28_) {
		BoscoECSEntity* _tmp29_ = NULL;
		BoscoECSEntity* _tmp30_ = NULL;
		BoscoECSEntity* _tmp31_ = NULL;
		_tmp29_ = bullet;
		_tmp30_ = bosco_ecs_entity_setDestroy (_tmp29_, TRUE);
		_tmp31_ = _tmp30_;
		_dark_matter_unref0 (_tmp31_);
	}
	_tmp32_ = health;
	_tmp33_ = health;
	_tmp34_ = _tmp33_->health;
	_tmp33_->health = _tmp34_ - 1;
	_tmp35_ = health;
	_tmp36_ = _tmp35_->health;
	if (_tmp36_ < ((gdouble) 0)) {
		BoscoECSEntity* _tmp37_ = NULL;
		gboolean _tmp38_ = FALSE;
		gboolean _tmp39_ = FALSE;
		PositionComponent* _tmp43_ = NULL;
		gdouble _tmp44_ = 0.0;
		PositionComponent* _tmp45_ = NULL;
		gdouble _tmp46_ = 0.0;
		BoscoECSEntity* _tmp47_ = NULL;
		BoscoECSEntity* _tmp48_ = NULL;
		_tmp37_ = ship;
		_tmp38_ = bosco_ecs_entity_get_isDestroy (_tmp37_);
		_tmp39_ = _tmp38_;
		if (!_tmp39_) {
			BoscoECSEntity* _tmp40_ = NULL;
			BoscoECSEntity* _tmp41_ = NULL;
			BoscoECSEntity* _tmp42_ = NULL;
			_tmp40_ = ship;
			_tmp41_ = bosco_ecs_entity_setDestroy (_tmp40_, TRUE);
			_tmp42_ = _tmp41_;
			_dark_matter_unref0 (_tmp42_);
		}
		_tmp43_ = position;
		_tmp44_ = _tmp43_->x;
		_tmp45_ = position;
		_tmp46_ = _tmp45_->y;
		_tmp47_ = createExplosion (_tmp44_, _tmp46_);
		_tmp48_ = _tmp47_;
		_dark_matter_unref0 (_tmp48_);
	}
	_dark_matter_unref0 (position);
	_dark_matter_unref0 (health);
	_dark_matter_unref0 (bp);
}


static BoscoECSGroup* collision_pair_real_get_groupEntitiesA (CollisionHandler* base) {
	BoscoECSGroup* result;
	CollisionPair* self;
	BoscoECSGroup* _tmp0_ = NULL;
	self = (CollisionPair*) base;
	_tmp0_ = self->priv->_groupEntitiesA;
	result = _tmp0_;
	return result;
}


static void collision_pair_real_set_groupEntitiesA (CollisionHandler* base, BoscoECSGroup* value) {
	CollisionPair* self;
	BoscoECSGroup* _tmp0_ = NULL;
	BoscoECSGroup* _tmp1_ = NULL;
	self = (CollisionPair*) base;
	_tmp0_ = value;
	_tmp1_ = _dark_matter_ref0 (_tmp0_);
	_dark_matter_unref0 (self->priv->_groupEntitiesA);
	self->priv->_groupEntitiesA = _tmp1_;
}


static BoscoECSGroup* collision_pair_real_get_groupEntitiesB (CollisionHandler* base) {
	BoscoECSGroup* result;
	CollisionPair* self;
	BoscoECSGroup* _tmp0_ = NULL;
	self = (CollisionPair*) base;
	_tmp0_ = self->priv->_groupEntitiesB;
	result = _tmp0_;
	return result;
}


static void collision_pair_real_set_groupEntitiesB (CollisionHandler* base, BoscoECSGroup* value) {
	CollisionPair* self;
	BoscoECSGroup* _tmp0_ = NULL;
	BoscoECSGroup* _tmp1_ = NULL;
	self = (CollisionPair*) base;
	_tmp0_ = value;
	_tmp1_ = _dark_matter_ref0 (_tmp0_);
	_dark_matter_unref0 (self->priv->_groupEntitiesB);
	self->priv->_groupEntitiesB = _tmp1_;
}


static void value_collision_pair_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_collision_pair_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		collision_pair_unref (value->data[0].v_pointer);
	}
}


static void value_collision_pair_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = collision_pair_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_collision_pair_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_collision_pair_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		CollisionPair* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = collision_pair_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_collision_pair_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	CollisionPair** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = collision_pair_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_collision_pair (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecCollisionPair* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_COLLISION_PAIR), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_collision_pair (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_COLLISION_PAIR), NULL);
	return value->data[0].v_pointer;
}


void value_set_collision_pair (GValue* value, gpointer v_object) {
	CollisionPair* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_COLLISION_PAIR));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_COLLISION_PAIR));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		collision_pair_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		collision_pair_unref (old);
	}
}


void value_take_collision_pair (GValue* value, gpointer v_object) {
	CollisionPair* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_COLLISION_PAIR));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_COLLISION_PAIR));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		collision_pair_unref (old);
	}
}


static void collision_pair_class_init (CollisionPairClass * klass) {
	collision_pair_parent_class = g_type_class_peek_parent (klass);
	((CollisionPairClass *) klass)->finalize = collision_pair_finalize;
	g_type_class_add_private (klass, sizeof (CollisionPairPrivate));
}


static void collision_pair_collision_handler_interface_init (CollisionHandlerIface * iface) {
	collision_pair_collision_handler_parent_iface = g_type_interface_peek_parent (iface);
	iface->handleCollision = (void (*)(CollisionHandler*, BoscoECSEntity*, BoscoECSEntity*)) collision_pair_real_handleCollision;
	iface->get_groupEntitiesA = collision_pair_real_get_groupEntitiesA;
	iface->set_groupEntitiesA = collision_pair_real_set_groupEntitiesA;
	iface->get_groupEntitiesB = collision_pair_real_get_groupEntitiesB;
	iface->set_groupEntitiesB = collision_pair_real_set_groupEntitiesB;
}


static void collision_pair_instance_init (CollisionPair * self) {
	self->priv = COLLISION_PAIR_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void collision_pair_finalize (CollisionPair* obj) {
	CollisionPair * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_COLLISION_PAIR, CollisionPair);
	g_signal_handlers_destroy (self);
	_dark_matter_unref0 (self->priv->_groupEntitiesA);
	_dark_matter_unref0 (self->priv->_groupEntitiesB);
}


GType collision_pair_get_type (void) {
	static volatile gsize collision_pair_type_id__volatile = 0;
	if (g_once_init_enter (&collision_pair_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_collision_pair_init, value_collision_pair_free_value, value_collision_pair_copy_value, value_collision_pair_peek_pointer, "p", value_collision_pair_collect_value, "p", value_collision_pair_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (CollisionPairClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) collision_pair_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CollisionPair), 0, (GInstanceInitFunc) collision_pair_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		static const GInterfaceInfo collision_handler_info = { (GInterfaceInitFunc) collision_pair_collision_handler_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType collision_pair_type_id;
		collision_pair_type_id = g_type_register_fundamental (g_type_fundamental_next (), "CollisionPair", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_type_add_interface_static (collision_pair_type_id, TYPE_COLLISION_HANDLER, &collision_handler_info);
		g_once_init_leave (&collision_pair_type_id__volatile, collision_pair_type_id);
	}
	return collision_pair_type_id__volatile;
}


gpointer collision_pair_ref (gpointer instance) {
	CollisionPair* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void collision_pair_unref (gpointer instance) {
	CollisionPair* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		COLLISION_PAIR_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


void collision_handler_handleCollision (CollisionHandler* self, BoscoECSEntity* a, BoscoECSEntity* b) {
	g_return_if_fail (self != NULL);
	COLLISION_HANDLER_GET_INTERFACE (self)->handleCollision (self, a, b);
}


void collision_handler_checkForCollisions (CollisionHandler* self) {
	BoscoECSGroup* _tmp0_ = NULL;
	BoscoECSGroup* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	BoscoECSEntity** _tmp3_ = NULL;
	_tmp0_ = collision_handler_get_groupEntitiesA (self);
	_tmp1_ = _tmp0_;
	_tmp3_ = bosco_ecs_group_getEntities (_tmp1_, &_tmp2_);
	{
		BoscoECSEntity** entityA_collection = NULL;
		gint entityA_collection_length1 = 0;
		gint _entityA_collection_size_ = 0;
		gint entityA_it = 0;
		entityA_collection = _tmp3_;
		entityA_collection_length1 = _tmp2_;
		for (entityA_it = 0; entityA_it < _tmp2_; entityA_it = entityA_it + 1) {
			BoscoECSEntity* _tmp4_ = NULL;
			BoscoECSEntity* entityA = NULL;
			_tmp4_ = _dark_matter_ref0 (entityA_collection[entityA_it]);
			entityA = _tmp4_;
			{
				BoscoECSGroup* _tmp5_ = NULL;
				BoscoECSGroup* _tmp6_ = NULL;
				gint _tmp7_ = 0;
				BoscoECSEntity** _tmp8_ = NULL;
				_tmp5_ = collision_handler_get_groupEntitiesB (self);
				_tmp6_ = _tmp5_;
				_tmp8_ = bosco_ecs_group_getEntities (_tmp6_, &_tmp7_);
				{
					BoscoECSEntity** entityB_collection = NULL;
					gint entityB_collection_length1 = 0;
					gint _entityB_collection_size_ = 0;
					gint entityB_it = 0;
					entityB_collection = _tmp8_;
					entityB_collection_length1 = _tmp7_;
					for (entityB_it = 0; entityB_it < _tmp7_; entityB_it = entityB_it + 1) {
						BoscoECSEntity* _tmp9_ = NULL;
						BoscoECSEntity* entityB = NULL;
						_tmp9_ = _dark_matter_ref0 (entityB_collection[entityB_it]);
						entityB = _tmp9_;
						{
							BoscoECSEntity* _tmp10_ = NULL;
							BoscoECSEntity* _tmp11_ = NULL;
							gboolean _tmp12_ = FALSE;
							_tmp10_ = entityA;
							_tmp11_ = entityB;
							_tmp12_ = collision_handler_collisionExists (self, _tmp10_, _tmp11_);
							if (_tmp12_) {
								BoscoECSEntity* _tmp13_ = NULL;
								BoscoECSEntity* _tmp14_ = NULL;
								_tmp13_ = entityA;
								_tmp14_ = entityB;
								collision_handler_handleCollision (self, _tmp13_, _tmp14_);
							}
							_dark_matter_unref0 (entityB);
						}
					}
					entityB_collection = (_vala_array_free (entityB_collection, entityB_collection_length1, (GDestroyNotify) dark_matter_unref), NULL);
				}
				_dark_matter_unref0 (entityA);
			}
		}
		entityA_collection = (_vala_array_free (entityA_collection, entityA_collection_length1, (GDestroyNotify) dark_matter_unref), NULL);
	}
}


gboolean collision_handler_collisionExists (CollisionHandler* self, BoscoECSEntity* e1, BoscoECSEntity* e2) {
	gboolean result = FALSE;
	gboolean _result_ = FALSE;
	gboolean _tmp0_ = FALSE;
	BoscoECSEntity* _tmp1_ = NULL;
	PositionComponent* p1 = NULL;
	BoscoECSEntity* _tmp3_ = NULL;
	PositionComponent* _tmp4_ = NULL;
	PositionComponent* _tmp5_ = NULL;
	PositionComponent* _tmp6_ = NULL;
	PositionComponent* p2 = NULL;
	BoscoECSEntity* _tmp7_ = NULL;
	PositionComponent* _tmp8_ = NULL;
	PositionComponent* _tmp9_ = NULL;
	PositionComponent* _tmp10_ = NULL;
	BoundsComponent* b1 = NULL;
	BoscoECSEntity* _tmp11_ = NULL;
	BoundsComponent* _tmp12_ = NULL;
	BoundsComponent* _tmp13_ = NULL;
	BoundsComponent* _tmp14_ = NULL;
	BoundsComponent* b2 = NULL;
	BoscoECSEntity* _tmp15_ = NULL;
	BoundsComponent* _tmp16_ = NULL;
	BoundsComponent* _tmp17_ = NULL;
	BoundsComponent* _tmp18_ = NULL;
	gdouble a = 0.0;
	PositionComponent* _tmp19_ = NULL;
	gdouble _tmp20_ = 0.0;
	PositionComponent* _tmp21_ = NULL;
	gdouble _tmp22_ = 0.0;
	gdouble b = 0.0;
	PositionComponent* _tmp23_ = NULL;
	gdouble _tmp24_ = 0.0;
	PositionComponent* _tmp25_ = NULL;
	gdouble _tmp26_ = 0.0;
	gdouble _tmp27_ = 0.0;
	gdouble _tmp28_ = 0.0;
	gdouble _tmp29_ = 0.0;
	gdouble _tmp30_ = 0.0;
	gdouble _tmp31_ = 0.0;
	BoundsComponent* _tmp32_ = NULL;
	gdouble _tmp33_ = 0.0;
	BoundsComponent* _tmp34_ = NULL;
	gdouble _tmp35_ = 0.0;
	g_return_val_if_fail (e1 != NULL, FALSE);
	g_return_val_if_fail (e2 != NULL, FALSE);
	_result_ = FALSE;
	_tmp1_ = e1;
	if (_tmp1_ == NULL) {
		_tmp0_ = TRUE;
	} else {
		BoscoECSEntity* _tmp2_ = NULL;
		_tmp2_ = e2;
		_tmp0_ = _tmp2_ == NULL;
	}
	if (_tmp0_) {
		result = _result_;
		return result;
	}
	_tmp3_ = e1;
	_tmp4_ = bosco_ecs_entity_get_position (_tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = _dark_matter_ref0 (_tmp5_);
	p1 = _tmp6_;
	_tmp7_ = e2;
	_tmp8_ = bosco_ecs_entity_get_position (_tmp7_);
	_tmp9_ = _tmp8_;
	_tmp10_ = _dark_matter_ref0 (_tmp9_);
	p2 = _tmp10_;
	_tmp11_ = e1;
	_tmp12_ = bosco_ecs_entity_get_bounds (_tmp11_);
	_tmp13_ = _tmp12_;
	_tmp14_ = _dark_matter_ref0 (_tmp13_);
	b1 = _tmp14_;
	_tmp15_ = e2;
	_tmp16_ = bosco_ecs_entity_get_bounds (_tmp15_);
	_tmp17_ = _tmp16_;
	_tmp18_ = _dark_matter_ref0 (_tmp17_);
	b2 = _tmp18_;
	_tmp19_ = p1;
	_tmp20_ = _tmp19_->x;
	_tmp21_ = p2;
	_tmp22_ = _tmp21_->x;
	a = _tmp20_ - _tmp22_;
	_tmp23_ = p1;
	_tmp24_ = _tmp23_->y;
	_tmp25_ = p2;
	_tmp26_ = _tmp25_->y;
	b = _tmp24_ - _tmp26_;
	_tmp27_ = a;
	_tmp28_ = a;
	_tmp29_ = b;
	_tmp30_ = b;
	_tmp31_ = sqrt ((_tmp27_ * _tmp28_) + (_tmp29_ * _tmp30_));
	_tmp32_ = b1;
	_tmp33_ = _tmp32_->radius;
	_tmp34_ = b2;
	_tmp35_ = _tmp34_->radius;
	_result_ = (_tmp31_ - _tmp33_) < _tmp35_;
	result = _result_;
	_dark_matter_unref0 (b2);
	_dark_matter_unref0 (b1);
	_dark_matter_unref0 (p2);
	_dark_matter_unref0 (p1);
	return result;
}


BoscoECSGroup* collision_handler_get_groupEntitiesA (CollisionHandler* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return COLLISION_HANDLER_GET_INTERFACE (self)->get_groupEntitiesA (self);
}


void collision_handler_set_groupEntitiesA (CollisionHandler* self, BoscoECSGroup* value) {
	g_return_if_fail (self != NULL);
	COLLISION_HANDLER_GET_INTERFACE (self)->set_groupEntitiesA (self, value);
}


BoscoECSGroup* collision_handler_get_groupEntitiesB (CollisionHandler* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return COLLISION_HANDLER_GET_INTERFACE (self)->get_groupEntitiesB (self);
}


void collision_handler_set_groupEntitiesB (CollisionHandler* self, BoscoECSGroup* value) {
	g_return_if_fail (self != NULL);
	COLLISION_HANDLER_GET_INTERFACE (self)->set_groupEntitiesB (self, value);
}


static void collision_handler_base_init (CollisionHandlerIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType collision_handler_get_type (void) {
	static volatile gsize collision_handler_type_id__volatile = 0;
	if (g_once_init_enter (&collision_handler_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CollisionHandlerIface), (GBaseInitFunc) collision_handler_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType collision_handler_type_id;
		collision_handler_type_id = g_type_register_static (G_TYPE_INTERFACE, "CollisionHandler", &g_define_type_info, 0);
		g_once_init_leave (&collision_handler_type_id__volatile, collision_handler_type_id);
	}
	return collision_handler_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



