/* DestroySystem.c generated by valac 0.34.4, the Vala compiler
 * generated from DestroySystem.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_events.h>
#include <float.h>
#include <math.h>
#include <SDL2/SDL_video.h>
#include <SDL2/SDL_render.h>


#define TYPE_DARK_MATTER (dark_matter_get_type ())
#define DARK_MATTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DARK_MATTER, DarkMatter))
#define DARK_MATTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DARK_MATTER, DarkMatterClass))
#define IS_DARK_MATTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DARK_MATTER))
#define IS_DARK_MATTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DARK_MATTER))
#define DARK_MATTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DARK_MATTER, DarkMatterClass))

typedef struct _DarkMatter DarkMatter;
typedef struct _DarkMatterClass DarkMatterClass;
typedef struct _DarkMatterPrivate DarkMatterPrivate;

#define BOSCO_ECS_TYPE_ISYSTEM (bosco_ecs_isystem_get_type ())
#define BOSCO_ECS_ISYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ISYSTEM, BoscoECSISystem))
#define BOSCO_ECS_IS_ISYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ISYSTEM))
#define BOSCO_ECS_ISYSTEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_ISYSTEM, BoscoECSISystemIface))

typedef struct _BoscoECSISystem BoscoECSISystem;
typedef struct _BoscoECSISystemIface BoscoECSISystemIface;

#define BOSCO_ECS_TYPE_ISET_WORLD (bosco_ecs_iset_world_get_type ())
#define BOSCO_ECS_ISET_WORLD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ISET_WORLD, BoscoECSISetWorld))
#define BOSCO_ECS_IS_ISET_WORLD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ISET_WORLD))
#define BOSCO_ECS_ISET_WORLD_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_ISET_WORLD, BoscoECSISetWorldIface))

typedef struct _BoscoECSISetWorld BoscoECSISetWorld;
typedef struct _BoscoECSISetWorldIface BoscoECSISetWorldIface;

#define BOSCO_ECS_TYPE_WORLD_BASE (bosco_ecs_world_base_get_type ())
#define BOSCO_ECS_WORLD_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_WORLD_BASE, BoscoECSWorldBase))
#define BOSCO_ECS_WORLD_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_WORLD_BASE, BoscoECSWorldBaseClass))
#define BOSCO_ECS_IS_WORLD_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_WORLD_BASE))
#define BOSCO_ECS_IS_WORLD_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_WORLD_BASE))
#define BOSCO_ECS_WORLD_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_WORLD_BASE, BoscoECSWorldBaseClass))

typedef struct _BoscoECSWorldBase BoscoECSWorldBase;
typedef struct _BoscoECSWorldBaseClass BoscoECSWorldBaseClass;

#define BOSCO_ECS_TYPE_WORLD (bosco_ecs_world_get_type ())
#define BOSCO_ECS_WORLD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_WORLD, BoscoECSWorld))
#define BOSCO_ECS_WORLD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_WORLD, BoscoECSWorldClass))
#define BOSCO_ECS_IS_WORLD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_WORLD))
#define BOSCO_ECS_IS_WORLD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_WORLD))
#define BOSCO_ECS_WORLD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_WORLD, BoscoECSWorldClass))

typedef struct _BoscoECSWorld BoscoECSWorld;
typedef struct _BoscoECSWorldClass BoscoECSWorldClass;

#define BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM (bosco_ecs_iinitialize_system_get_type ())
#define BOSCO_ECS_IINITIALIZE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM, BoscoECSIInitializeSystem))
#define BOSCO_ECS_IS_IINITIALIZE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM))
#define BOSCO_ECS_IINITIALIZE_SYSTEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM, BoscoECSIInitializeSystemIface))

typedef struct _BoscoECSIInitializeSystem BoscoECSIInitializeSystem;
typedef struct _BoscoECSIInitializeSystemIface BoscoECSIInitializeSystemIface;

#define BOSCO_ECS_TYPE_IEXECUTE_SYSTEM (bosco_ecs_iexecute_system_get_type ())
#define BOSCO_ECS_IEXECUTE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_IEXECUTE_SYSTEM, BoscoECSIExecuteSystem))
#define BOSCO_ECS_IS_IEXECUTE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_IEXECUTE_SYSTEM))
#define BOSCO_ECS_IEXECUTE_SYSTEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_IEXECUTE_SYSTEM, BoscoECSIExecuteSystemIface))

typedef struct _BoscoECSIExecuteSystem BoscoECSIExecuteSystem;
typedef struct _BoscoECSIExecuteSystemIface BoscoECSIExecuteSystemIface;

#define TYPE_DESTROY_SYSTEM (destroy_system_get_type ())
#define DESTROY_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DESTROY_SYSTEM, DestroySystem))
#define DESTROY_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DESTROY_SYSTEM, DestroySystemClass))
#define IS_DESTROY_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DESTROY_SYSTEM))
#define IS_DESTROY_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DESTROY_SYSTEM))
#define DESTROY_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DESTROY_SYSTEM, DestroySystemClass))

typedef struct _DestroySystem DestroySystem;
typedef struct _DestroySystemClass DestroySystemClass;
typedef struct _DestroySystemPrivate DestroySystemPrivate;

#define BOSCO_ECS_TYPE_GROUP (bosco_ecs_group_get_type ())
#define BOSCO_ECS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_GROUP, BoscoECSGroup))
#define BOSCO_ECS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_GROUP, BoscoECSGroupClass))
#define BOSCO_ECS_IS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_GROUP))
#define BOSCO_ECS_IS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_GROUP))
#define BOSCO_ECS_GROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_GROUP, BoscoECSGroupClass))

typedef struct _BoscoECSGroup BoscoECSGroup;
typedef struct _BoscoECSGroupClass BoscoECSGroupClass;

#define BOSCO_TYPE_ABSTRACT_GAME (bosco_abstract_game_get_type ())
#define BOSCO_ABSTRACT_GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_TYPE_ABSTRACT_GAME, BoscoAbstractGame))
#define BOSCO_ABSTRACT_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_TYPE_ABSTRACT_GAME, BoscoAbstractGameClass))
#define BOSCO_IS_ABSTRACT_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_TYPE_ABSTRACT_GAME))
#define BOSCO_IS_ABSTRACT_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_TYPE_ABSTRACT_GAME))
#define BOSCO_ABSTRACT_GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_TYPE_ABSTRACT_GAME, BoscoAbstractGameClass))

typedef struct _BoscoAbstractGame BoscoAbstractGame;
typedef struct _BoscoAbstractGameClass BoscoAbstractGameClass;

#define TYPE_GAME (game_get_type ())
#define GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAME, Game))
#define GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAME, GameClass))
#define IS_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAME))
#define IS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAME))
#define GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAME, GameClass))

typedef struct _Game Game;
typedef struct _GameClass GameClass;

#define BOSCO_TYPE_SPRITE (bosco_sprite_get_type ())
#define BOSCO_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_TYPE_SPRITE, BoscoSprite))
#define BOSCO_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_TYPE_SPRITE, BoscoSpriteClass))
#define BOSCO_IS_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_TYPE_SPRITE))
#define BOSCO_IS_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_TYPE_SPRITE))
#define BOSCO_SPRITE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_TYPE_SPRITE, BoscoSpriteClass))

typedef struct _BoscoSprite BoscoSprite;
typedef struct _BoscoSpriteClass BoscoSpriteClass;
#define _dark_matter_unref0(var) ((var == NULL) ? NULL : (var = (dark_matter_unref (var), NULL)))
#define _g_ptr_array_unref0(var) ((var == NULL) ? NULL : (var = (g_ptr_array_unref (var), NULL)))

#define BOSCO_ECS_TYPE_IMATCHER (bosco_ecs_imatcher_get_type ())
#define BOSCO_ECS_IMATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_IMATCHER, BoscoECSIMatcher))
#define BOSCO_ECS_IS_IMATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_IMATCHER))
#define BOSCO_ECS_IMATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_IMATCHER, BoscoECSIMatcherIface))

typedef struct _BoscoECSIMatcher BoscoECSIMatcher;
typedef struct _BoscoECSIMatcherIface BoscoECSIMatcherIface;

#define BOSCO_ECS_TYPE_ENTITY_BASE (bosco_ecs_entity_base_get_type ())
#define BOSCO_ECS_ENTITY_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ENTITY_BASE, BoscoECSEntityBase))
#define BOSCO_ECS_ENTITY_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_ENTITY_BASE, BoscoECSEntityBaseClass))
#define BOSCO_ECS_IS_ENTITY_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ENTITY_BASE))
#define BOSCO_ECS_IS_ENTITY_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_ENTITY_BASE))
#define BOSCO_ECS_ENTITY_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_ENTITY_BASE, BoscoECSEntityBaseClass))

typedef struct _BoscoECSEntityBase BoscoECSEntityBase;
typedef struct _BoscoECSEntityBaseClass BoscoECSEntityBaseClass;

#define BOSCO_ECS_TYPE_ENTITY (bosco_ecs_entity_get_type ())
#define BOSCO_ECS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ENTITY, BoscoECSEntity))
#define BOSCO_ECS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_ENTITY, BoscoECSEntityClass))
#define BOSCO_ECS_IS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ENTITY))
#define BOSCO_ECS_IS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_ENTITY))
#define BOSCO_ECS_ENTITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_ENTITY, BoscoECSEntityClass))

typedef struct _BoscoECSEntity BoscoECSEntity;
typedef struct _BoscoECSEntityClass BoscoECSEntityClass;

#define TYPE_COMPONENT (component_get_type ())
typedef struct _BoscoAbstractGamePrivate BoscoAbstractGamePrivate;

#define TYPE_RESOURCE_COMPONENT (resource_component_get_type ())
#define RESOURCE_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RESOURCE_COMPONENT, ResourceComponent))
#define RESOURCE_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_RESOURCE_COMPONENT, ResourceComponentClass))
#define IS_RESOURCE_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RESOURCE_COMPONENT))
#define IS_RESOURCE_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_RESOURCE_COMPONENT))
#define RESOURCE_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RESOURCE_COMPONENT, ResourceComponentClass))

typedef struct _ResourceComponent ResourceComponent;
typedef struct _ResourceComponentClass ResourceComponentClass;
typedef struct _BoscoSpritePrivate BoscoSpritePrivate;

#define BOSCO_TYPE_SCALE (bosco_scale_get_type ())
typedef struct _BoscoScale BoscoScale;

#define BOSCO_TYPE_COLOR (bosco_color_get_type ())
typedef struct _BoscoColor BoscoColor;

#define BOSCO_ECS_TYPE_ICOMPONENT (bosco_ecs_icomponent_get_type ())
#define BOSCO_ECS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ICOMPONENT, BoscoECSIComponent))
#define BOSCO_ECS_IS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ICOMPONENT))
#define BOSCO_ECS_ICOMPONENT_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_ICOMPONENT, BoscoECSIComponentIface))

typedef struct _BoscoECSIComponent BoscoECSIComponent;
typedef struct _BoscoECSIComponentIface BoscoECSIComponentIface;
typedef struct _ResourceComponentPrivate ResourceComponentPrivate;

struct _DarkMatter {
	GTypeInstance parent_instance;
	volatile int ref_count;
	DarkMatterPrivate * priv;
};

struct _DarkMatterClass {
	GTypeClass parent_class;
	void (*finalize) (DarkMatter *self);
};

struct _BoscoECSISystemIface {
	GTypeInterface parent_iface;
};

struct _BoscoECSISetWorldIface {
	GTypeInterface parent_iface;
	void (*setWorld) (BoscoECSISetWorld* self, BoscoECSWorld* world);
};

struct _BoscoECSIInitializeSystemIface {
	GTypeInterface parent_iface;
	void (*initialize) (BoscoECSIInitializeSystem* self);
};

struct _BoscoECSIExecuteSystemIface {
	GTypeInterface parent_iface;
	void (*execute) (BoscoECSIExecuteSystem* self);
};

struct _DestroySystem {
	DarkMatter parent_instance;
	DestroySystemPrivate * priv;
};

struct _DestroySystemClass {
	DarkMatterClass parent_class;
};

struct _DestroySystemPrivate {
	BoscoECSWorld* _world;
	BoscoECSGroup* _group;
	Game* _game;
	GPtrArray* _sprites;
};

struct _BoscoECSIMatcherIface {
	GTypeInterface parent_iface;
	gboolean (*matches) (BoscoECSIMatcher* self, BoscoECSEntity* entity);
	gchar* (*toString) (BoscoECSIMatcher* self);
	const gchar* (*get_id) (BoscoECSIMatcher* self);
	gint* (*get_indices) (BoscoECSIMatcher* self, int* result_length1);
};

typedef enum  {
	COMPONENT_Bounds,
	COMPONENT_Bullet,
	COMPONENT_ColorTween,
	COMPONENT_Destroy,
	COMPONENT_Enemy,
	COMPONENT_Expires,
	COMPONENT_Firing,
	COMPONENT_Health,
	COMPONENT_Layer,
	COMPONENT_Life,
	COMPONENT_Mine,
	COMPONENT_Mouse,
	COMPONENT_Player,
	COMPONENT_Position,
	COMPONENT_Resource,
	COMPONENT_ScaleTween,
	COMPONENT_Scale,
	COMPONENT_Score,
	COMPONENT_SoundEffect,
	COMPONENT_Tint,
	COMPONENT_Velocity,
	COMPONENT_TotalComponents
} Component;

struct _BoscoAbstractGame {
	DarkMatter parent_instance;
	BoscoAbstractGamePrivate * priv;
	gchar* name;
	gint width;
	gint height;
	gboolean running;
	SDL_Window* window;
	SDL_Renderer* renderer;
	GPtrArray* sprites;
	guint8* keys;
	gint keys_length1;
	gboolean showFps;
};

struct _BoscoAbstractGameClass {
	DarkMatterClass parent_class;
	void (*Events) (BoscoAbstractGame* self, SDL_Event e);
	void (*Update) (BoscoAbstractGame* self, gdouble delta);
	void (*Draw) (BoscoAbstractGame* self, gdouble delta);
	void (*Dispose) (BoscoAbstractGame* self);
	gboolean (*Initialize) (BoscoAbstractGame* self);
};

struct _BoscoScale {
	gdouble x;
	gdouble y;
};

struct _BoscoColor {
	guint8 r;
	guint8 g;
	guint8 b;
	guint8 a;
};

struct _BoscoSprite {
	DarkMatter parent_instance;
	BoscoSpritePrivate * priv;
	SDL_Texture* texture;
	gint width;
	gint height;
	gint x;
	gint y;
	BoscoScale scale;
	BoscoColor color;
	gboolean centered;
	gint layer;
	gint id;
};

struct _BoscoSpriteClass {
	DarkMatterClass parent_class;
};

struct _BoscoECSIComponentIface {
	GTypeInterface parent_iface;
};

struct _ResourceComponent {
	DarkMatter parent_instance;
	ResourceComponentPrivate * priv;
	gchar* path;
	BoscoSprite* sprite;
	gboolean bgd;
};

struct _ResourceComponentClass {
	DarkMatterClass parent_class;
};

typedef enum  {
	BOSCO_ECS_ECS_EXCEPTION_EntityIsNotEnabled,
	BOSCO_ECS_ECS_EXCEPTION_EntityAlreadyHasComponent,
	BOSCO_ECS_ECS_EXCEPTION_EntityDoesNotHaveComponent,
	BOSCO_ECS_ECS_EXCEPTION_EntityIsAlreadyReleased,
	BOSCO_ECS_ECS_EXCEPTION_SingleEntity,
	BOSCO_ECS_ECS_EXCEPTION_Matcher,
	BOSCO_ECS_ECS_EXCEPTION_WorldDoesNotContainEntity
} BoscoECSEcsException;
#define BOSCO_ECS_ECS_EXCEPTION bosco_ecs_ecs_exception_quark ()

static gpointer destroy_system_parent_class = NULL;
static BoscoECSISystemIface* destroy_system_bosco_ecs_isystem_parent_iface = NULL;
static BoscoECSISetWorldIface* destroy_system_bosco_ecs_iset_world_parent_iface = NULL;
static BoscoECSIInitializeSystemIface* destroy_system_bosco_ecs_iinitialize_system_parent_iface = NULL;
static BoscoECSIExecuteSystemIface* destroy_system_bosco_ecs_iexecute_system_parent_iface = NULL;

gpointer dark_matter_ref (gpointer instance);
void dark_matter_unref (gpointer instance);
GParamSpec* param_spec_dark_matter (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_dark_matter (GValue* value, gpointer v_object);
void value_take_dark_matter (GValue* value, gpointer v_object);
gpointer value_get_dark_matter (const GValue* value);
GType dark_matter_get_type (void) G_GNUC_CONST;
GType bosco_ecs_isystem_get_type (void) G_GNUC_CONST;
GType bosco_ecs_world_base_get_type (void) G_GNUC_CONST;
GType bosco_ecs_world_get_type (void) G_GNUC_CONST;
GType bosco_ecs_iset_world_get_type (void) G_GNUC_CONST;
GType bosco_ecs_iinitialize_system_get_type (void) G_GNUC_CONST;
GType bosco_ecs_iexecute_system_get_type (void) G_GNUC_CONST;
GType destroy_system_get_type (void) G_GNUC_CONST;
GType bosco_ecs_group_get_type (void) G_GNUC_CONST;
GType bosco_abstract_game_get_type (void) G_GNUC_CONST;
GType game_get_type (void) G_GNUC_CONST;
GType bosco_sprite_get_type (void) G_GNUC_CONST;
#define DESTROY_SYSTEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_DESTROY_SYSTEM, DestroySystemPrivate))
enum  {
	DESTROY_SYSTEM_DUMMY_PROPERTY
};
DestroySystem* destroy_system_new (Game* game);
DestroySystem* destroy_system_construct (GType object_type, Game* game);
DarkMatter* dark_matter_new (void);
DarkMatter* dark_matter_construct (GType object_type);
static void destroy_system_real_setWorld (BoscoECSISetWorld* base, BoscoECSWorld* world);
static void destroy_system_real_initialize (BoscoECSIInitializeSystem* base);
GType bosco_ecs_entity_base_get_type (void) G_GNUC_CONST;
GType bosco_ecs_entity_get_type (void) G_GNUC_CONST;
GType bosco_ecs_imatcher_get_type (void) G_GNUC_CONST;
BoscoECSGroup* bosco_ecs_world_base_getGroup (BoscoECSWorldBase* self, BoscoECSIMatcher* matcher);
BoscoECSIMatcher* bosco_ecs_matcher_AllOf (gint* args, int args_length1);
GType component_get_type (void) G_GNUC_CONST;
static void destroy_system_real_execute (BoscoECSIExecuteSystem* base);
GType resource_component_get_type (void) G_GNUC_CONST;
BoscoECSEntity** bosco_ecs_group_getEntities (BoscoECSGroup* self, int* result_length1);
gboolean bosco_ecs_entity_get_hasResource (BoscoECSEntity* self);
ResourceComponent* bosco_ecs_entity_get_resource (BoscoECSEntity* self);
GType bosco_scale_get_type (void) G_GNUC_CONST;
BoscoScale* bosco_scale_dup (const BoscoScale* self);
void bosco_scale_free (BoscoScale* self);
GType bosco_color_get_type (void) G_GNUC_CONST;
BoscoColor* bosco_color_dup (const BoscoColor* self);
void bosco_color_free (BoscoColor* self);
GType bosco_ecs_icomponent_get_type (void) G_GNUC_CONST;
GQuark bosco_ecs_ecs_exception_quark (void);
void bosco_ecs_world_base_destroyEntity (BoscoECSWorldBase* self, BoscoECSEntity* entity, GError** error);
static void destroy_system_finalize (DarkMatter* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gpointer _dark_matter_ref0 (gpointer self) {
	return self ? dark_matter_ref (self) : NULL;
}


DestroySystem* destroy_system_construct (GType object_type, Game* game) {
	DestroySystem* self = NULL;
	Game* _tmp0_ = NULL;
	Game* _tmp1_ = NULL;
	g_return_val_if_fail (game != NULL, NULL);
	self = (DestroySystem*) dark_matter_construct (object_type);
	_tmp0_ = game;
	_tmp1_ = _dark_matter_ref0 (_tmp0_);
	_dark_matter_unref0 (self->priv->_game);
	self->priv->_game = _tmp1_;
	return self;
}


DestroySystem* destroy_system_new (Game* game) {
	return destroy_system_construct (TYPE_DESTROY_SYSTEM, game);
}


static void destroy_system_real_setWorld (BoscoECSISetWorld* base, BoscoECSWorld* world) {
	DestroySystem * self;
	BoscoECSWorld* _tmp0_ = NULL;
	BoscoECSWorld* _tmp1_ = NULL;
	self = (DestroySystem*) base;
	g_return_if_fail (world != NULL);
	_tmp0_ = world;
	_tmp1_ = _dark_matter_ref0 (_tmp0_);
	_dark_matter_unref0 (self->priv->_world);
	self->priv->_world = _tmp1_;
}


static gpointer _g_ptr_array_ref0 (gpointer self) {
	return self ? g_ptr_array_ref (self) : NULL;
}


static void destroy_system_real_initialize (BoscoECSIInitializeSystem* base) {
	DestroySystem * self;
	BoscoECSWorld* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint* _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	BoscoECSIMatcher* _tmp3_ = NULL;
	BoscoECSIMatcher* _tmp4_ = NULL;
	BoscoECSGroup* _tmp5_ = NULL;
	Game* _tmp6_ = NULL;
	GPtrArray* _tmp7_ = NULL;
	GPtrArray* _tmp8_ = NULL;
	self = (DestroySystem*) base;
	_tmp0_ = self->priv->_world;
	_tmp1_ = g_new0 (gint, 1);
	_tmp1_[0] = (gint) COMPONENT_Destroy;
	_tmp2_ = _tmp1_;
	_tmp2__length1 = 1;
	_tmp3_ = bosco_ecs_matcher_AllOf (_tmp2_, 1);
	_tmp4_ = _tmp3_;
	_tmp5_ = bosco_ecs_world_base_getGroup ((BoscoECSWorldBase*) _tmp0_, _tmp4_);
	_dark_matter_unref0 (self->priv->_group);
	self->priv->_group = _tmp5_;
	_dark_matter_unref0 (_tmp4_);
	_tmp2_ = (g_free (_tmp2_), NULL);
	_tmp6_ = self->priv->_game;
	_tmp7_ = ((BoscoAbstractGame*) _tmp6_)->sprites;
	_tmp8_ = _g_ptr_array_ref0 (_tmp7_);
	_g_ptr_array_unref0 (self->priv->_sprites);
	self->priv->_sprites = _tmp8_;
}


static gint g_ptr_array_get_length (GPtrArray* self) {
	gint result;
	guint _tmp0_ = 0U;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->len;
	result = (gint) _tmp0_;
	return result;
}


static void g_ptr_array_set_length (GPtrArray* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	g_ptr_array_set_size (self, _tmp0_);
}


static void destroy_system_real_execute (BoscoECSIExecuteSystem* base) {
	DestroySystem * self;
	ResourceComponent* res = NULL;
	BoscoECSGroup* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	BoscoECSEntity** _tmp2_ = NULL;
	GError * _inner_error_ = NULL;
	self = (DestroySystem*) base;
	_tmp0_ = self->priv->_group;
	_tmp2_ = bosco_ecs_group_getEntities (_tmp0_, &_tmp1_);
	{
		BoscoECSEntity** entity_collection = NULL;
		gint entity_collection_length1 = 0;
		gint _entity_collection_size_ = 0;
		gint entity_it = 0;
		entity_collection = _tmp2_;
		entity_collection_length1 = _tmp1_;
		for (entity_it = 0; entity_it < _tmp1_; entity_it = entity_it + 1) {
			BoscoECSEntity* _tmp3_ = NULL;
			BoscoECSEntity* entity = NULL;
			_tmp3_ = _dark_matter_ref0 (entity_collection[entity_it]);
			entity = _tmp3_;
			{
				BoscoECSEntity* _tmp4_ = NULL;
				gboolean _tmp5_ = FALSE;
				gboolean _tmp6_ = FALSE;
				BoscoECSWorld* _tmp25_ = NULL;
				BoscoECSEntity* _tmp26_ = NULL;
				_tmp4_ = entity;
				_tmp5_ = bosco_ecs_entity_get_hasResource (_tmp4_);
				_tmp6_ = _tmp5_;
				if (_tmp6_) {
					BoscoECSEntity* _tmp7_ = NULL;
					ResourceComponent* _tmp8_ = NULL;
					ResourceComponent* _tmp9_ = NULL;
					ResourceComponent* _tmp10_ = NULL;
					_tmp7_ = entity;
					_tmp8_ = bosco_ecs_entity_get_resource (_tmp7_);
					_tmp9_ = _tmp8_;
					_tmp10_ = _dark_matter_ref0 (_tmp9_);
					_dark_matter_unref0 (res);
					res = _tmp10_;
					{
						gint i = 0;
						i = 0;
						{
							gboolean _tmp11_ = FALSE;
							_tmp11_ = TRUE;
							while (TRUE) {
								GPtrArray* _tmp13_ = NULL;
								gint _tmp14_ = 0;
								gint _tmp15_ = 0;
								GPtrArray* _tmp16_ = NULL;
								gint _tmp17_ = 0;
								gconstpointer _tmp18_ = NULL;
								gint _tmp19_ = 0;
								ResourceComponent* _tmp20_ = NULL;
								BoscoSprite* _tmp21_ = NULL;
								gint _tmp22_ = 0;
								if (!_tmp11_) {
									gint _tmp12_ = 0;
									_tmp12_ = i;
									i = _tmp12_ + 1;
								}
								_tmp11_ = FALSE;
								_tmp13_ = self->priv->_sprites;
								_tmp14_ = g_ptr_array_get_length (_tmp13_);
								_tmp15_ = _tmp14_;
								if (!(i <= (_tmp15_ - 1))) {
									break;
								}
								_tmp16_ = self->priv->_sprites;
								_tmp17_ = i;
								_tmp18_ = g_ptr_array_index (_tmp16_, (guint) _tmp17_);
								_tmp19_ = ((BoscoSprite*) _tmp18_)->id;
								_tmp20_ = res;
								_tmp21_ = _tmp20_->sprite;
								_tmp22_ = _tmp21_->id;
								if (_tmp19_ == _tmp22_) {
									GPtrArray* _tmp23_ = NULL;
									gint _tmp24_ = 0;
									_tmp23_ = self->priv->_sprites;
									_tmp24_ = i;
									g_ptr_array_remove_index (_tmp23_, (guint) _tmp24_);
									break;
								}
							}
						}
					}
				}
				_tmp25_ = self->priv->_world;
				_tmp26_ = entity;
				bosco_ecs_world_base_destroyEntity ((BoscoECSWorldBase*) _tmp25_, _tmp26_, &_inner_error_);
				if (G_UNLIKELY (_inner_error_ != NULL)) {
					_dark_matter_unref0 (entity);
					entity_collection = (_vala_array_free (entity_collection, entity_collection_length1, (GDestroyNotify) dark_matter_unref), NULL);
					_dark_matter_unref0 (res);
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return;
				}
				_dark_matter_unref0 (entity);
			}
		}
		entity_collection = (_vala_array_free (entity_collection, entity_collection_length1, (GDestroyNotify) dark_matter_unref), NULL);
	}
	_dark_matter_unref0 (res);
}


static void destroy_system_class_init (DestroySystemClass * klass) {
	destroy_system_parent_class = g_type_class_peek_parent (klass);
	((DarkMatterClass *) klass)->finalize = destroy_system_finalize;
	g_type_class_add_private (klass, sizeof (DestroySystemPrivate));
}


static void destroy_system_bosco_ecs_isystem_interface_init (BoscoECSISystemIface * iface) {
	destroy_system_bosco_ecs_isystem_parent_iface = g_type_interface_peek_parent (iface);
}


static void destroy_system_bosco_ecs_iset_world_interface_init (BoscoECSISetWorldIface * iface) {
	destroy_system_bosco_ecs_iset_world_parent_iface = g_type_interface_peek_parent (iface);
	iface->setWorld = (void (*)(BoscoECSISetWorld*, BoscoECSWorld*)) destroy_system_real_setWorld;
}


static void destroy_system_bosco_ecs_iinitialize_system_interface_init (BoscoECSIInitializeSystemIface * iface) {
	destroy_system_bosco_ecs_iinitialize_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->initialize = (void (*)(BoscoECSIInitializeSystem*)) destroy_system_real_initialize;
}


static void destroy_system_bosco_ecs_iexecute_system_interface_init (BoscoECSIExecuteSystemIface * iface) {
	destroy_system_bosco_ecs_iexecute_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->execute = (void (*)(BoscoECSIExecuteSystem*)) destroy_system_real_execute;
}


static void destroy_system_instance_init (DestroySystem * self) {
	self->priv = DESTROY_SYSTEM_GET_PRIVATE (self);
}


static void destroy_system_finalize (DarkMatter* obj) {
	DestroySystem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_DESTROY_SYSTEM, DestroySystem);
	_dark_matter_unref0 (self->priv->_world);
	_dark_matter_unref0 (self->priv->_group);
	_dark_matter_unref0 (self->priv->_game);
	_g_ptr_array_unref0 (self->priv->_sprites);
	DARK_MATTER_CLASS (destroy_system_parent_class)->finalize (obj);
}


GType destroy_system_get_type (void) {
	static volatile gsize destroy_system_type_id__volatile = 0;
	if (g_once_init_enter (&destroy_system_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DestroySystemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) destroy_system_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DestroySystem), 0, (GInstanceInitFunc) destroy_system_instance_init, NULL };
		static const GInterfaceInfo bosco_ecs_isystem_info = { (GInterfaceInitFunc) destroy_system_bosco_ecs_isystem_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo bosco_ecs_iset_world_info = { (GInterfaceInitFunc) destroy_system_bosco_ecs_iset_world_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo bosco_ecs_iinitialize_system_info = { (GInterfaceInitFunc) destroy_system_bosco_ecs_iinitialize_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo bosco_ecs_iexecute_system_info = { (GInterfaceInitFunc) destroy_system_bosco_ecs_iexecute_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType destroy_system_type_id;
		destroy_system_type_id = g_type_register_static (TYPE_DARK_MATTER, "DestroySystem", &g_define_type_info, 0);
		g_type_add_interface_static (destroy_system_type_id, BOSCO_ECS_TYPE_ISYSTEM, &bosco_ecs_isystem_info);
		g_type_add_interface_static (destroy_system_type_id, BOSCO_ECS_TYPE_ISET_WORLD, &bosco_ecs_iset_world_info);
		g_type_add_interface_static (destroy_system_type_id, BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM, &bosco_ecs_iinitialize_system_info);
		g_type_add_interface_static (destroy_system_type_id, BOSCO_ECS_TYPE_IEXECUTE_SYSTEM, &bosco_ecs_iexecute_system_info);
		g_once_init_leave (&destroy_system_type_id__volatile, destroy_system_type_id);
	}
	return destroy_system_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



