/* MovementSystem.c generated by valac 0.34.4, the Vala compiler
 * generated from MovementSystem.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define TYPE_DARK_MATTER (dark_matter_get_type ())
#define DARK_MATTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DARK_MATTER, DarkMatter))
#define DARK_MATTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DARK_MATTER, DarkMatterClass))
#define IS_DARK_MATTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DARK_MATTER))
#define IS_DARK_MATTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DARK_MATTER))
#define DARK_MATTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DARK_MATTER, DarkMatterClass))

typedef struct _DarkMatter DarkMatter;
typedef struct _DarkMatterClass DarkMatterClass;
typedef struct _DarkMatterPrivate DarkMatterPrivate;

#define BOSCO_ECS_TYPE_ISYSTEM (bosco_ecs_isystem_get_type ())
#define BOSCO_ECS_ISYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ISYSTEM, BoscoECSISystem))
#define BOSCO_ECS_IS_ISYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ISYSTEM))
#define BOSCO_ECS_ISYSTEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_ISYSTEM, BoscoECSISystemIface))

typedef struct _BoscoECSISystem BoscoECSISystem;
typedef struct _BoscoECSISystemIface BoscoECSISystemIface;

#define BOSCO_ECS_TYPE_ISET_WORLD (bosco_ecs_iset_world_get_type ())
#define BOSCO_ECS_ISET_WORLD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ISET_WORLD, BoscoECSISetWorld))
#define BOSCO_ECS_IS_ISET_WORLD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ISET_WORLD))
#define BOSCO_ECS_ISET_WORLD_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_ISET_WORLD, BoscoECSISetWorldIface))

typedef struct _BoscoECSISetWorld BoscoECSISetWorld;
typedef struct _BoscoECSISetWorldIface BoscoECSISetWorldIface;

#define BOSCO_ECS_TYPE_WORLD_BASE (bosco_ecs_world_base_get_type ())
#define BOSCO_ECS_WORLD_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_WORLD_BASE, BoscoECSWorldBase))
#define BOSCO_ECS_WORLD_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_WORLD_BASE, BoscoECSWorldBaseClass))
#define BOSCO_ECS_IS_WORLD_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_WORLD_BASE))
#define BOSCO_ECS_IS_WORLD_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_WORLD_BASE))
#define BOSCO_ECS_WORLD_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_WORLD_BASE, BoscoECSWorldBaseClass))

typedef struct _BoscoECSWorldBase BoscoECSWorldBase;
typedef struct _BoscoECSWorldBaseClass BoscoECSWorldBaseClass;

#define BOSCO_ECS_TYPE_WORLD (bosco_ecs_world_get_type ())
#define BOSCO_ECS_WORLD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_WORLD, BoscoECSWorld))
#define BOSCO_ECS_WORLD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_WORLD, BoscoECSWorldClass))
#define BOSCO_ECS_IS_WORLD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_WORLD))
#define BOSCO_ECS_IS_WORLD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_WORLD))
#define BOSCO_ECS_WORLD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_WORLD, BoscoECSWorldClass))

typedef struct _BoscoECSWorld BoscoECSWorld;
typedef struct _BoscoECSWorldClass BoscoECSWorldClass;

#define BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM (bosco_ecs_iinitialize_system_get_type ())
#define BOSCO_ECS_IINITIALIZE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM, BoscoECSIInitializeSystem))
#define BOSCO_ECS_IS_IINITIALIZE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM))
#define BOSCO_ECS_IINITIALIZE_SYSTEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM, BoscoECSIInitializeSystemIface))

typedef struct _BoscoECSIInitializeSystem BoscoECSIInitializeSystem;
typedef struct _BoscoECSIInitializeSystemIface BoscoECSIInitializeSystemIface;

#define BOSCO_ECS_TYPE_IEXECUTE_SYSTEM (bosco_ecs_iexecute_system_get_type ())
#define BOSCO_ECS_IEXECUTE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_IEXECUTE_SYSTEM, BoscoECSIExecuteSystem))
#define BOSCO_ECS_IS_IEXECUTE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_IEXECUTE_SYSTEM))
#define BOSCO_ECS_IEXECUTE_SYSTEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_IEXECUTE_SYSTEM, BoscoECSIExecuteSystemIface))

typedef struct _BoscoECSIExecuteSystem BoscoECSIExecuteSystem;
typedef struct _BoscoECSIExecuteSystemIface BoscoECSIExecuteSystemIface;

#define TYPE_MOVEMENT_SYSTEM (movement_system_get_type ())
#define MOVEMENT_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MOVEMENT_SYSTEM, MovementSystem))
#define MOVEMENT_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MOVEMENT_SYSTEM, MovementSystemClass))
#define IS_MOVEMENT_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MOVEMENT_SYSTEM))
#define IS_MOVEMENT_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MOVEMENT_SYSTEM))
#define MOVEMENT_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MOVEMENT_SYSTEM, MovementSystemClass))

typedef struct _MovementSystem MovementSystem;
typedef struct _MovementSystemClass MovementSystemClass;
typedef struct _MovementSystemPrivate MovementSystemPrivate;

#define BOSCO_ECS_TYPE_GROUP (bosco_ecs_group_get_type ())
#define BOSCO_ECS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_GROUP, BoscoECSGroup))
#define BOSCO_ECS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_GROUP, BoscoECSGroupClass))
#define BOSCO_ECS_IS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_GROUP))
#define BOSCO_ECS_IS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_GROUP))
#define BOSCO_ECS_GROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_GROUP, BoscoECSGroupClass))

typedef struct _BoscoECSGroup BoscoECSGroup;
typedef struct _BoscoECSGroupClass BoscoECSGroupClass;

#define BOSCO_TYPE_ABSTRACT_GAME (bosco_abstract_game_get_type ())
#define BOSCO_ABSTRACT_GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_TYPE_ABSTRACT_GAME, BoscoAbstractGame))
#define BOSCO_ABSTRACT_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_TYPE_ABSTRACT_GAME, BoscoAbstractGameClass))
#define BOSCO_IS_ABSTRACT_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_TYPE_ABSTRACT_GAME))
#define BOSCO_IS_ABSTRACT_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_TYPE_ABSTRACT_GAME))
#define BOSCO_ABSTRACT_GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_TYPE_ABSTRACT_GAME, BoscoAbstractGameClass))

typedef struct _BoscoAbstractGame BoscoAbstractGame;
typedef struct _BoscoAbstractGameClass BoscoAbstractGameClass;

#define TYPE_GAME (game_get_type ())
#define GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAME, Game))
#define GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAME, GameClass))
#define IS_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAME))
#define IS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAME))
#define GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAME, GameClass))

typedef struct _Game Game;
typedef struct _GameClass GameClass;
#define _dark_matter_unref0(var) ((var == NULL) ? NULL : (var = (dark_matter_unref (var), NULL)))

#define BOSCO_ECS_TYPE_IMATCHER (bosco_ecs_imatcher_get_type ())
#define BOSCO_ECS_IMATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_IMATCHER, BoscoECSIMatcher))
#define BOSCO_ECS_IS_IMATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_IMATCHER))
#define BOSCO_ECS_IMATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_IMATCHER, BoscoECSIMatcherIface))

typedef struct _BoscoECSIMatcher BoscoECSIMatcher;
typedef struct _BoscoECSIMatcherIface BoscoECSIMatcherIface;

#define BOSCO_ECS_TYPE_ENTITY_BASE (bosco_ecs_entity_base_get_type ())
#define BOSCO_ECS_ENTITY_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ENTITY_BASE, BoscoECSEntityBase))
#define BOSCO_ECS_ENTITY_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_ENTITY_BASE, BoscoECSEntityBaseClass))
#define BOSCO_ECS_IS_ENTITY_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ENTITY_BASE))
#define BOSCO_ECS_IS_ENTITY_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_ENTITY_BASE))
#define BOSCO_ECS_ENTITY_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_ENTITY_BASE, BoscoECSEntityBaseClass))

typedef struct _BoscoECSEntityBase BoscoECSEntityBase;
typedef struct _BoscoECSEntityBaseClass BoscoECSEntityBaseClass;

#define BOSCO_ECS_TYPE_ENTITY (bosco_ecs_entity_get_type ())
#define BOSCO_ECS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ENTITY, BoscoECSEntity))
#define BOSCO_ECS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_ENTITY, BoscoECSEntityClass))
#define BOSCO_ECS_IS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ENTITY))
#define BOSCO_ECS_IS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_ENTITY))
#define BOSCO_ECS_ENTITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_ENTITY, BoscoECSEntityClass))

typedef struct _BoscoECSEntity BoscoECSEntity;
typedef struct _BoscoECSEntityClass BoscoECSEntityClass;

#define TYPE_COMPONENT (component_get_type ())

#define TYPE_POSITION_COMPONENT (position_component_get_type ())
#define POSITION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_POSITION_COMPONENT, PositionComponent))
#define POSITION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_POSITION_COMPONENT, PositionComponentClass))
#define IS_POSITION_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_POSITION_COMPONENT))
#define IS_POSITION_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_POSITION_COMPONENT))
#define POSITION_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_POSITION_COMPONENT, PositionComponentClass))

typedef struct _PositionComponent PositionComponent;
typedef struct _PositionComponentClass PositionComponentClass;

#define TYPE_VELOCITY_COMPONENT (velocity_component_get_type ())
#define VELOCITY_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_VELOCITY_COMPONENT, VelocityComponent))
#define VELOCITY_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_VELOCITY_COMPONENT, VelocityComponentClass))
#define IS_VELOCITY_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_VELOCITY_COMPONENT))
#define IS_VELOCITY_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_VELOCITY_COMPONENT))
#define VELOCITY_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_VELOCITY_COMPONENT, VelocityComponentClass))

typedef struct _VelocityComponent VelocityComponent;
typedef struct _VelocityComponentClass VelocityComponentClass;

#define BOSCO_ECS_TYPE_ICOMPONENT (bosco_ecs_icomponent_get_type ())
#define BOSCO_ECS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ICOMPONENT, BoscoECSIComponent))
#define BOSCO_ECS_IS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ICOMPONENT))
#define BOSCO_ECS_ICOMPONENT_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_ICOMPONENT, BoscoECSIComponentIface))

typedef struct _BoscoECSIComponent BoscoECSIComponent;
typedef struct _BoscoECSIComponentIface BoscoECSIComponentIface;
typedef struct _PositionComponentPrivate PositionComponentPrivate;
typedef struct _VelocityComponentPrivate VelocityComponentPrivate;

struct _DarkMatter {
	GTypeInstance parent_instance;
	volatile int ref_count;
	DarkMatterPrivate * priv;
};

struct _DarkMatterClass {
	GTypeClass parent_class;
	void (*finalize) (DarkMatter *self);
};

struct _BoscoECSISystemIface {
	GTypeInterface parent_iface;
};

struct _BoscoECSISetWorldIface {
	GTypeInterface parent_iface;
	void (*setWorld) (BoscoECSISetWorld* self, BoscoECSWorld* world);
};

struct _BoscoECSIInitializeSystemIface {
	GTypeInterface parent_iface;
	void (*initialize) (BoscoECSIInitializeSystem* self);
};

struct _BoscoECSIExecuteSystemIface {
	GTypeInterface parent_iface;
	void (*execute) (BoscoECSIExecuteSystem* self);
};

struct _MovementSystem {
	DarkMatter parent_instance;
	MovementSystemPrivate * priv;
};

struct _MovementSystemClass {
	DarkMatterClass parent_class;
};

struct _MovementSystemPrivate {
	BoscoECSWorld* _world;
	BoscoECSGroup* _group;
	Game* _game;
};

struct _BoscoECSIMatcherIface {
	GTypeInterface parent_iface;
	gboolean (*matches) (BoscoECSIMatcher* self, BoscoECSEntity* entity);
	gchar* (*toString) (BoscoECSIMatcher* self);
	const gchar* (*get_id) (BoscoECSIMatcher* self);
	gint* (*get_indices) (BoscoECSIMatcher* self, int* result_length1);
};

typedef enum  {
	COMPONENT_Bounds,
	COMPONENT_Bullet,
	COMPONENT_ColorTween,
	COMPONENT_Destroy,
	COMPONENT_Enemy,
	COMPONENT_Expires,
	COMPONENT_Firing,
	COMPONENT_Health,
	COMPONENT_Layer,
	COMPONENT_Life,
	COMPONENT_Mine,
	COMPONENT_Mouse,
	COMPONENT_Player,
	COMPONENT_Position,
	COMPONENT_Resource,
	COMPONENT_ScaleTween,
	COMPONENT_Scale,
	COMPONENT_Score,
	COMPONENT_SoundEffect,
	COMPONENT_Tint,
	COMPONENT_Velocity,
	COMPONENT_TotalComponents
} Component;

struct _BoscoECSIComponentIface {
	GTypeInterface parent_iface;
};

struct _PositionComponent {
	DarkMatter parent_instance;
	PositionComponentPrivate * priv;
	gdouble x;
	gdouble y;
};

struct _PositionComponentClass {
	DarkMatterClass parent_class;
};

struct _VelocityComponent {
	DarkMatter parent_instance;
	VelocityComponentPrivate * priv;
	gdouble x;
	gdouble y;
};

struct _VelocityComponentClass {
	DarkMatterClass parent_class;
};


static gpointer movement_system_parent_class = NULL;
static BoscoECSISystemIface* movement_system_bosco_ecs_isystem_parent_iface = NULL;
static BoscoECSISetWorldIface* movement_system_bosco_ecs_iset_world_parent_iface = NULL;
static BoscoECSIInitializeSystemIface* movement_system_bosco_ecs_iinitialize_system_parent_iface = NULL;
static BoscoECSIExecuteSystemIface* movement_system_bosco_ecs_iexecute_system_parent_iface = NULL;

gpointer dark_matter_ref (gpointer instance);
void dark_matter_unref (gpointer instance);
GParamSpec* param_spec_dark_matter (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_dark_matter (GValue* value, gpointer v_object);
void value_take_dark_matter (GValue* value, gpointer v_object);
gpointer value_get_dark_matter (const GValue* value);
GType dark_matter_get_type (void) G_GNUC_CONST;
GType bosco_ecs_isystem_get_type (void) G_GNUC_CONST;
GType bosco_ecs_world_base_get_type (void) G_GNUC_CONST;
GType bosco_ecs_world_get_type (void) G_GNUC_CONST;
GType bosco_ecs_iset_world_get_type (void) G_GNUC_CONST;
GType bosco_ecs_iinitialize_system_get_type (void) G_GNUC_CONST;
GType bosco_ecs_iexecute_system_get_type (void) G_GNUC_CONST;
GType movement_system_get_type (void) G_GNUC_CONST;
GType bosco_ecs_group_get_type (void) G_GNUC_CONST;
GType bosco_abstract_game_get_type (void) G_GNUC_CONST;
GType game_get_type (void) G_GNUC_CONST;
#define MOVEMENT_SYSTEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_MOVEMENT_SYSTEM, MovementSystemPrivate))
enum  {
	MOVEMENT_SYSTEM_DUMMY_PROPERTY
};
MovementSystem* movement_system_new (Game* game);
MovementSystem* movement_system_construct (GType object_type, Game* game);
DarkMatter* dark_matter_new (void);
DarkMatter* dark_matter_construct (GType object_type);
static void movement_system_real_setWorld (BoscoECSISetWorld* base, BoscoECSWorld* world);
static void movement_system_real_initialize (BoscoECSIInitializeSystem* base);
GType bosco_ecs_entity_base_get_type (void) G_GNUC_CONST;
GType bosco_ecs_entity_get_type (void) G_GNUC_CONST;
GType bosco_ecs_imatcher_get_type (void) G_GNUC_CONST;
BoscoECSGroup* bosco_ecs_world_base_getGroup (BoscoECSWorldBase* self, BoscoECSIMatcher* matcher);
BoscoECSIMatcher* bosco_ecs_matcher_AllOf (gint* args, int args_length1);
GType component_get_type (void) G_GNUC_CONST;
static void movement_system_real_execute (BoscoECSIExecuteSystem* base);
BoscoECSEntity** bosco_ecs_group_getEntities (BoscoECSGroup* self, int* result_length1);
GType position_component_get_type (void) G_GNUC_CONST;
PositionComponent* bosco_ecs_entity_get_position (BoscoECSEntity* self);
GType velocity_component_get_type (void) G_GNUC_CONST;
VelocityComponent* bosco_ecs_entity_get_velocity (BoscoECSEntity* self);
GType bosco_ecs_icomponent_get_type (void) G_GNUC_CONST;
gdouble bosco_abstract_game_get_delta (BoscoAbstractGame* self);
static void movement_system_finalize (DarkMatter* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gpointer _dark_matter_ref0 (gpointer self) {
	return self ? dark_matter_ref (self) : NULL;
}


MovementSystem* movement_system_construct (GType object_type, Game* game) {
	MovementSystem* self = NULL;
	Game* _tmp0_ = NULL;
	Game* _tmp1_ = NULL;
	g_return_val_if_fail (game != NULL, NULL);
	self = (MovementSystem*) dark_matter_construct (object_type);
	_tmp0_ = game;
	_tmp1_ = _dark_matter_ref0 (_tmp0_);
	_dark_matter_unref0 (self->priv->_game);
	self->priv->_game = _tmp1_;
	return self;
}


MovementSystem* movement_system_new (Game* game) {
	return movement_system_construct (TYPE_MOVEMENT_SYSTEM, game);
}


static void movement_system_real_setWorld (BoscoECSISetWorld* base, BoscoECSWorld* world) {
	MovementSystem * self;
	BoscoECSWorld* _tmp0_ = NULL;
	BoscoECSWorld* _tmp1_ = NULL;
	self = (MovementSystem*) base;
	g_return_if_fail (world != NULL);
	_tmp0_ = world;
	_tmp1_ = _dark_matter_ref0 (_tmp0_);
	_dark_matter_unref0 (self->priv->_world);
	self->priv->_world = _tmp1_;
}


static void movement_system_real_initialize (BoscoECSIInitializeSystem* base) {
	MovementSystem * self;
	BoscoECSWorld* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint* _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	BoscoECSIMatcher* _tmp3_ = NULL;
	BoscoECSIMatcher* _tmp4_ = NULL;
	BoscoECSGroup* _tmp5_ = NULL;
	self = (MovementSystem*) base;
	_tmp0_ = self->priv->_world;
	_tmp1_ = g_new0 (gint, 2);
	_tmp1_[0] = (gint) COMPONENT_Position;
	_tmp1_[1] = (gint) COMPONENT_Velocity;
	_tmp2_ = _tmp1_;
	_tmp2__length1 = 2;
	_tmp3_ = bosco_ecs_matcher_AllOf (_tmp2_, 2);
	_tmp4_ = _tmp3_;
	_tmp5_ = bosco_ecs_world_base_getGroup ((BoscoECSWorldBase*) _tmp0_, _tmp4_);
	_dark_matter_unref0 (self->priv->_group);
	self->priv->_group = _tmp5_;
	_dark_matter_unref0 (_tmp4_);
	_tmp2_ = (g_free (_tmp2_), NULL);
}


static void movement_system_real_execute (BoscoECSIExecuteSystem* base) {
	MovementSystem * self;
	BoscoECSGroup* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	BoscoECSEntity** _tmp2_ = NULL;
	self = (MovementSystem*) base;
	_tmp0_ = self->priv->_group;
	_tmp2_ = bosco_ecs_group_getEntities (_tmp0_, &_tmp1_);
	{
		BoscoECSEntity** entity_collection = NULL;
		gint entity_collection_length1 = 0;
		gint _entity_collection_size_ = 0;
		gint entity_it = 0;
		entity_collection = _tmp2_;
		entity_collection_length1 = _tmp1_;
		for (entity_it = 0; entity_it < _tmp1_; entity_it = entity_it + 1) {
			BoscoECSEntity* _tmp3_ = NULL;
			BoscoECSEntity* entity = NULL;
			_tmp3_ = _dark_matter_ref0 (entity_collection[entity_it]);
			entity = _tmp3_;
			{
				PositionComponent* pos = NULL;
				BoscoECSEntity* _tmp4_ = NULL;
				PositionComponent* _tmp5_ = NULL;
				PositionComponent* _tmp6_ = NULL;
				PositionComponent* _tmp7_ = NULL;
				VelocityComponent* vel = NULL;
				BoscoECSEntity* _tmp8_ = NULL;
				VelocityComponent* _tmp9_ = NULL;
				VelocityComponent* _tmp10_ = NULL;
				VelocityComponent* _tmp11_ = NULL;
				PositionComponent* _tmp12_ = NULL;
				PositionComponent* _tmp13_ = NULL;
				gdouble _tmp14_ = 0.0;
				VelocityComponent* _tmp15_ = NULL;
				gdouble _tmp16_ = 0.0;
				Game* _tmp17_ = NULL;
				gdouble _tmp18_ = 0.0;
				gdouble _tmp19_ = 0.0;
				PositionComponent* _tmp20_ = NULL;
				PositionComponent* _tmp21_ = NULL;
				gdouble _tmp22_ = 0.0;
				VelocityComponent* _tmp23_ = NULL;
				gdouble _tmp24_ = 0.0;
				Game* _tmp25_ = NULL;
				gdouble _tmp26_ = 0.0;
				gdouble _tmp27_ = 0.0;
				_tmp4_ = entity;
				_tmp5_ = bosco_ecs_entity_get_position (_tmp4_);
				_tmp6_ = _tmp5_;
				_tmp7_ = _dark_matter_ref0 (_tmp6_);
				pos = _tmp7_;
				_tmp8_ = entity;
				_tmp9_ = bosco_ecs_entity_get_velocity (_tmp8_);
				_tmp10_ = _tmp9_;
				_tmp11_ = _dark_matter_ref0 (_tmp10_);
				vel = _tmp11_;
				_tmp12_ = pos;
				_tmp13_ = pos;
				_tmp14_ = _tmp13_->x;
				_tmp15_ = vel;
				_tmp16_ = _tmp15_->x;
				_tmp17_ = self->priv->_game;
				_tmp18_ = bosco_abstract_game_get_delta ((BoscoAbstractGame*) _tmp17_);
				_tmp19_ = _tmp18_;
				_tmp13_->x = _tmp14_ + (_tmp16_ * _tmp19_);
				_tmp20_ = pos;
				_tmp21_ = pos;
				_tmp22_ = _tmp21_->y;
				_tmp23_ = vel;
				_tmp24_ = _tmp23_->y;
				_tmp25_ = self->priv->_game;
				_tmp26_ = bosco_abstract_game_get_delta ((BoscoAbstractGame*) _tmp25_);
				_tmp27_ = _tmp26_;
				_tmp21_->y = _tmp22_ + (_tmp24_ * _tmp27_);
				_dark_matter_unref0 (vel);
				_dark_matter_unref0 (pos);
				_dark_matter_unref0 (entity);
			}
		}
		entity_collection = (_vala_array_free (entity_collection, entity_collection_length1, (GDestroyNotify) dark_matter_unref), NULL);
	}
}


static void movement_system_class_init (MovementSystemClass * klass) {
	movement_system_parent_class = g_type_class_peek_parent (klass);
	((DarkMatterClass *) klass)->finalize = movement_system_finalize;
	g_type_class_add_private (klass, sizeof (MovementSystemPrivate));
}


static void movement_system_bosco_ecs_isystem_interface_init (BoscoECSISystemIface * iface) {
	movement_system_bosco_ecs_isystem_parent_iface = g_type_interface_peek_parent (iface);
}


static void movement_system_bosco_ecs_iset_world_interface_init (BoscoECSISetWorldIface * iface) {
	movement_system_bosco_ecs_iset_world_parent_iface = g_type_interface_peek_parent (iface);
	iface->setWorld = (void (*)(BoscoECSISetWorld*, BoscoECSWorld*)) movement_system_real_setWorld;
}


static void movement_system_bosco_ecs_iinitialize_system_interface_init (BoscoECSIInitializeSystemIface * iface) {
	movement_system_bosco_ecs_iinitialize_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->initialize = (void (*)(BoscoECSIInitializeSystem*)) movement_system_real_initialize;
}


static void movement_system_bosco_ecs_iexecute_system_interface_init (BoscoECSIExecuteSystemIface * iface) {
	movement_system_bosco_ecs_iexecute_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->execute = (void (*)(BoscoECSIExecuteSystem*)) movement_system_real_execute;
}


static void movement_system_instance_init (MovementSystem * self) {
	self->priv = MOVEMENT_SYSTEM_GET_PRIVATE (self);
}


static void movement_system_finalize (DarkMatter* obj) {
	MovementSystem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MOVEMENT_SYSTEM, MovementSystem);
	_dark_matter_unref0 (self->priv->_world);
	_dark_matter_unref0 (self->priv->_group);
	_dark_matter_unref0 (self->priv->_game);
	DARK_MATTER_CLASS (movement_system_parent_class)->finalize (obj);
}


GType movement_system_get_type (void) {
	static volatile gsize movement_system_type_id__volatile = 0;
	if (g_once_init_enter (&movement_system_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MovementSystemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) movement_system_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MovementSystem), 0, (GInstanceInitFunc) movement_system_instance_init, NULL };
		static const GInterfaceInfo bosco_ecs_isystem_info = { (GInterfaceInitFunc) movement_system_bosco_ecs_isystem_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo bosco_ecs_iset_world_info = { (GInterfaceInitFunc) movement_system_bosco_ecs_iset_world_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo bosco_ecs_iinitialize_system_info = { (GInterfaceInitFunc) movement_system_bosco_ecs_iinitialize_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo bosco_ecs_iexecute_system_info = { (GInterfaceInitFunc) movement_system_bosco_ecs_iexecute_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType movement_system_type_id;
		movement_system_type_id = g_type_register_static (TYPE_DARK_MATTER, "MovementSystem", &g_define_type_info, 0);
		g_type_add_interface_static (movement_system_type_id, BOSCO_ECS_TYPE_ISYSTEM, &bosco_ecs_isystem_info);
		g_type_add_interface_static (movement_system_type_id, BOSCO_ECS_TYPE_ISET_WORLD, &bosco_ecs_iset_world_info);
		g_type_add_interface_static (movement_system_type_id, BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM, &bosco_ecs_iinitialize_system_info);
		g_type_add_interface_static (movement_system_type_id, BOSCO_ECS_TYPE_IEXECUTE_SYSTEM, &bosco_ecs_iexecute_system_info);
		g_once_init_leave (&movement_system_type_id__volatile, movement_system_type_id);
	}
	return movement_system_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



