/* ScaleTweenSystem.c generated by valac 0.34.4, the Vala compiler
 * generated from ScaleTweenSystem.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <SDL2/SDL_render.h>


#define TYPE_DARK_MATTER (dark_matter_get_type ())
#define DARK_MATTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DARK_MATTER, DarkMatter))
#define DARK_MATTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DARK_MATTER, DarkMatterClass))
#define IS_DARK_MATTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DARK_MATTER))
#define IS_DARK_MATTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DARK_MATTER))
#define DARK_MATTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DARK_MATTER, DarkMatterClass))

typedef struct _DarkMatter DarkMatter;
typedef struct _DarkMatterClass DarkMatterClass;
typedef struct _DarkMatterPrivate DarkMatterPrivate;

#define BOSCO_ECS_TYPE_ISYSTEM (bosco_ecs_isystem_get_type ())
#define BOSCO_ECS_ISYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ISYSTEM, BoscoECSISystem))
#define BOSCO_ECS_IS_ISYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ISYSTEM))
#define BOSCO_ECS_ISYSTEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_ISYSTEM, BoscoECSISystemIface))

typedef struct _BoscoECSISystem BoscoECSISystem;
typedef struct _BoscoECSISystemIface BoscoECSISystemIface;

#define BOSCO_ECS_TYPE_ISET_WORLD (bosco_ecs_iset_world_get_type ())
#define BOSCO_ECS_ISET_WORLD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ISET_WORLD, BoscoECSISetWorld))
#define BOSCO_ECS_IS_ISET_WORLD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ISET_WORLD))
#define BOSCO_ECS_ISET_WORLD_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_ISET_WORLD, BoscoECSISetWorldIface))

typedef struct _BoscoECSISetWorld BoscoECSISetWorld;
typedef struct _BoscoECSISetWorldIface BoscoECSISetWorldIface;

#define BOSCO_ECS_TYPE_WORLD_BASE (bosco_ecs_world_base_get_type ())
#define BOSCO_ECS_WORLD_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_WORLD_BASE, BoscoECSWorldBase))
#define BOSCO_ECS_WORLD_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_WORLD_BASE, BoscoECSWorldBaseClass))
#define BOSCO_ECS_IS_WORLD_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_WORLD_BASE))
#define BOSCO_ECS_IS_WORLD_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_WORLD_BASE))
#define BOSCO_ECS_WORLD_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_WORLD_BASE, BoscoECSWorldBaseClass))

typedef struct _BoscoECSWorldBase BoscoECSWorldBase;
typedef struct _BoscoECSWorldBaseClass BoscoECSWorldBaseClass;

#define BOSCO_ECS_TYPE_WORLD (bosco_ecs_world_get_type ())
#define BOSCO_ECS_WORLD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_WORLD, BoscoECSWorld))
#define BOSCO_ECS_WORLD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_WORLD, BoscoECSWorldClass))
#define BOSCO_ECS_IS_WORLD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_WORLD))
#define BOSCO_ECS_IS_WORLD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_WORLD))
#define BOSCO_ECS_WORLD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_WORLD, BoscoECSWorldClass))

typedef struct _BoscoECSWorld BoscoECSWorld;
typedef struct _BoscoECSWorldClass BoscoECSWorldClass;

#define BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM (bosco_ecs_iinitialize_system_get_type ())
#define BOSCO_ECS_IINITIALIZE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM, BoscoECSIInitializeSystem))
#define BOSCO_ECS_IS_IINITIALIZE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM))
#define BOSCO_ECS_IINITIALIZE_SYSTEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM, BoscoECSIInitializeSystemIface))

typedef struct _BoscoECSIInitializeSystem BoscoECSIInitializeSystem;
typedef struct _BoscoECSIInitializeSystemIface BoscoECSIInitializeSystemIface;

#define BOSCO_ECS_TYPE_IEXECUTE_SYSTEM (bosco_ecs_iexecute_system_get_type ())
#define BOSCO_ECS_IEXECUTE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_IEXECUTE_SYSTEM, BoscoECSIExecuteSystem))
#define BOSCO_ECS_IS_IEXECUTE_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_IEXECUTE_SYSTEM))
#define BOSCO_ECS_IEXECUTE_SYSTEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_IEXECUTE_SYSTEM, BoscoECSIExecuteSystemIface))

typedef struct _BoscoECSIExecuteSystem BoscoECSIExecuteSystem;
typedef struct _BoscoECSIExecuteSystemIface BoscoECSIExecuteSystemIface;

#define TYPE_SCALE_TWEEN_SYSTEM (scale_tween_system_get_type ())
#define SCALE_TWEEN_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SCALE_TWEEN_SYSTEM, ScaleTweenSystem))
#define SCALE_TWEEN_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SCALE_TWEEN_SYSTEM, ScaleTweenSystemClass))
#define IS_SCALE_TWEEN_SYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SCALE_TWEEN_SYSTEM))
#define IS_SCALE_TWEEN_SYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SCALE_TWEEN_SYSTEM))
#define SCALE_TWEEN_SYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SCALE_TWEEN_SYSTEM, ScaleTweenSystemClass))

typedef struct _ScaleTweenSystem ScaleTweenSystem;
typedef struct _ScaleTweenSystemClass ScaleTweenSystemClass;
typedef struct _ScaleTweenSystemPrivate ScaleTweenSystemPrivate;

#define BOSCO_ECS_TYPE_GROUP (bosco_ecs_group_get_type ())
#define BOSCO_ECS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_GROUP, BoscoECSGroup))
#define BOSCO_ECS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_GROUP, BoscoECSGroupClass))
#define BOSCO_ECS_IS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_GROUP))
#define BOSCO_ECS_IS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_GROUP))
#define BOSCO_ECS_GROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_GROUP, BoscoECSGroupClass))

typedef struct _BoscoECSGroup BoscoECSGroup;
typedef struct _BoscoECSGroupClass BoscoECSGroupClass;

#define BOSCO_TYPE_ABSTRACT_GAME (bosco_abstract_game_get_type ())
#define BOSCO_ABSTRACT_GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_TYPE_ABSTRACT_GAME, BoscoAbstractGame))
#define BOSCO_ABSTRACT_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_TYPE_ABSTRACT_GAME, BoscoAbstractGameClass))
#define BOSCO_IS_ABSTRACT_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_TYPE_ABSTRACT_GAME))
#define BOSCO_IS_ABSTRACT_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_TYPE_ABSTRACT_GAME))
#define BOSCO_ABSTRACT_GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_TYPE_ABSTRACT_GAME, BoscoAbstractGameClass))

typedef struct _BoscoAbstractGame BoscoAbstractGame;
typedef struct _BoscoAbstractGameClass BoscoAbstractGameClass;

#define TYPE_GAME (game_get_type ())
#define GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAME, Game))
#define GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAME, GameClass))
#define IS_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAME))
#define IS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAME))
#define GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAME, GameClass))

typedef struct _Game Game;
typedef struct _GameClass GameClass;
#define _dark_matter_unref0(var) ((var == NULL) ? NULL : (var = (dark_matter_unref (var), NULL)))

#define BOSCO_ECS_TYPE_IMATCHER (bosco_ecs_imatcher_get_type ())
#define BOSCO_ECS_IMATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_IMATCHER, BoscoECSIMatcher))
#define BOSCO_ECS_IS_IMATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_IMATCHER))
#define BOSCO_ECS_IMATCHER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_IMATCHER, BoscoECSIMatcherIface))

typedef struct _BoscoECSIMatcher BoscoECSIMatcher;
typedef struct _BoscoECSIMatcherIface BoscoECSIMatcherIface;

#define BOSCO_ECS_TYPE_ENTITY_BASE (bosco_ecs_entity_base_get_type ())
#define BOSCO_ECS_ENTITY_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ENTITY_BASE, BoscoECSEntityBase))
#define BOSCO_ECS_ENTITY_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_ENTITY_BASE, BoscoECSEntityBaseClass))
#define BOSCO_ECS_IS_ENTITY_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ENTITY_BASE))
#define BOSCO_ECS_IS_ENTITY_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_ENTITY_BASE))
#define BOSCO_ECS_ENTITY_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_ENTITY_BASE, BoscoECSEntityBaseClass))

typedef struct _BoscoECSEntityBase BoscoECSEntityBase;
typedef struct _BoscoECSEntityBaseClass BoscoECSEntityBaseClass;

#define BOSCO_ECS_TYPE_ENTITY (bosco_ecs_entity_get_type ())
#define BOSCO_ECS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ENTITY, BoscoECSEntity))
#define BOSCO_ECS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_ENTITY, BoscoECSEntityClass))
#define BOSCO_ECS_IS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ENTITY))
#define BOSCO_ECS_IS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_ENTITY))
#define BOSCO_ECS_ENTITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_ENTITY, BoscoECSEntityClass))

typedef struct _BoscoECSEntity BoscoECSEntity;
typedef struct _BoscoECSEntityClass BoscoECSEntityClass;

#define TYPE_COMPONENT (component_get_type ())

#define TYPE_SCALE_TWEEN_COMPONENT (scale_tween_component_get_type ())
#define SCALE_TWEEN_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SCALE_TWEEN_COMPONENT, ScaleTweenComponent))
#define SCALE_TWEEN_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SCALE_TWEEN_COMPONENT, ScaleTweenComponentClass))
#define IS_SCALE_TWEEN_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SCALE_TWEEN_COMPONENT))
#define IS_SCALE_TWEEN_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SCALE_TWEEN_COMPONENT))
#define SCALE_TWEEN_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SCALE_TWEEN_COMPONENT, ScaleTweenComponentClass))

typedef struct _ScaleTweenComponent ScaleTweenComponent;
typedef struct _ScaleTweenComponentClass ScaleTweenComponentClass;

#define BOSCO_ECS_TYPE_ICOMPONENT (bosco_ecs_icomponent_get_type ())
#define BOSCO_ECS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ICOMPONENT, BoscoECSIComponent))
#define BOSCO_ECS_IS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ICOMPONENT))
#define BOSCO_ECS_ICOMPONENT_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_ICOMPONENT, BoscoECSIComponentIface))

typedef struct _BoscoECSIComponent BoscoECSIComponent;
typedef struct _BoscoECSIComponentIface BoscoECSIComponentIface;
typedef struct _ScaleTweenComponentPrivate ScaleTweenComponentPrivate;

#define TYPE_RESOURCE_COMPONENT (resource_component_get_type ())
#define RESOURCE_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RESOURCE_COMPONENT, ResourceComponent))
#define RESOURCE_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_RESOURCE_COMPONENT, ResourceComponentClass))
#define IS_RESOURCE_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RESOURCE_COMPONENT))
#define IS_RESOURCE_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_RESOURCE_COMPONENT))
#define RESOURCE_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RESOURCE_COMPONENT, ResourceComponentClass))

typedef struct _ResourceComponent ResourceComponent;
typedef struct _ResourceComponentClass ResourceComponentClass;

#define BOSCO_TYPE_SCALE (bosco_scale_get_type ())
typedef struct _BoscoScale BoscoScale;
typedef struct _ResourceComponentPrivate ResourceComponentPrivate;

#define BOSCO_TYPE_SPRITE (bosco_sprite_get_type ())
#define BOSCO_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_TYPE_SPRITE, BoscoSprite))
#define BOSCO_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_TYPE_SPRITE, BoscoSpriteClass))
#define BOSCO_IS_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_TYPE_SPRITE))
#define BOSCO_IS_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_TYPE_SPRITE))
#define BOSCO_SPRITE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_TYPE_SPRITE, BoscoSpriteClass))

typedef struct _BoscoSprite BoscoSprite;
typedef struct _BoscoSpriteClass BoscoSpriteClass;
typedef struct _BoscoSpritePrivate BoscoSpritePrivate;

#define BOSCO_TYPE_COLOR (bosco_color_get_type ())
typedef struct _BoscoColor BoscoColor;

struct _DarkMatter {
	GTypeInstance parent_instance;
	volatile int ref_count;
	DarkMatterPrivate * priv;
};

struct _DarkMatterClass {
	GTypeClass parent_class;
	void (*finalize) (DarkMatter *self);
};

struct _BoscoECSISystemIface {
	GTypeInterface parent_iface;
};

struct _BoscoECSISetWorldIface {
	GTypeInterface parent_iface;
	void (*setWorld) (BoscoECSISetWorld* self, BoscoECSWorld* world);
};

struct _BoscoECSIInitializeSystemIface {
	GTypeInterface parent_iface;
	void (*initialize) (BoscoECSIInitializeSystem* self);
};

struct _BoscoECSIExecuteSystemIface {
	GTypeInterface parent_iface;
	void (*execute) (BoscoECSIExecuteSystem* self);
};

struct _ScaleTweenSystem {
	DarkMatter parent_instance;
	ScaleTweenSystemPrivate * priv;
};

struct _ScaleTweenSystemClass {
	DarkMatterClass parent_class;
};

struct _ScaleTweenSystemPrivate {
	BoscoECSWorld* _world;
	BoscoECSGroup* _group;
	Game* _game;
};

struct _BoscoECSIMatcherIface {
	GTypeInterface parent_iface;
	gboolean (*matches) (BoscoECSIMatcher* self, BoscoECSEntity* entity);
	gchar* (*toString) (BoscoECSIMatcher* self);
	const gchar* (*get_id) (BoscoECSIMatcher* self);
	gint* (*get_indices) (BoscoECSIMatcher* self, int* result_length1);
};

typedef enum  {
	COMPONENT_Bounds,
	COMPONENT_Bullet,
	COMPONENT_ColorTween,
	COMPONENT_Destroy,
	COMPONENT_Enemy,
	COMPONENT_Expires,
	COMPONENT_Firing,
	COMPONENT_Health,
	COMPONENT_Layer,
	COMPONENT_Life,
	COMPONENT_Mine,
	COMPONENT_Mouse,
	COMPONENT_Player,
	COMPONENT_Position,
	COMPONENT_Resource,
	COMPONENT_ScaleTween,
	COMPONENT_Scale,
	COMPONENT_Score,
	COMPONENT_SoundEffect,
	COMPONENT_Tint,
	COMPONENT_Velocity,
	COMPONENT_TotalComponents
} Component;

struct _BoscoECSIComponentIface {
	GTypeInterface parent_iface;
};

struct _ScaleTweenComponent {
	DarkMatter parent_instance;
	ScaleTweenComponentPrivate * priv;
	gdouble min;
	gdouble max;
	gdouble speed;
	gboolean repeat;
	gboolean active;
};

struct _ScaleTweenComponentClass {
	DarkMatterClass parent_class;
};

struct _BoscoScale {
	gdouble x;
	gdouble y;
};

struct _ResourceComponent {
	DarkMatter parent_instance;
	ResourceComponentPrivate * priv;
	gchar* path;
	BoscoSprite* sprite;
	gboolean bgd;
};

struct _ResourceComponentClass {
	DarkMatterClass parent_class;
};

struct _BoscoColor {
	guint8 r;
	guint8 g;
	guint8 b;
	guint8 a;
};

struct _BoscoSprite {
	DarkMatter parent_instance;
	BoscoSpritePrivate * priv;
	SDL_Texture* texture;
	gint width;
	gint height;
	gint x;
	gint y;
	BoscoScale scale;
	BoscoColor color;
	gboolean centered;
	gint layer;
	gint id;
};

struct _BoscoSpriteClass {
	DarkMatterClass parent_class;
};


static gpointer scale_tween_system_parent_class = NULL;
static BoscoECSISystemIface* scale_tween_system_bosco_ecs_isystem_parent_iface = NULL;
static BoscoECSISetWorldIface* scale_tween_system_bosco_ecs_iset_world_parent_iface = NULL;
static BoscoECSIInitializeSystemIface* scale_tween_system_bosco_ecs_iinitialize_system_parent_iface = NULL;
static BoscoECSIExecuteSystemIface* scale_tween_system_bosco_ecs_iexecute_system_parent_iface = NULL;

gpointer dark_matter_ref (gpointer instance);
void dark_matter_unref (gpointer instance);
GParamSpec* param_spec_dark_matter (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_dark_matter (GValue* value, gpointer v_object);
void value_take_dark_matter (GValue* value, gpointer v_object);
gpointer value_get_dark_matter (const GValue* value);
GType dark_matter_get_type (void) G_GNUC_CONST;
GType bosco_ecs_isystem_get_type (void) G_GNUC_CONST;
GType bosco_ecs_world_base_get_type (void) G_GNUC_CONST;
GType bosco_ecs_world_get_type (void) G_GNUC_CONST;
GType bosco_ecs_iset_world_get_type (void) G_GNUC_CONST;
GType bosco_ecs_iinitialize_system_get_type (void) G_GNUC_CONST;
GType bosco_ecs_iexecute_system_get_type (void) G_GNUC_CONST;
GType scale_tween_system_get_type (void) G_GNUC_CONST;
GType bosco_ecs_group_get_type (void) G_GNUC_CONST;
GType bosco_abstract_game_get_type (void) G_GNUC_CONST;
GType game_get_type (void) G_GNUC_CONST;
#define SCALE_TWEEN_SYSTEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_SCALE_TWEEN_SYSTEM, ScaleTweenSystemPrivate))
enum  {
	SCALE_TWEEN_SYSTEM_DUMMY_PROPERTY
};
ScaleTweenSystem* scale_tween_system_new (Game* game);
ScaleTweenSystem* scale_tween_system_construct (GType object_type, Game* game);
DarkMatter* dark_matter_new (void);
DarkMatter* dark_matter_construct (GType object_type);
static void scale_tween_system_real_setWorld (BoscoECSISetWorld* base, BoscoECSWorld* world);
static void scale_tween_system_real_initialize (BoscoECSIInitializeSystem* base);
GType bosco_ecs_entity_base_get_type (void) G_GNUC_CONST;
GType bosco_ecs_entity_get_type (void) G_GNUC_CONST;
GType bosco_ecs_imatcher_get_type (void) G_GNUC_CONST;
BoscoECSGroup* bosco_ecs_world_base_getGroup (BoscoECSWorldBase* self, BoscoECSIMatcher* matcher);
BoscoECSIMatcher* bosco_ecs_matcher_AllOf (gint* args, int args_length1);
GType component_get_type (void) G_GNUC_CONST;
static void scale_tween_system_real_execute (BoscoECSIExecuteSystem* base);
BoscoECSEntity** bosco_ecs_group_getEntities (BoscoECSGroup* self, int* result_length1);
GType scale_tween_component_get_type (void) G_GNUC_CONST;
ScaleTweenComponent* bosco_ecs_entity_get_scaleTween (BoscoECSEntity* self);
GType bosco_ecs_icomponent_get_type (void) G_GNUC_CONST;
GType resource_component_get_type (void) G_GNUC_CONST;
ResourceComponent* bosco_ecs_entity_get_resource (BoscoECSEntity* self);
GType bosco_scale_get_type (void) G_GNUC_CONST;
BoscoScale* bosco_scale_dup (const BoscoScale* self);
void bosco_scale_free (BoscoScale* self);
GType bosco_sprite_get_type (void) G_GNUC_CONST;
GType bosco_color_get_type (void) G_GNUC_CONST;
BoscoColor* bosco_color_dup (const BoscoColor* self);
void bosco_color_free (BoscoColor* self);
gdouble bosco_abstract_game_get_delta (BoscoAbstractGame* self);
static void scale_tween_system_finalize (DarkMatter* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gpointer _dark_matter_ref0 (gpointer self) {
	return self ? dark_matter_ref (self) : NULL;
}


ScaleTweenSystem* scale_tween_system_construct (GType object_type, Game* game) {
	ScaleTweenSystem* self = NULL;
	Game* _tmp0_ = NULL;
	Game* _tmp1_ = NULL;
	g_return_val_if_fail (game != NULL, NULL);
	self = (ScaleTweenSystem*) dark_matter_construct (object_type);
	_tmp0_ = game;
	_tmp1_ = _dark_matter_ref0 (_tmp0_);
	_dark_matter_unref0 (self->priv->_game);
	self->priv->_game = _tmp1_;
	return self;
}


ScaleTweenSystem* scale_tween_system_new (Game* game) {
	return scale_tween_system_construct (TYPE_SCALE_TWEEN_SYSTEM, game);
}


static void scale_tween_system_real_setWorld (BoscoECSISetWorld* base, BoscoECSWorld* world) {
	ScaleTweenSystem * self;
	BoscoECSWorld* _tmp0_ = NULL;
	BoscoECSWorld* _tmp1_ = NULL;
	self = (ScaleTweenSystem*) base;
	g_return_if_fail (world != NULL);
	_tmp0_ = world;
	_tmp1_ = _dark_matter_ref0 (_tmp0_);
	_dark_matter_unref0 (self->priv->_world);
	self->priv->_world = _tmp1_;
}


static void scale_tween_system_real_initialize (BoscoECSIInitializeSystem* base) {
	ScaleTweenSystem * self;
	BoscoECSWorld* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint* _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	BoscoECSIMatcher* _tmp3_ = NULL;
	BoscoECSIMatcher* _tmp4_ = NULL;
	BoscoECSGroup* _tmp5_ = NULL;
	self = (ScaleTweenSystem*) base;
	_tmp0_ = self->priv->_world;
	_tmp1_ = g_new0 (gint, 2);
	_tmp1_[0] = (gint) COMPONENT_ScaleTween;
	_tmp1_[1] = (gint) COMPONENT_Resource;
	_tmp2_ = _tmp1_;
	_tmp2__length1 = 2;
	_tmp3_ = bosco_ecs_matcher_AllOf (_tmp2_, 2);
	_tmp4_ = _tmp3_;
	_tmp5_ = bosco_ecs_world_base_getGroup ((BoscoECSWorldBase*) _tmp0_, _tmp4_);
	_dark_matter_unref0 (self->priv->_group);
	self->priv->_group = _tmp5_;
	_dark_matter_unref0 (_tmp4_);
	_tmp2_ = (g_free (_tmp2_), NULL);
}


static void scale_tween_system_real_execute (BoscoECSIExecuteSystem* base) {
	ScaleTweenSystem * self;
	BoscoECSGroup* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	BoscoECSEntity** _tmp2_ = NULL;
	self = (ScaleTweenSystem*) base;
	_tmp0_ = self->priv->_group;
	_tmp2_ = bosco_ecs_group_getEntities (_tmp0_, &_tmp1_);
	{
		BoscoECSEntity** entity_collection = NULL;
		gint entity_collection_length1 = 0;
		gint _entity_collection_size_ = 0;
		gint entity_it = 0;
		entity_collection = _tmp2_;
		entity_collection_length1 = _tmp1_;
		for (entity_it = 0; entity_it < _tmp1_; entity_it = entity_it + 1) {
			BoscoECSEntity* _tmp3_ = NULL;
			BoscoECSEntity* entity = NULL;
			_tmp3_ = _dark_matter_ref0 (entity_collection[entity_it]);
			entity = _tmp3_;
			{
				ScaleTweenComponent* scaleTween = NULL;
				BoscoECSEntity* _tmp4_ = NULL;
				ScaleTweenComponent* _tmp5_ = NULL;
				ScaleTweenComponent* _tmp6_ = NULL;
				ScaleTweenComponent* _tmp7_ = NULL;
				ScaleTweenComponent* _tmp8_ = NULL;
				gboolean _tmp9_ = FALSE;
				_tmp4_ = entity;
				_tmp5_ = bosco_ecs_entity_get_scaleTween (_tmp4_);
				_tmp6_ = _tmp5_;
				_tmp7_ = _dark_matter_ref0 (_tmp6_);
				scaleTween = _tmp7_;
				_tmp8_ = scaleTween;
				_tmp9_ = _tmp8_->active;
				if (_tmp9_) {
					ResourceComponent* res = NULL;
					BoscoECSEntity* _tmp10_ = NULL;
					ResourceComponent* _tmp11_ = NULL;
					ResourceComponent* _tmp12_ = NULL;
					ResourceComponent* _tmp13_ = NULL;
					BoscoScale scale = {0};
					ResourceComponent* _tmp14_ = NULL;
					BoscoSprite* _tmp15_ = NULL;
					BoscoScale _tmp16_ = {0};
					ResourceComponent* _tmp17_ = NULL;
					BoscoSprite* _tmp18_ = NULL;
					ResourceComponent* _tmp19_ = NULL;
					BoscoSprite* _tmp20_ = NULL;
					gdouble _tmp21_ = 0.0;
					ScaleTweenComponent* _tmp22_ = NULL;
					gdouble _tmp23_ = 0.0;
					Game* _tmp24_ = NULL;
					gdouble _tmp25_ = 0.0;
					gdouble _tmp26_ = 0.0;
					ResourceComponent* _tmp27_ = NULL;
					BoscoSprite* _tmp28_ = NULL;
					ResourceComponent* _tmp29_ = NULL;
					BoscoSprite* _tmp30_ = NULL;
					gdouble _tmp31_ = 0.0;
					ScaleTweenComponent* _tmp32_ = NULL;
					gdouble _tmp33_ = 0.0;
					Game* _tmp34_ = NULL;
					gdouble _tmp35_ = 0.0;
					gdouble _tmp36_ = 0.0;
					BoscoScale _tmp37_ = {0};
					gdouble _tmp38_ = 0.0;
					ScaleTweenComponent* _tmp39_ = NULL;
					gdouble _tmp40_ = 0.0;
					_tmp10_ = entity;
					_tmp11_ = bosco_ecs_entity_get_resource (_tmp10_);
					_tmp12_ = _tmp11_;
					_tmp13_ = _dark_matter_ref0 (_tmp12_);
					res = _tmp13_;
					_tmp14_ = res;
					_tmp15_ = _tmp14_->sprite;
					_tmp16_ = _tmp15_->scale;
					scale = _tmp16_;
					_tmp17_ = res;
					_tmp18_ = _tmp17_->sprite;
					_tmp19_ = res;
					_tmp20_ = _tmp19_->sprite;
					_tmp21_ = _tmp20_->scale.x;
					_tmp22_ = scaleTween;
					_tmp23_ = _tmp22_->speed;
					_tmp24_ = self->priv->_game;
					_tmp25_ = bosco_abstract_game_get_delta ((BoscoAbstractGame*) _tmp24_);
					_tmp26_ = _tmp25_;
					_tmp20_->scale.x = _tmp21_ + (_tmp23_ * _tmp26_);
					_tmp27_ = res;
					_tmp28_ = _tmp27_->sprite;
					_tmp29_ = res;
					_tmp30_ = _tmp29_->sprite;
					_tmp31_ = _tmp30_->scale.y;
					_tmp32_ = scaleTween;
					_tmp33_ = _tmp32_->speed;
					_tmp34_ = self->priv->_game;
					_tmp35_ = bosco_abstract_game_get_delta ((BoscoAbstractGame*) _tmp34_);
					_tmp36_ = _tmp35_;
					_tmp30_->scale.y = _tmp31_ + (_tmp33_ * _tmp36_);
					_tmp37_ = scale;
					_tmp38_ = _tmp37_.x;
					_tmp39_ = scaleTween;
					_tmp40_ = _tmp39_->max;
					if (_tmp38_ > _tmp40_) {
						ResourceComponent* _tmp41_ = NULL;
						BoscoSprite* _tmp42_ = NULL;
						ScaleTweenComponent* _tmp43_ = NULL;
						gdouble _tmp44_ = 0.0;
						ResourceComponent* _tmp45_ = NULL;
						BoscoSprite* _tmp46_ = NULL;
						ScaleTweenComponent* _tmp47_ = NULL;
						gdouble _tmp48_ = 0.0;
						ScaleTweenComponent* _tmp49_ = NULL;
						_tmp41_ = res;
						_tmp42_ = _tmp41_->sprite;
						_tmp43_ = scaleTween;
						_tmp44_ = _tmp43_->max;
						_tmp42_->scale.x = _tmp44_;
						_tmp45_ = res;
						_tmp46_ = _tmp45_->sprite;
						_tmp47_ = scaleTween;
						_tmp48_ = _tmp47_->max;
						_tmp46_->scale.y = _tmp48_;
						_tmp49_ = scaleTween;
						_tmp49_->active = FALSE;
					} else {
						BoscoScale _tmp50_ = {0};
						gdouble _tmp51_ = 0.0;
						ScaleTweenComponent* _tmp52_ = NULL;
						gdouble _tmp53_ = 0.0;
						_tmp50_ = scale;
						_tmp51_ = _tmp50_.x;
						_tmp52_ = scaleTween;
						_tmp53_ = _tmp52_->min;
						if (_tmp51_ < _tmp53_) {
							ResourceComponent* _tmp54_ = NULL;
							BoscoSprite* _tmp55_ = NULL;
							ScaleTweenComponent* _tmp56_ = NULL;
							gdouble _tmp57_ = 0.0;
							ResourceComponent* _tmp58_ = NULL;
							BoscoSprite* _tmp59_ = NULL;
							ScaleTweenComponent* _tmp60_ = NULL;
							gdouble _tmp61_ = 0.0;
							ScaleTweenComponent* _tmp62_ = NULL;
							_tmp54_ = res;
							_tmp55_ = _tmp54_->sprite;
							_tmp56_ = scaleTween;
							_tmp57_ = _tmp56_->min;
							_tmp55_->scale.x = _tmp57_;
							_tmp58_ = res;
							_tmp59_ = _tmp58_->sprite;
							_tmp60_ = scaleTween;
							_tmp61_ = _tmp60_->min;
							_tmp59_->scale.y = _tmp61_;
							_tmp62_ = scaleTween;
							_tmp62_->active = FALSE;
						}
					}
					_dark_matter_unref0 (res);
				}
				_dark_matter_unref0 (scaleTween);
				_dark_matter_unref0 (entity);
			}
		}
		entity_collection = (_vala_array_free (entity_collection, entity_collection_length1, (GDestroyNotify) dark_matter_unref), NULL);
	}
}


static void scale_tween_system_class_init (ScaleTweenSystemClass * klass) {
	scale_tween_system_parent_class = g_type_class_peek_parent (klass);
	((DarkMatterClass *) klass)->finalize = scale_tween_system_finalize;
	g_type_class_add_private (klass, sizeof (ScaleTweenSystemPrivate));
}


static void scale_tween_system_bosco_ecs_isystem_interface_init (BoscoECSISystemIface * iface) {
	scale_tween_system_bosco_ecs_isystem_parent_iface = g_type_interface_peek_parent (iface);
}


static void scale_tween_system_bosco_ecs_iset_world_interface_init (BoscoECSISetWorldIface * iface) {
	scale_tween_system_bosco_ecs_iset_world_parent_iface = g_type_interface_peek_parent (iface);
	iface->setWorld = (void (*)(BoscoECSISetWorld*, BoscoECSWorld*)) scale_tween_system_real_setWorld;
}


static void scale_tween_system_bosco_ecs_iinitialize_system_interface_init (BoscoECSIInitializeSystemIface * iface) {
	scale_tween_system_bosco_ecs_iinitialize_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->initialize = (void (*)(BoscoECSIInitializeSystem*)) scale_tween_system_real_initialize;
}


static void scale_tween_system_bosco_ecs_iexecute_system_interface_init (BoscoECSIExecuteSystemIface * iface) {
	scale_tween_system_bosco_ecs_iexecute_system_parent_iface = g_type_interface_peek_parent (iface);
	iface->execute = (void (*)(BoscoECSIExecuteSystem*)) scale_tween_system_real_execute;
}


static void scale_tween_system_instance_init (ScaleTweenSystem * self) {
	self->priv = SCALE_TWEEN_SYSTEM_GET_PRIVATE (self);
}


static void scale_tween_system_finalize (DarkMatter* obj) {
	ScaleTweenSystem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_SCALE_TWEEN_SYSTEM, ScaleTweenSystem);
	_dark_matter_unref0 (self->priv->_world);
	_dark_matter_unref0 (self->priv->_group);
	_dark_matter_unref0 (self->priv->_game);
	DARK_MATTER_CLASS (scale_tween_system_parent_class)->finalize (obj);
}


GType scale_tween_system_get_type (void) {
	static volatile gsize scale_tween_system_type_id__volatile = 0;
	if (g_once_init_enter (&scale_tween_system_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ScaleTweenSystemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) scale_tween_system_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ScaleTweenSystem), 0, (GInstanceInitFunc) scale_tween_system_instance_init, NULL };
		static const GInterfaceInfo bosco_ecs_isystem_info = { (GInterfaceInitFunc) scale_tween_system_bosco_ecs_isystem_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo bosco_ecs_iset_world_info = { (GInterfaceInitFunc) scale_tween_system_bosco_ecs_iset_world_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo bosco_ecs_iinitialize_system_info = { (GInterfaceInitFunc) scale_tween_system_bosco_ecs_iinitialize_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo bosco_ecs_iexecute_system_info = { (GInterfaceInitFunc) scale_tween_system_bosco_ecs_iexecute_system_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType scale_tween_system_type_id;
		scale_tween_system_type_id = g_type_register_static (TYPE_DARK_MATTER, "ScaleTweenSystem", &g_define_type_info, 0);
		g_type_add_interface_static (scale_tween_system_type_id, BOSCO_ECS_TYPE_ISYSTEM, &bosco_ecs_isystem_info);
		g_type_add_interface_static (scale_tween_system_type_id, BOSCO_ECS_TYPE_ISET_WORLD, &bosco_ecs_iset_world_info);
		g_type_add_interface_static (scale_tween_system_type_id, BOSCO_ECS_TYPE_IINITIALIZE_SYSTEM, &bosco_ecs_iinitialize_system_info);
		g_type_add_interface_static (scale_tween_system_type_id, BOSCO_ECS_TYPE_IEXECUTE_SYSTEM, &bosco_ecs_iexecute_system_info);
		g_once_init_leave (&scale_tween_system_type_id__volatile, scale_tween_system_type_id);
	}
	return scale_tween_system_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



