/* EntityBase.c generated by valac 0.34.4, the Vala compiler
 * generated from EntityBase.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_DARK_MATTER (dark_matter_get_type ())
#define DARK_MATTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DARK_MATTER, DarkMatter))
#define DARK_MATTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DARK_MATTER, DarkMatterClass))
#define IS_DARK_MATTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DARK_MATTER))
#define IS_DARK_MATTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DARK_MATTER))
#define DARK_MATTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DARK_MATTER, DarkMatterClass))

typedef struct _DarkMatter DarkMatter;
typedef struct _DarkMatterClass DarkMatterClass;
typedef struct _DarkMatterPrivate DarkMatterPrivate;

#define BOSCO_ECS_TYPE_ENTITY_BASE (bosco_ecs_entity_base_get_type ())
#define BOSCO_ECS_ENTITY_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ENTITY_BASE, BoscoECSEntityBase))
#define BOSCO_ECS_ENTITY_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_ENTITY_BASE, BoscoECSEntityBaseClass))
#define BOSCO_ECS_IS_ENTITY_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ENTITY_BASE))
#define BOSCO_ECS_IS_ENTITY_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_ENTITY_BASE))
#define BOSCO_ECS_ENTITY_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_ENTITY_BASE, BoscoECSEntityBaseClass))

typedef struct _BoscoECSEntityBase BoscoECSEntityBase;
typedef struct _BoscoECSEntityBaseClass BoscoECSEntityBaseClass;
typedef struct _BoscoECSEntityBasePrivate BoscoECSEntityBasePrivate;

#define BOSCO_ECS_TYPE_ENTITY_RELEASED (bosco_ecs_entity_released_get_type ())
#define BOSCO_ECS_ENTITY_RELEASED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ENTITY_RELEASED, BoscoECSEntityReleased))
#define BOSCO_ECS_ENTITY_RELEASED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_ENTITY_RELEASED, BoscoECSEntityReleasedClass))
#define BOSCO_ECS_IS_ENTITY_RELEASED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ENTITY_RELEASED))
#define BOSCO_ECS_IS_ENTITY_RELEASED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_ENTITY_RELEASED))
#define BOSCO_ECS_ENTITY_RELEASED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_ENTITY_RELEASED, BoscoECSEntityReleasedClass))

typedef struct _BoscoECSEntityReleased BoscoECSEntityReleased;
typedef struct _BoscoECSEntityReleasedClass BoscoECSEntityReleasedClass;

#define BOSCO_ECS_TYPE_ENTITY_CHANGED (bosco_ecs_entity_changed_get_type ())
#define BOSCO_ECS_ENTITY_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ENTITY_CHANGED, BoscoECSEntityChanged))
#define BOSCO_ECS_ENTITY_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_ENTITY_CHANGED, BoscoECSEntityChangedClass))
#define BOSCO_ECS_IS_ENTITY_CHANGED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ENTITY_CHANGED))
#define BOSCO_ECS_IS_ENTITY_CHANGED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_ENTITY_CHANGED))
#define BOSCO_ECS_ENTITY_CHANGED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_ENTITY_CHANGED, BoscoECSEntityChangedClass))

typedef struct _BoscoECSEntityChanged BoscoECSEntityChanged;
typedef struct _BoscoECSEntityChangedClass BoscoECSEntityChangedClass;

#define BOSCO_ECS_TYPE_COMPONENT_REPLACED (bosco_ecs_component_replaced_get_type ())
#define BOSCO_ECS_COMPONENT_REPLACED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_COMPONENT_REPLACED, BoscoECSComponentReplaced))
#define BOSCO_ECS_COMPONENT_REPLACED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_COMPONENT_REPLACED, BoscoECSComponentReplacedClass))
#define BOSCO_ECS_IS_COMPONENT_REPLACED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_COMPONENT_REPLACED))
#define BOSCO_ECS_IS_COMPONENT_REPLACED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_COMPONENT_REPLACED))
#define BOSCO_ECS_COMPONENT_REPLACED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_COMPONENT_REPLACED, BoscoECSComponentReplacedClass))

typedef struct _BoscoECSComponentReplaced BoscoECSComponentReplaced;
typedef struct _BoscoECSComponentReplacedClass BoscoECSComponentReplacedClass;

#define BOSCO_ECS_TYPE_WORLD_BASE (bosco_ecs_world_base_get_type ())
#define BOSCO_ECS_WORLD_BASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_WORLD_BASE, BoscoECSWorldBase))
#define BOSCO_ECS_WORLD_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_WORLD_BASE, BoscoECSWorldBaseClass))
#define BOSCO_ECS_IS_WORLD_BASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_WORLD_BASE))
#define BOSCO_ECS_IS_WORLD_BASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_WORLD_BASE))
#define BOSCO_ECS_WORLD_BASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_WORLD_BASE, BoscoECSWorldBaseClass))

typedef struct _BoscoECSWorldBase BoscoECSWorldBase;
typedef struct _BoscoECSWorldBaseClass BoscoECSWorldBaseClass;

#define BOSCO_ECS_TYPE_WORLD (bosco_ecs_world_get_type ())
#define BOSCO_ECS_WORLD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_WORLD, BoscoECSWorld))
#define BOSCO_ECS_WORLD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_WORLD, BoscoECSWorldClass))
#define BOSCO_ECS_IS_WORLD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_WORLD))
#define BOSCO_ECS_IS_WORLD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_WORLD))
#define BOSCO_ECS_WORLD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_WORLD, BoscoECSWorldClass))

typedef struct _BoscoECSWorld BoscoECSWorld;
typedef struct _BoscoECSWorldClass BoscoECSWorldClass;

#define BOSCO_ECS_TYPE_ICOMPONENT (bosco_ecs_icomponent_get_type ())
#define BOSCO_ECS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ICOMPONENT, BoscoECSIComponent))
#define BOSCO_ECS_IS_ICOMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ICOMPONENT))
#define BOSCO_ECS_ICOMPONENT_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), BOSCO_ECS_TYPE_ICOMPONENT, BoscoECSIComponentIface))

typedef struct _BoscoECSIComponent BoscoECSIComponent;
typedef struct _BoscoECSIComponentIface BoscoECSIComponentIface;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _bosco_ecs_entity_released_unref0(var) ((var == NULL) ? NULL : (var = (bosco_ecs_entity_released_unref (var), NULL)))
#define _bosco_ecs_entity_changed_unref0(var) ((var == NULL) ? NULL : (var = (bosco_ecs_entity_changed_unref (var), NULL)))
#define _bosco_ecs_component_replaced_unref0(var) ((var == NULL) ? NULL : (var = (bosco_ecs_component_replaced_unref (var), NULL)))
#define _dark_matter_unref0(var) ((var == NULL) ? NULL : (var = (dark_matter_unref (var), NULL)))

#define BOSCO_ECS_TYPE_ENTITY (bosco_ecs_entity_get_type ())
#define BOSCO_ECS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_ECS_TYPE_ENTITY, BoscoECSEntity))
#define BOSCO_ECS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_ECS_TYPE_ENTITY, BoscoECSEntityClass))
#define BOSCO_ECS_IS_ENTITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_ECS_TYPE_ENTITY))
#define BOSCO_ECS_IS_ENTITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_ECS_TYPE_ENTITY))
#define BOSCO_ECS_ENTITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_ECS_TYPE_ENTITY, BoscoECSEntityClass))

typedef struct _BoscoECSEntity BoscoECSEntity;
typedef struct _BoscoECSEntityClass BoscoECSEntityClass;
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))

struct _DarkMatter {
	GTypeInstance parent_instance;
	volatile int ref_count;
	DarkMatterPrivate * priv;
};

struct _DarkMatterClass {
	GTypeClass parent_class;
	void (*finalize) (DarkMatter *self);
};

struct _BoscoECSEntityBase {
	DarkMatter parent_instance;
	BoscoECSEntityBasePrivate * priv;
	gint db_id;
	gint ic;
};

struct _BoscoECSEntityBaseClass {
	DarkMatterClass parent_class;
};

struct _BoscoECSIComponentIface {
	GTypeInterface parent_iface;
};

struct _BoscoECSEntityBasePrivate {
	gint _creationIndex;
	gchar* _name;
	gchar* _id;
	gboolean _isEnabled;
	gint _refCount;
	BoscoECSEntityReleased* _onEntityReleased;
	BoscoECSEntityChanged* _onComponentAdded;
	BoscoECSEntityChanged* _onComponentRemoved;
	BoscoECSComponentReplaced* _onComponentReplaced;
	BoscoECSWorld* _world;
	gchar* _toStringCache;
	BoscoECSIComponent** _componentsCache;
	gint _componentsCache_length1;
	gint __componentsCache_size_;
	gint* _componentIndicesCache;
	gint _componentIndicesCache_length1;
	gint __componentIndicesCache_size_;
	gchar** _componentsEnum;
	gint _componentsEnum_length1;
	gint __componentsEnum_size_;
	gint _totalComponents;
	gint _componentCount;
};

typedef enum  {
	BOSCO_ECS_ECS_EXCEPTION_EntityIsNotEnabled,
	BOSCO_ECS_ECS_EXCEPTION_EntityAlreadyHasComponent,
	BOSCO_ECS_ECS_EXCEPTION_EntityDoesNotHaveComponent,
	BOSCO_ECS_ECS_EXCEPTION_EntityIsAlreadyReleased,
	BOSCO_ECS_ECS_EXCEPTION_SingleEntity,
	BOSCO_ECS_ECS_EXCEPTION_Matcher,
	BOSCO_ECS_ECS_EXCEPTION_WorldDoesNotContainEntity
} BoscoECSEcsException;
#define BOSCO_ECS_ECS_EXCEPTION bosco_ecs_ecs_exception_quark ()

static gpointer bosco_ecs_entity_base_parent_class = NULL;
extern gint bosco_ecs_entity_base_instanceIndex;
gint bosco_ecs_entity_base_instanceIndex = 0;
extern gint bosco_ecs_entity_base_size;
gint bosco_ecs_entity_base_size = 0;
extern gboolean bosco_ecs_entity_base_first;
gboolean bosco_ecs_entity_base_first = TRUE;
extern gint bosco_ecs_entity_base_maxEntities;
gint bosco_ecs_entity_base_maxEntities = 128;
extern gint bosco_ecs_entity_base_incEntities;
gint bosco_ecs_entity_base_incEntities = 64;
extern gint bosco_ecs_entity_base_db_index;
gint bosco_ecs_entity_base_db_index = 0;
static BoscoECSIComponent** bosco_ecs_entity_base__components;
static gint bosco_ecs_entity_base__components_length1;
static BoscoECSIComponent** bosco_ecs_entity_base__components = NULL;
static gint bosco_ecs_entity_base__components_length1 = 0;
static gint _bosco_ecs_entity_base__components_size_ = 0;
extern BoscoECSWorld* bosco_ecs_world_instance;

gpointer dark_matter_ref (gpointer instance);
void dark_matter_unref (gpointer instance);
GParamSpec* param_spec_dark_matter (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_dark_matter (GValue* value, gpointer v_object);
void value_take_dark_matter (GValue* value, gpointer v_object);
gpointer value_get_dark_matter (const GValue* value);
GType dark_matter_get_type (void) G_GNUC_CONST;
GType bosco_ecs_entity_base_get_type (void) G_GNUC_CONST;
gpointer bosco_ecs_entity_released_ref (gpointer instance);
void bosco_ecs_entity_released_unref (gpointer instance);
GParamSpec* bosco_ecs_param_spec_entity_released (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void bosco_ecs_value_set_entity_released (GValue* value, gpointer v_object);
void bosco_ecs_value_take_entity_released (GValue* value, gpointer v_object);
gpointer bosco_ecs_value_get_entity_released (const GValue* value);
GType bosco_ecs_entity_released_get_type (void) G_GNUC_CONST;
gpointer bosco_ecs_entity_changed_ref (gpointer instance);
void bosco_ecs_entity_changed_unref (gpointer instance);
GParamSpec* bosco_ecs_param_spec_entity_changed (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void bosco_ecs_value_set_entity_changed (GValue* value, gpointer v_object);
void bosco_ecs_value_take_entity_changed (GValue* value, gpointer v_object);
gpointer bosco_ecs_value_get_entity_changed (const GValue* value);
GType bosco_ecs_entity_changed_get_type (void) G_GNUC_CONST;
gpointer bosco_ecs_component_replaced_ref (gpointer instance);
void bosco_ecs_component_replaced_unref (gpointer instance);
GParamSpec* bosco_ecs_param_spec_component_replaced (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void bosco_ecs_value_set_component_replaced (GValue* value, gpointer v_object);
void bosco_ecs_value_take_component_replaced (GValue* value, gpointer v_object);
gpointer bosco_ecs_value_get_component_replaced (const GValue* value);
GType bosco_ecs_component_replaced_get_type (void) G_GNUC_CONST;
GType bosco_ecs_world_base_get_type (void) G_GNUC_CONST;
GType bosco_ecs_world_get_type (void) G_GNUC_CONST;
GType bosco_ecs_icomponent_get_type (void) G_GNUC_CONST;
#define BOSCO_ECS_ENTITY_BASE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), BOSCO_ECS_TYPE_ENTITY_BASE, BoscoECSEntityBasePrivate))
enum  {
	BOSCO_ECS_ENTITY_BASE_DUMMY_PROPERTY
};
BoscoECSEntityBase* bosco_ecs_entity_base_construct (GType object_type, gchar** componentsEnum, int componentsEnum_length1, gint totalComponents);
DarkMatter* dark_matter_new (void);
DarkMatter* dark_matter_construct (GType object_type);
BoscoECSEntityReleased* bosco_ecs_entity_released_new (void);
BoscoECSEntityReleased* bosco_ecs_entity_released_construct (GType object_type);
BoscoECSEntityChanged* bosco_ecs_entity_changed_new (void);
BoscoECSEntityChanged* bosco_ecs_entity_changed_construct (GType object_type);
BoscoECSComponentReplaced* bosco_ecs_component_replaced_new (void);
BoscoECSComponentReplaced* bosco_ecs_component_replaced_construct (GType object_type);
void bosco_ecs_entity_base_initialize (BoscoECSEntityBase* self, const gchar* name, const gchar* id, gint creationIndex);
GType bosco_ecs_entity_get_type (void) G_GNUC_CONST;
BoscoECSEntity* bosco_ecs_entity_base_addRef (BoscoECSEntityBase* self);
GQuark bosco_ecs_ecs_exception_quark (void);
BoscoECSEntity* bosco_ecs_entity_base_addComponent (BoscoECSEntityBase* self, gint index, BoscoECSIComponent* component, GError** error);
gboolean bosco_ecs_entity_base_hasComponent (BoscoECSEntityBase* self, gint index);
void bosco_ecs_entity_changed_dispatch (BoscoECSEntityChanged* self, BoscoECSEntity* e, gint index, BoscoECSIComponent* component);
BoscoECSEntity* bosco_ecs_entity_base_removeComponent (BoscoECSEntityBase* self, gint index, GError** error);
static void _bosco_ecs_entity_base_replaceComponent (BoscoECSEntityBase* self, gint index, BoscoECSIComponent* replacement);
BoscoECSEntity* bosco_ecs_entity_base_replaceComponent (BoscoECSEntityBase* self, gint index, BoscoECSIComponent* component, GError** error);
void bosco_ecs_component_replaced_dispatch (BoscoECSComponentReplaced* self, BoscoECSEntity* e, gint index, BoscoECSIComponent* component, BoscoECSIComponent* replacement);
BoscoECSIComponent* bosco_ecs_entity_base_getComponent (BoscoECSEntityBase* self, gint index, GError** error);
BoscoECSIComponent** bosco_ecs_entity_base_getComponents (BoscoECSEntityBase* self, int* result_length1);
static void _vala_array_add2 (BoscoECSIComponent*** array, int* length, int* size, BoscoECSIComponent* value);
static BoscoECSIComponent** _vala_array_dup1 (BoscoECSIComponent** self, int length);
static BoscoECSIComponent** _vala_array_dup2 (BoscoECSIComponent** self, int length);
gint* bosco_ecs_entity_base_getComponentIndices (BoscoECSEntityBase* self, int* result_length1);
static void _vala_array_add3 (gint** array, int* length, int* size, gint value);
static gint* _vala_array_dup3 (gint* self, int length);
static gint* _vala_array_dup4 (gint* self, int length);
gboolean bosco_ecs_entity_base_hasComponents (BoscoECSEntityBase* self, gint* indices, int indices_length1);
gboolean bosco_ecs_entity_base_hasAnyComponent (BoscoECSEntityBase* self, gint* indices, int indices_length1);
void bosco_ecs_entity_base_removeAllComponents (BoscoECSEntityBase* self);
void bosco_ecs_entity_base_destroy (BoscoECSEntityBase* self);
void bosco_ecs_entity_changed_clear (BoscoECSEntityChanged* self);
void bosco_ecs_component_replaced_clear (BoscoECSComponentReplaced* self);
gchar* bosco_ecs_entity_base_toString (BoscoECSEntityBase* self);
void bosco_ecs_entity_base_release (BoscoECSEntityBase* self, GError** error);
void bosco_ecs_entity_released_dispatch (BoscoECSEntityReleased* self, BoscoECSEntity* e);
const gchar* bosco_ecs_entity_base_get_id (BoscoECSEntityBase* self);
const gchar* bosco_ecs_entity_base_get_name (BoscoECSEntityBase* self);
gint bosco_ecs_entity_base_get_creationIndex (BoscoECSEntityBase* self);
gboolean bosco_ecs_entity_base_get_isEnabled (BoscoECSEntityBase* self);
gint bosco_ecs_entity_base_get_refCount (BoscoECSEntityBase* self);
BoscoECSEntityReleased* bosco_ecs_entity_base_get_onEntityReleased (BoscoECSEntityBase* self);
BoscoECSEntityChanged* bosco_ecs_entity_base_get_onComponentAdded (BoscoECSEntityBase* self);
BoscoECSEntityChanged* bosco_ecs_entity_base_get_onComponentRemoved (BoscoECSEntityBase* self);
BoscoECSComponentReplaced* bosco_ecs_entity_base_get_onComponentReplaced (BoscoECSEntityBase* self);
static void bosco_ecs_entity_base_finalize (DarkMatter* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


/**
         * The basic game object. Everything is an entity with components that
         * are added / removed as needed.
         *
         * @param Object componentsEnum
         * @param number totalComponents
         * @constructor
         */
static gpointer _dark_matter_ref0 (gpointer self) {
	return self ? dark_matter_ref (self) : NULL;
}


BoscoECSEntityBase* bosco_ecs_entity_base_construct (GType object_type, gchar** componentsEnum, int componentsEnum_length1, gint totalComponents) {
	BoscoECSEntityBase* self = NULL;
	gint _tmp0_ = 0;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gboolean _tmp2_ = FALSE;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	gint _tmp13_ = 0;
	gint _tmp14_ = 0;
	gint _tmp15_ = 0;
	BoscoECSEntityReleased* _tmp16_ = NULL;
	BoscoECSEntityChanged* _tmp17_ = NULL;
	BoscoECSEntityChanged* _tmp18_ = NULL;
	BoscoECSComponentReplaced* _tmp19_ = NULL;
	gint _tmp20_ = 0;
	gint* _tmp21_ = NULL;
	gchar** _tmp22_ = NULL;
	gint _tmp22__length1 = 0;
	BoscoECSWorld* _tmp23_ = NULL;
	BoscoECSWorld* _tmp24_ = NULL;
	self = (BoscoECSEntityBase*) dark_matter_construct (object_type);
	_tmp0_ = totalComponents;
	self->priv->_totalComponents = _tmp0_;
	_tmp1_ = componentsEnum;
	_tmp1__length1 = componentsEnum_length1;
	self->priv->_componentCount = _tmp1__length1;
	_tmp2_ = bosco_ecs_entity_base_first;
	if (_tmp2_) {
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		BoscoECSIComponent** _tmp5_ = NULL;
		_tmp3_ = self->priv->_componentCount;
		_tmp4_ = bosco_ecs_entity_base_maxEntities;
		_tmp5_ = g_new0 (BoscoECSIComponent*, (_tmp3_ * _tmp4_) + 1);
		bosco_ecs_entity_base__components = (_vala_array_free (bosco_ecs_entity_base__components, bosco_ecs_entity_base__components_length1, (GDestroyNotify) dark_matter_unref), NULL);
		bosco_ecs_entity_base__components = _tmp5_;
		bosco_ecs_entity_base__components_length1 = _tmp3_ * _tmp4_;
		_bosco_ecs_entity_base__components_size_ = bosco_ecs_entity_base__components_length1;
		bosco_ecs_entity_base_first = FALSE;
	}
	_tmp6_ = bosco_ecs_entity_base_db_index;
	_tmp7_ = bosco_ecs_entity_base_maxEntities;
	if (_tmp6_ >= _tmp7_) {
		gint _tmp8_ = 0;
		gint _tmp9_ = 0;
		gint _tmp10_ = 0;
		gint _tmp11_ = 0;
		gint _tmp12_ = 0;
		_tmp8_ = bosco_ecs_entity_base_maxEntities;
		_tmp9_ = bosco_ecs_entity_base_incEntities;
		bosco_ecs_entity_base_maxEntities = _tmp8_ + _tmp9_;
		_tmp10_ = self->priv->_componentCount;
		_tmp11_ = bosco_ecs_entity_base_maxEntities;
		_tmp12_ = _tmp10_ * _tmp11_;
		bosco_ecs_entity_base__components = g_renew (BoscoECSIComponent*, bosco_ecs_entity_base__components, _tmp10_ * _tmp11_);
		(_tmp12_ > bosco_ecs_entity_base__components_length1) ? memset (bosco_ecs_entity_base__components + bosco_ecs_entity_base__components_length1, 0, sizeof (BoscoECSIComponent*) * (_tmp12_ - bosco_ecs_entity_base__components_length1)) : NULL;
		bosco_ecs_entity_base__components_length1 = _tmp12_;
		_bosco_ecs_entity_base__components_size_ = _tmp12_;
	}
	_tmp13_ = bosco_ecs_entity_base_db_index;
	bosco_ecs_entity_base_db_index = _tmp13_ + 1;
	self->db_id = _tmp13_;
	_tmp14_ = self->db_id;
	_tmp15_ = self->priv->_componentCount;
	self->ic = _tmp14_ * _tmp15_;
	_tmp16_ = bosco_ecs_entity_released_new ();
	_bosco_ecs_entity_released_unref0 (self->priv->_onEntityReleased);
	self->priv->_onEntityReleased = _tmp16_;
	_tmp17_ = bosco_ecs_entity_changed_new ();
	_bosco_ecs_entity_changed_unref0 (self->priv->_onComponentAdded);
	self->priv->_onComponentAdded = _tmp17_;
	_tmp18_ = bosco_ecs_entity_changed_new ();
	_bosco_ecs_entity_changed_unref0 (self->priv->_onComponentRemoved);
	self->priv->_onComponentRemoved = _tmp18_;
	_tmp19_ = bosco_ecs_component_replaced_new ();
	_bosco_ecs_component_replaced_unref0 (self->priv->_onComponentReplaced);
	self->priv->_onComponentReplaced = _tmp19_;
	_tmp20_ = totalComponents;
	_tmp21_ = g_new0 (gint, _tmp20_);
	self->priv->_componentIndicesCache = (g_free (self->priv->_componentIndicesCache), NULL);
	self->priv->_componentIndicesCache = _tmp21_;
	self->priv->_componentIndicesCache_length1 = _tmp20_;
	self->priv->__componentIndicesCache_size_ = self->priv->_componentIndicesCache_length1;
	_tmp22_ = componentsEnum;
	_tmp22__length1 = componentsEnum_length1;
	self->priv->_componentsEnum = _tmp22_;
	self->priv->_componentsEnum_length1 = _tmp22__length1;
	self->priv->__componentsEnum_size_ = self->priv->_componentsEnum_length1;
	_tmp23_ = bosco_ecs_world_instance;
	_tmp24_ = _dark_matter_ref0 (_tmp23_);
	_dark_matter_unref0 (self->priv->_world);
	self->priv->_world = _tmp24_;
	return self;
}


/**
         * Initialize the entity after allocation from the pool
         *
         * @param string  name
         * @param string  id
         * @param int creationIndex
         */
void bosco_ecs_entity_base_initialize (BoscoECSEntityBase* self, const gchar* name, const gchar* id, gint creationIndex) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	BoscoECSEntity* _tmp5_ = NULL;
	BoscoECSEntity* _tmp6_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (name != NULL);
	g_return_if_fail (id != NULL);
	_tmp0_ = name;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_name);
	self->priv->_name = _tmp1_;
	_tmp2_ = creationIndex;
	self->priv->_creationIndex = _tmp2_;
	self->priv->_isEnabled = TRUE;
	_tmp3_ = id;
	_tmp4_ = g_strdup (_tmp3_);
	_g_free0 (self->priv->_id);
	self->priv->_id = _tmp4_;
	_tmp5_ = bosco_ecs_entity_base_addRef (self);
	_tmp6_ = _tmp5_;
	_dark_matter_unref0 (_tmp6_);
}


/**
          * AddComponent
          *
          * @param number index
          * @param entitas.IComponent component
          * @returns entitas.Entity
          */
BoscoECSEntity* bosco_ecs_entity_base_addComponent (BoscoECSEntityBase* self, gint index, BoscoECSIComponent* component, GError** error) {
	BoscoECSEntity* result = NULL;
	gboolean _tmp0_ = FALSE;
	gint _tmp2_ = 0;
	gboolean _tmp3_ = FALSE;
	BoscoECSIComponent** _tmp9_ = NULL;
	gint _tmp9__length1 = 0;
	gint _tmp10_ = 0;
	gint _tmp11_ = 0;
	BoscoECSIComponent* _tmp12_ = NULL;
	BoscoECSIComponent* _tmp13_ = NULL;
	BoscoECSIComponent* _tmp14_ = NULL;
	BoscoECSEntityChanged* _tmp15_ = NULL;
	gint _tmp16_ = 0;
	BoscoECSIComponent* _tmp17_ = NULL;
	BoscoECSEntity* _tmp18_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (component != NULL, NULL);
	_tmp0_ = self->priv->_isEnabled;
	if (!_tmp0_) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (BOSCO_ECS_ECS_EXCEPTION, BOSCO_ECS_ECS_EXCEPTION_EntityIsNotEnabled, "Cannot add component!");
		_inner_error_ = _tmp1_;
		if (_inner_error_->domain == BOSCO_ECS_ECS_EXCEPTION) {
			g_propagate_error (error, _inner_error_);
			return NULL;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp2_ = index;
	_tmp3_ = bosco_ecs_entity_base_hasComponent (self, _tmp2_);
	if (_tmp3_) {
		gchar** _tmp4_ = NULL;
		gint _tmp4__length1 = 0;
		gint _tmp5_ = 0;
		const gchar* _tmp6_ = NULL;
		gint _tmp7_ = 0;
		GError* _tmp8_ = NULL;
		_tmp4_ = self->priv->_componentsEnum;
		_tmp4__length1 = self->priv->_componentsEnum_length1;
		_tmp5_ = index;
		_tmp6_ = _tmp4_[_tmp5_];
		_tmp7_ = index;
		_tmp8_ = g_error_new (BOSCO_ECS_ECS_EXCEPTION, BOSCO_ECS_ECS_EXCEPTION_EntityAlreadyHasComponent, "Cannot add %s at index %d", _tmp6_, _tmp7_);
		_inner_error_ = _tmp8_;
		if (_inner_error_->domain == BOSCO_ECS_ECS_EXCEPTION) {
			g_propagate_error (error, _inner_error_);
			return NULL;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp9_ = bosco_ecs_entity_base__components;
	_tmp9__length1 = bosco_ecs_entity_base__components_length1;
	_tmp10_ = self->ic;
	_tmp11_ = index;
	_tmp12_ = component;
	_tmp13_ = _dark_matter_ref0 (_tmp12_);
	_dark_matter_unref0 (_tmp9_[_tmp10_ + _tmp11_]);
	_tmp9_[_tmp10_ + _tmp11_] = _tmp13_;
	_tmp14_ = _tmp9_[_tmp10_ + _tmp11_];
	self->priv->_componentsCache = (_vala_array_free (self->priv->_componentsCache, self->priv->_componentsCache_length1, (GDestroyNotify) dark_matter_unref), NULL);
	self->priv->_componentsCache = NULL;
	self->priv->_componentsCache_length1 = 0;
	self->priv->__componentsCache_size_ = self->priv->_componentsCache_length1;
	self->priv->_componentIndicesCache = (g_free (self->priv->_componentIndicesCache), NULL);
	self->priv->_componentIndicesCache = NULL;
	self->priv->_componentIndicesCache_length1 = 0;
	self->priv->__componentIndicesCache_size_ = self->priv->_componentIndicesCache_length1;
	_g_free0 (self->priv->_toStringCache);
	self->priv->_toStringCache = NULL;
	_tmp15_ = self->priv->_onComponentAdded;
	_tmp16_ = index;
	_tmp17_ = component;
	bosco_ecs_entity_changed_dispatch (_tmp15_, G_TYPE_CHECK_INSTANCE_CAST (self, BOSCO_ECS_TYPE_ENTITY, BoscoECSEntity), _tmp16_, _tmp17_);
	_tmp18_ = _dark_matter_ref0 (G_TYPE_CHECK_INSTANCE_CAST (self, BOSCO_ECS_TYPE_ENTITY, BoscoECSEntity));
	result = _tmp18_;
	return result;
}


/**
         * RemoveComponent
         *
         * @param number index
         * @returns entitas.Entity
         */
BoscoECSEntity* bosco_ecs_entity_base_removeComponent (BoscoECSEntityBase* self, gint index, GError** error) {
	BoscoECSEntity* result = NULL;
	gboolean _tmp0_ = FALSE;
	gint _tmp2_ = 0;
	gboolean _tmp3_ = FALSE;
	gint _tmp9_ = 0;
	BoscoECSEntity* _tmp10_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_isEnabled;
	if (!_tmp0_) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (BOSCO_ECS_ECS_EXCEPTION, BOSCO_ECS_ECS_EXCEPTION_EntityIsNotEnabled, "Cannot remove component!");
		_inner_error_ = _tmp1_;
		if (_inner_error_->domain == BOSCO_ECS_ECS_EXCEPTION) {
			g_propagate_error (error, _inner_error_);
			return NULL;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp2_ = index;
	_tmp3_ = bosco_ecs_entity_base_hasComponent (self, _tmp2_);
	if (!_tmp3_) {
		gchar** _tmp4_ = NULL;
		gint _tmp4__length1 = 0;
		gint _tmp5_ = 0;
		const gchar* _tmp6_ = NULL;
		gint _tmp7_ = 0;
		GError* _tmp8_ = NULL;
		_tmp4_ = self->priv->_componentsEnum;
		_tmp4__length1 = self->priv->_componentsEnum_length1;
		_tmp5_ = index;
		_tmp6_ = _tmp4_[_tmp5_];
		_tmp7_ = index;
		_tmp8_ = g_error_new (BOSCO_ECS_ECS_EXCEPTION, BOSCO_ECS_ECS_EXCEPTION_EntityDoesNotHaveComponent, "Cannot remove %s at index %d", _tmp6_, _tmp7_);
		_inner_error_ = _tmp8_;
		if (_inner_error_->domain == BOSCO_ECS_ECS_EXCEPTION) {
			g_propagate_error (error, _inner_error_);
			return NULL;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp9_ = index;
	_bosco_ecs_entity_base_replaceComponent (self, _tmp9_, NULL);
	_tmp10_ = _dark_matter_ref0 (G_TYPE_CHECK_INSTANCE_CAST (self, BOSCO_ECS_TYPE_ENTITY, BoscoECSEntity));
	result = _tmp10_;
	return result;
}


/**
         * ReplaceComponent
         *
         * @param number index
         * @param entitas.IComponent component
         * @returns entitas.Entity
         */
BoscoECSEntity* bosco_ecs_entity_base_replaceComponent (BoscoECSEntityBase* self, gint index, BoscoECSIComponent* component, GError** error) {
	BoscoECSEntity* result = NULL;
	gboolean _tmp0_ = FALSE;
	gint _tmp2_ = 0;
	gboolean _tmp3_ = FALSE;
	BoscoECSEntity* _tmp11_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (component != NULL, NULL);
	_tmp0_ = self->priv->_isEnabled;
	if (!_tmp0_) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (BOSCO_ECS_ECS_EXCEPTION, BOSCO_ECS_ECS_EXCEPTION_EntityIsNotEnabled, "Cannot replace component!");
		_inner_error_ = _tmp1_;
		if (_inner_error_->domain == BOSCO_ECS_ECS_EXCEPTION) {
			g_propagate_error (error, _inner_error_);
			return NULL;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp2_ = index;
	_tmp3_ = bosco_ecs_entity_base_hasComponent (self, _tmp2_);
	if (_tmp3_) {
		gint _tmp4_ = 0;
		BoscoECSIComponent* _tmp5_ = NULL;
		_tmp4_ = index;
		_tmp5_ = component;
		_bosco_ecs_entity_base_replaceComponent (self, _tmp4_, _tmp5_);
	} else {
		BoscoECSIComponent* _tmp6_ = NULL;
		_tmp6_ = component;
		if (_tmp6_ != NULL) {
			gint _tmp7_ = 0;
			BoscoECSIComponent* _tmp8_ = NULL;
			BoscoECSEntity* _tmp9_ = NULL;
			BoscoECSEntity* _tmp10_ = NULL;
			_tmp7_ = index;
			_tmp8_ = component;
			_tmp9_ = bosco_ecs_entity_base_addComponent (self, _tmp7_, _tmp8_, &_inner_error_);
			_tmp10_ = _tmp9_;
			_dark_matter_unref0 (_tmp10_);
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				if (_inner_error_->domain == BOSCO_ECS_ECS_EXCEPTION) {
					g_propagate_error (error, _inner_error_);
					return NULL;
				} else {
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return NULL;
				}
			}
		}
	}
	_tmp11_ = _dark_matter_ref0 (G_TYPE_CHECK_INSTANCE_CAST (self, BOSCO_ECS_TYPE_ENTITY, BoscoECSEntity));
	result = _tmp11_;
	return result;
}


static void _bosco_ecs_entity_base_replaceComponent (BoscoECSEntityBase* self, gint index, BoscoECSIComponent* replacement) {
	BoscoECSIComponent* previousComponent = NULL;
	BoscoECSIComponent** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	BoscoECSIComponent* _tmp3_ = NULL;
	BoscoECSIComponent* _tmp4_ = NULL;
	BoscoECSIComponent* _tmp5_ = NULL;
	BoscoECSIComponent* _tmp6_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = bosco_ecs_entity_base__components;
	_tmp0__length1 = bosco_ecs_entity_base__components_length1;
	_tmp1_ = self->ic;
	_tmp2_ = index;
	_tmp3_ = _tmp0_[_tmp1_ + _tmp2_];
	_tmp4_ = _dark_matter_ref0 (_tmp3_);
	previousComponent = _tmp4_;
	_tmp5_ = previousComponent;
	_tmp6_ = replacement;
	if (_tmp5_ == _tmp6_) {
		BoscoECSComponentReplaced* _tmp7_ = NULL;
		gint _tmp8_ = 0;
		BoscoECSIComponent* _tmp9_ = NULL;
		BoscoECSIComponent* _tmp10_ = NULL;
		_tmp7_ = self->priv->_onComponentReplaced;
		_tmp8_ = index;
		_tmp9_ = previousComponent;
		_tmp10_ = replacement;
		bosco_ecs_component_replaced_dispatch (_tmp7_, G_TYPE_CHECK_INSTANCE_CAST (self, BOSCO_ECS_TYPE_ENTITY, BoscoECSEntity), _tmp8_, _tmp9_, _tmp10_);
	} else {
		BoscoECSIComponent** _tmp11_ = NULL;
		gint _tmp11__length1 = 0;
		gint _tmp12_ = 0;
		gint _tmp13_ = 0;
		BoscoECSIComponent* _tmp14_ = NULL;
		BoscoECSIComponent* _tmp15_ = NULL;
		BoscoECSIComponent* _tmp16_ = NULL;
		BoscoECSIComponent* _tmp17_ = NULL;
		_tmp11_ = bosco_ecs_entity_base__components;
		_tmp11__length1 = bosco_ecs_entity_base__components_length1;
		_tmp12_ = self->ic;
		_tmp13_ = index;
		_tmp14_ = replacement;
		_tmp15_ = _dark_matter_ref0 (_tmp14_);
		_dark_matter_unref0 (_tmp11_[_tmp12_ + _tmp13_]);
		_tmp11_[_tmp12_ + _tmp13_] = _tmp15_;
		_tmp16_ = _tmp11_[_tmp12_ + _tmp13_];
		self->priv->_componentsCache = (_vala_array_free (self->priv->_componentsCache, self->priv->_componentsCache_length1, (GDestroyNotify) dark_matter_unref), NULL);
		self->priv->_componentsCache = NULL;
		self->priv->_componentsCache_length1 = 0;
		self->priv->__componentsCache_size_ = self->priv->_componentsCache_length1;
		_tmp17_ = replacement;
		if (_tmp17_ == NULL) {
			BoscoECSIComponent** _tmp18_ = NULL;
			gint _tmp18__length1 = 0;
			gint _tmp19_ = 0;
			gint _tmp20_ = 0;
			BoscoECSIComponent* _tmp21_ = NULL;
			BoscoECSEntityChanged* _tmp22_ = NULL;
			gint _tmp23_ = 0;
			BoscoECSIComponent* _tmp24_ = NULL;
			_tmp18_ = bosco_ecs_entity_base__components;
			_tmp18__length1 = bosco_ecs_entity_base__components_length1;
			_tmp19_ = self->ic;
			_tmp20_ = index;
			_dark_matter_unref0 (_tmp18_[_tmp19_ + _tmp20_]);
			_tmp18_[_tmp19_ + _tmp20_] = NULL;
			_tmp21_ = _tmp18_[_tmp19_ + _tmp20_];
			self->priv->_componentIndicesCache = (g_free (self->priv->_componentIndicesCache), NULL);
			self->priv->_componentIndicesCache = NULL;
			self->priv->_componentIndicesCache_length1 = 0;
			self->priv->__componentIndicesCache_size_ = self->priv->_componentIndicesCache_length1;
			_g_free0 (self->priv->_toStringCache);
			self->priv->_toStringCache = NULL;
			_tmp22_ = self->priv->_onComponentRemoved;
			_tmp23_ = index;
			_tmp24_ = previousComponent;
			bosco_ecs_entity_changed_dispatch (_tmp22_, G_TYPE_CHECK_INSTANCE_CAST (self, BOSCO_ECS_TYPE_ENTITY, BoscoECSEntity), _tmp23_, _tmp24_);
		} else {
			BoscoECSComponentReplaced* _tmp25_ = NULL;
			gint _tmp26_ = 0;
			BoscoECSIComponent* _tmp27_ = NULL;
			BoscoECSIComponent* _tmp28_ = NULL;
			_tmp25_ = self->priv->_onComponentReplaced;
			_tmp26_ = index;
			_tmp27_ = previousComponent;
			_tmp28_ = replacement;
			bosco_ecs_component_replaced_dispatch (_tmp25_, G_TYPE_CHECK_INSTANCE_CAST (self, BOSCO_ECS_TYPE_ENTITY, BoscoECSEntity), _tmp26_, _tmp27_, _tmp28_);
		}
	}
	_dark_matter_unref0 (previousComponent);
}


/**
         * GetComponent
         *
         * @param number index
         * @param entitas.IComponent component
         */
BoscoECSIComponent* bosco_ecs_entity_base_getComponent (BoscoECSEntityBase* self, gint index, GError** error) {
	BoscoECSIComponent* result = NULL;
	gint _tmp0_ = 0;
	gboolean _tmp1_ = FALSE;
	BoscoECSIComponent** _tmp7_ = NULL;
	gint _tmp7__length1 = 0;
	gint _tmp8_ = 0;
	gint _tmp9_ = 0;
	BoscoECSIComponent* _tmp10_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = index;
	_tmp1_ = bosco_ecs_entity_base_hasComponent (self, _tmp0_);
	if (!_tmp1_) {
		gchar** _tmp2_ = NULL;
		gint _tmp2__length1 = 0;
		gint _tmp3_ = 0;
		const gchar* _tmp4_ = NULL;
		gint _tmp5_ = 0;
		GError* _tmp6_ = NULL;
		_tmp2_ = self->priv->_componentsEnum;
		_tmp2__length1 = self->priv->_componentsEnum_length1;
		_tmp3_ = index;
		_tmp4_ = _tmp2_[_tmp3_];
		_tmp5_ = index;
		_tmp6_ = g_error_new (BOSCO_ECS_ECS_EXCEPTION, BOSCO_ECS_ECS_EXCEPTION_EntityDoesNotHaveComponent, "Cannot get %s at index %d", _tmp4_, _tmp5_);
		_inner_error_ = _tmp6_;
		if (_inner_error_->domain == BOSCO_ECS_ECS_EXCEPTION) {
			g_propagate_error (error, _inner_error_);
			return NULL;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp7_ = bosco_ecs_entity_base__components;
	_tmp7__length1 = bosco_ecs_entity_base__components_length1;
	_tmp8_ = self->ic;
	_tmp9_ = index;
	_tmp10_ = _tmp7_[_tmp8_ + _tmp9_];
	result = _tmp10_;
	return result;
}


/**
         * GetComponents
         *
         * @returns Array<entitas.IComponent>
         */
static void _vala_array_add2 (BoscoECSIComponent*** array, int* length, int* size, BoscoECSIComponent* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (BoscoECSIComponent*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static BoscoECSIComponent** _vala_array_dup1 (BoscoECSIComponent** self, int length) {
	BoscoECSIComponent** result;
	int i;
	result = g_new0 (BoscoECSIComponent*, length + 1);
	for (i = 0; i < length; i++) {
		BoscoECSIComponent* _tmp0_ = NULL;
		_tmp0_ = _dark_matter_ref0 (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


static BoscoECSIComponent** _vala_array_dup2 (BoscoECSIComponent** self, int length) {
	BoscoECSIComponent** result;
	int i;
	result = g_new0 (BoscoECSIComponent*, length + 1);
	for (i = 0; i < length; i++) {
		BoscoECSIComponent* _tmp0_ = NULL;
		_tmp0_ = _dark_matter_ref0 (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


BoscoECSIComponent** bosco_ecs_entity_base_getComponents (BoscoECSEntityBase* self, int* result_length1) {
	BoscoECSIComponent** result = NULL;
	BoscoECSIComponent** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	BoscoECSIComponent** _tmp17_ = NULL;
	gint _tmp17__length1 = 0;
	BoscoECSIComponent** _tmp18_ = NULL;
	gint _tmp18__length1 = 0;
	BoscoECSIComponent** _tmp19_ = NULL;
	gint _tmp19__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_componentsCache;
	_tmp0__length1 = self->priv->_componentsCache_length1;
	if (_tmp0_ == NULL) {
		BoscoECSIComponent** components = NULL;
		BoscoECSIComponent** _tmp1_ = NULL;
		gint components_length1 = 0;
		gint _components_size_ = 0;
		BoscoECSIComponent** _tmp15_ = NULL;
		gint _tmp15__length1 = 0;
		BoscoECSIComponent** _tmp16_ = NULL;
		gint _tmp16__length1 = 0;
		_tmp1_ = g_new0 (BoscoECSIComponent*, 0 + 1);
		components = _tmp1_;
		components_length1 = 0;
		_components_size_ = components_length1;
		{
			gint i = 0;
			gint _tmp2_ = 0;
			_tmp2_ = self->ic;
			i = _tmp2_;
			{
				gboolean _tmp3_ = FALSE;
				_tmp3_ = TRUE;
				while (TRUE) {
					gint _tmp5_ = 0;
					gint _tmp6_ = 0;
					BoscoECSIComponent** _tmp7_ = NULL;
					gint _tmp7__length1 = 0;
					gint _tmp8_ = 0;
					BoscoECSIComponent* _tmp9_ = NULL;
					if (!_tmp3_) {
						gint _tmp4_ = 0;
						_tmp4_ = i;
						i = _tmp4_ + 1;
					}
					_tmp3_ = FALSE;
					_tmp5_ = self->ic;
					_tmp6_ = self->priv->_componentCount;
					if (!(i <= ((_tmp5_ + _tmp6_) - 1))) {
						break;
					}
					_tmp7_ = bosco_ecs_entity_base__components;
					_tmp7__length1 = bosco_ecs_entity_base__components_length1;
					_tmp8_ = i;
					_tmp9_ = _tmp7_[_tmp8_];
					if (_tmp9_ != NULL) {
						BoscoECSIComponent** _tmp10_ = NULL;
						gint _tmp10__length1 = 0;
						BoscoECSIComponent** _tmp11_ = NULL;
						gint _tmp11__length1 = 0;
						gint _tmp12_ = 0;
						BoscoECSIComponent* _tmp13_ = NULL;
						BoscoECSIComponent* _tmp14_ = NULL;
						_tmp10_ = components;
						_tmp10__length1 = components_length1;
						_tmp11_ = bosco_ecs_entity_base__components;
						_tmp11__length1 = bosco_ecs_entity_base__components_length1;
						_tmp12_ = i;
						_tmp13_ = _tmp11_[_tmp12_];
						_tmp14_ = _dark_matter_ref0 (_tmp13_);
						_vala_array_add2 (&components, &components_length1, &_components_size_, _tmp14_);
					}
				}
			}
		}
		_tmp15_ = components;
		_tmp15__length1 = components_length1;
		_tmp16_ = (_tmp15_ != NULL) ? _vala_array_dup1 (_tmp15_, _tmp15__length1) : ((gpointer) _tmp15_);
		_tmp16__length1 = _tmp15__length1;
		self->priv->_componentsCache = (_vala_array_free (self->priv->_componentsCache, self->priv->_componentsCache_length1, (GDestroyNotify) dark_matter_unref), NULL);
		self->priv->_componentsCache = _tmp16_;
		self->priv->_componentsCache_length1 = _tmp16__length1;
		self->priv->__componentsCache_size_ = self->priv->_componentsCache_length1;
		components = (_vala_array_free (components, components_length1, (GDestroyNotify) dark_matter_unref), NULL);
	}
	_tmp17_ = self->priv->_componentsCache;
	_tmp17__length1 = self->priv->_componentsCache_length1;
	_tmp18_ = (_tmp17_ != NULL) ? _vala_array_dup2 (_tmp17_, _tmp17__length1) : ((gpointer) _tmp17_);
	_tmp18__length1 = _tmp17__length1;
	_tmp19_ = _tmp18_;
	_tmp19__length1 = _tmp18__length1;
	if (result_length1) {
		*result_length1 = _tmp19__length1;
	}
	result = _tmp19_;
	return result;
}


/**
         * GetComponentIndices
         *
         * @returns Array<number>
         */
static void _vala_array_add3 (gint** array, int* length, int* size, gint value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gint, *array, *size);
	}
	(*array)[(*length)++] = value;
}


static gint* _vala_array_dup3 (gint* self, int length) {
	return g_memdup (self, length * sizeof (gint));
}


static gint* _vala_array_dup4 (gint* self, int length) {
	return g_memdup (self, length * sizeof (gint));
}


gint* bosco_ecs_entity_base_getComponentIndices (BoscoECSEntityBase* self, int* result_length1) {
	gint* result = NULL;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint* _tmp15_ = NULL;
	gint _tmp15__length1 = 0;
	gint* _tmp16_ = NULL;
	gint _tmp16__length1 = 0;
	gint* _tmp17_ = NULL;
	gint _tmp17__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_componentIndicesCache;
	_tmp0__length1 = self->priv->_componentIndicesCache_length1;
	if (_tmp0_ == NULL) {
		gint* indices = NULL;
		gint* _tmp1_ = NULL;
		gint indices_length1 = 0;
		gint _indices_size_ = 0;
		gint index = 0;
		gint* _tmp13_ = NULL;
		gint _tmp13__length1 = 0;
		gint* _tmp14_ = NULL;
		gint _tmp14__length1 = 0;
		_tmp1_ = g_new0 (gint, 0);
		indices = _tmp1_;
		indices_length1 = 0;
		_indices_size_ = indices_length1;
		index = 0;
		{
			gint i = 0;
			gint _tmp2_ = 0;
			_tmp2_ = self->ic;
			i = _tmp2_;
			{
				gboolean _tmp3_ = FALSE;
				_tmp3_ = TRUE;
				while (TRUE) {
					gint _tmp5_ = 0;
					gint _tmp6_ = 0;
					BoscoECSIComponent** _tmp7_ = NULL;
					gint _tmp7__length1 = 0;
					gint _tmp8_ = 0;
					BoscoECSIComponent* _tmp9_ = NULL;
					gint _tmp12_ = 0;
					if (!_tmp3_) {
						gint _tmp4_ = 0;
						_tmp4_ = i;
						i = _tmp4_ + 1;
					}
					_tmp3_ = FALSE;
					_tmp5_ = self->ic;
					_tmp6_ = self->priv->_componentCount;
					if (!(i <= ((_tmp5_ + _tmp6_) - 1))) {
						break;
					}
					_tmp7_ = bosco_ecs_entity_base__components;
					_tmp7__length1 = bosco_ecs_entity_base__components_length1;
					_tmp8_ = i;
					_tmp9_ = _tmp7_[_tmp8_];
					if (_tmp9_ != NULL) {
						gint* _tmp10_ = NULL;
						gint _tmp10__length1 = 0;
						gint _tmp11_ = 0;
						_tmp10_ = indices;
						_tmp10__length1 = indices_length1;
						_tmp11_ = index;
						_vala_array_add3 (&indices, &indices_length1, &_indices_size_, _tmp11_);
					}
					_tmp12_ = index;
					index = _tmp12_ + 1;
				}
			}
		}
		_tmp13_ = indices;
		_tmp13__length1 = indices_length1;
		_tmp14_ = (_tmp13_ != NULL) ? _vala_array_dup3 (_tmp13_, _tmp13__length1) : ((gpointer) _tmp13_);
		_tmp14__length1 = _tmp13__length1;
		self->priv->_componentIndicesCache = (g_free (self->priv->_componentIndicesCache), NULL);
		self->priv->_componentIndicesCache = _tmp14_;
		self->priv->_componentIndicesCache_length1 = _tmp14__length1;
		self->priv->__componentIndicesCache_size_ = self->priv->_componentIndicesCache_length1;
		indices = (g_free (indices), NULL);
	}
	_tmp15_ = self->priv->_componentIndicesCache;
	_tmp15__length1 = self->priv->_componentIndicesCache_length1;
	_tmp16_ = (_tmp15_ != NULL) ? _vala_array_dup4 (_tmp15_, _tmp15__length1) : ((gpointer) _tmp15_);
	_tmp16__length1 = _tmp15__length1;
	_tmp17_ = _tmp16_;
	_tmp17__length1 = _tmp16__length1;
	if (result_length1) {
		*result_length1 = _tmp17__length1;
	}
	result = _tmp17_;
	return result;
}


/**
          * HasComponent
          *
          * @param number index
          * @returns boolean
          */
gboolean bosco_ecs_entity_base_hasComponent (BoscoECSEntityBase* self, gint index) {
	gboolean result = FALSE;
	BoscoECSIComponent** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	BoscoECSIComponent* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = bosco_ecs_entity_base__components;
	_tmp0__length1 = bosco_ecs_entity_base__components_length1;
	_tmp1_ = self->ic;
	_tmp2_ = index;
	_tmp3_ = _tmp0_[_tmp1_ + _tmp2_];
	result = _tmp3_ != NULL;
	return result;
}


/**
         * HasComponents
         *
         * @param Array<number> indices
         * @returns boolean
         */
gboolean bosco_ecs_entity_base_hasComponents (BoscoECSEntityBase* self, gint* indices, int indices_length1) {
	gboolean result = FALSE;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = indices;
	_tmp0__length1 = indices_length1;
	{
		gint* index_collection = NULL;
		gint index_collection_length1 = 0;
		gint _index_collection_size_ = 0;
		gint index_it = 0;
		index_collection = _tmp0_;
		index_collection_length1 = _tmp0__length1;
		for (index_it = 0; index_it < _tmp0__length1; index_it = index_it + 1) {
			gint index = 0;
			index = index_collection[index_it];
			{
				BoscoECSIComponent** _tmp1_ = NULL;
				gint _tmp1__length1 = 0;
				gint _tmp2_ = 0;
				gint _tmp3_ = 0;
				BoscoECSIComponent* _tmp4_ = NULL;
				_tmp1_ = bosco_ecs_entity_base__components;
				_tmp1__length1 = bosco_ecs_entity_base__components_length1;
				_tmp2_ = self->ic;
				_tmp3_ = index;
				_tmp4_ = _tmp1_[_tmp2_ + _tmp3_];
				if (_tmp4_ == NULL) {
					result = FALSE;
					return result;
				}
			}
		}
	}
	result = TRUE;
	return result;
}


/**
         * HasAnyComponent
         *
         * @param Array<number> indices
         * @returns boolean
         */
gboolean bosco_ecs_entity_base_hasAnyComponent (BoscoECSEntityBase* self, gint* indices, int indices_length1) {
	gboolean result = FALSE;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = indices;
	_tmp0__length1 = indices_length1;
	{
		gint* index_collection = NULL;
		gint index_collection_length1 = 0;
		gint _index_collection_size_ = 0;
		gint index_it = 0;
		index_collection = _tmp0_;
		index_collection_length1 = _tmp0__length1;
		for (index_it = 0; index_it < _tmp0__length1; index_it = index_it + 1) {
			gint index = 0;
			index = index_collection[index_it];
			{
				BoscoECSIComponent** _tmp1_ = NULL;
				gint _tmp1__length1 = 0;
				gint _tmp2_ = 0;
				gint _tmp3_ = 0;
				BoscoECSIComponent* _tmp4_ = NULL;
				_tmp1_ = bosco_ecs_entity_base__components;
				_tmp1__length1 = bosco_ecs_entity_base__components_length1;
				_tmp2_ = self->ic;
				_tmp3_ = index;
				_tmp4_ = _tmp1_[_tmp2_ + _tmp3_];
				if (_tmp4_ != NULL) {
					result = TRUE;
					return result;
				}
			}
		}
	}
	result = FALSE;
	return result;
}


/**
         * RemoveAllComponents
         *
         */
void bosco_ecs_entity_base_removeAllComponents (BoscoECSEntityBase* self) {
	gchar* _tmp0_ = NULL;
	gint index = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("");
	_g_free0 (self->priv->_toStringCache);
	self->priv->_toStringCache = _tmp0_;
	index = 0;
	{
		gint i = 0;
		gint _tmp1_ = 0;
		_tmp1_ = self->ic;
		i = _tmp1_;
		{
			gboolean _tmp2_ = FALSE;
			_tmp2_ = TRUE;
			while (TRUE) {
				gint _tmp4_ = 0;
				gint _tmp5_ = 0;
				BoscoECSIComponent** _tmp6_ = NULL;
				gint _tmp6__length1 = 0;
				gint _tmp7_ = 0;
				BoscoECSIComponent* _tmp8_ = NULL;
				gint _tmp10_ = 0;
				if (!_tmp2_) {
					gint _tmp3_ = 0;
					_tmp3_ = i;
					i = _tmp3_ + 1;
				}
				_tmp2_ = FALSE;
				_tmp4_ = self->ic;
				_tmp5_ = self->priv->_componentCount;
				if (!(i <= ((_tmp4_ + _tmp5_) - 1))) {
					break;
				}
				_tmp6_ = bosco_ecs_entity_base__components;
				_tmp6__length1 = bosco_ecs_entity_base__components_length1;
				_tmp7_ = i;
				_tmp8_ = _tmp6_[_tmp7_];
				if (_tmp8_ != NULL) {
					gint _tmp9_ = 0;
					_tmp9_ = index;
					_bosco_ecs_entity_base_replaceComponent (self, _tmp9_, NULL);
				}
				_tmp10_ = index;
				index = _tmp10_ + 1;
			}
		}
	}
}


/**
         * Destroy
         *
         */
void bosco_ecs_entity_base_destroy (BoscoECSEntityBase* self) {
	BoscoECSEntityChanged* _tmp0_ = NULL;
	BoscoECSComponentReplaced* _tmp1_ = NULL;
	BoscoECSEntityChanged* _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	bosco_ecs_entity_base_removeAllComponents (self);
	_tmp0_ = self->priv->_onComponentAdded;
	bosco_ecs_entity_changed_clear (_tmp0_);
	_tmp1_ = self->priv->_onComponentReplaced;
	bosco_ecs_component_replaced_clear (_tmp1_);
	_tmp2_ = self->priv->_onComponentRemoved;
	bosco_ecs_entity_changed_clear (_tmp2_);
	self->priv->_isEnabled = FALSE;
}


/**
         * ToString
         *
         * @returns string
         */
static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	{
		GRegex* regex = NULL;
		const gchar* _tmp0_ = NULL;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_ = NULL;
		GRegex* _tmp3_ = NULL;
		GRegex* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		GRegex* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		_tmp0_ = old;
		_tmp1_ = g_regex_escape_string (_tmp0_, -1);
		_tmp2_ = _tmp1_;
		_tmp3_ = g_regex_new (_tmp2_, 0, 0, &_inner_error_);
		_tmp4_ = _tmp3_;
		_g_free0 (_tmp2_);
		regex = _tmp4_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp6_ = regex;
		_tmp7_ = replacement;
		_tmp8_ = g_regex_replace_literal (_tmp6_, self, (gssize) -1, 0, _tmp7_, 0, &_inner_error_);
		_tmp5_ = _tmp8_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_regex_unref0 (regex);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp9_ = _tmp5_;
		_tmp5_ = NULL;
		result = _tmp9_;
		_g_free0 (_tmp5_);
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally0;
	__catch0_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
}


gchar* bosco_ecs_entity_base_toString (BoscoECSEntityBase* self) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp24_ = NULL;
	gchar* _tmp25_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_toStringCache;
	if (_tmp0_ == NULL) {
		GString* sb = NULL;
		GString* _tmp1_ = NULL;
		gchar* seperator = NULL;
		gchar* _tmp2_ = NULL;
		gint* components = NULL;
		gint _tmp3_ = 0;
		gint* _tmp4_ = NULL;
		gint components_length1 = 0;
		gint _components_size_ = 0;
		gint lastSeperator = 0;
		gint* _tmp5_ = NULL;
		gint _tmp5__length1 = 0;
		GString* _tmp21_ = NULL;
		const gchar* _tmp22_ = NULL;
		gchar* _tmp23_ = NULL;
		_tmp1_ = g_string_new ("");
		sb = _tmp1_;
		_tmp2_ = g_strdup (", ");
		seperator = _tmp2_;
		_tmp4_ = bosco_ecs_entity_base_getComponentIndices (self, &_tmp3_);
		components = _tmp4_;
		components_length1 = _tmp3_;
		_components_size_ = components_length1;
		_tmp5_ = components;
		_tmp5__length1 = components_length1;
		lastSeperator = _tmp5__length1 - 1;
		{
			gint i = 0;
			i = 0;
			{
				gboolean _tmp6_ = FALSE;
				_tmp6_ = TRUE;
				while (TRUE) {
					gint _tmp8_ = 0;
					GString* _tmp9_ = NULL;
					gchar** _tmp10_ = NULL;
					gint _tmp10__length1 = 0;
					gint* _tmp11_ = NULL;
					gint _tmp11__length1 = 0;
					gint _tmp12_ = 0;
					gint _tmp13_ = 0;
					const gchar* _tmp14_ = NULL;
					gchar* _tmp15_ = NULL;
					gchar* _tmp16_ = NULL;
					gint _tmp17_ = 0;
					gint _tmp18_ = 0;
					if (!_tmp6_) {
						gint _tmp7_ = 0;
						_tmp7_ = i;
						i = _tmp7_ + 1;
					}
					_tmp6_ = FALSE;
					_tmp8_ = lastSeperator;
					if (!(i <= _tmp8_)) {
						break;
					}
					_tmp9_ = sb;
					_tmp10_ = self->priv->_componentsEnum;
					_tmp10__length1 = self->priv->_componentsEnum_length1;
					_tmp11_ = components;
					_tmp11__length1 = components_length1;
					_tmp12_ = i;
					_tmp13_ = _tmp11_[_tmp12_];
					_tmp14_ = _tmp10_[_tmp13_];
					_tmp15_ = string_replace (_tmp14_, "Component", "");
					_tmp16_ = _tmp15_;
					g_string_append (_tmp9_, _tmp16_);
					_g_free0 (_tmp16_);
					_tmp17_ = i;
					_tmp18_ = lastSeperator;
					if (_tmp17_ < _tmp18_) {
						GString* _tmp19_ = NULL;
						const gchar* _tmp20_ = NULL;
						_tmp19_ = sb;
						_tmp20_ = seperator;
						g_string_append (_tmp19_, _tmp20_);
					}
				}
			}
		}
		_tmp21_ = sb;
		_tmp22_ = _tmp21_->str;
		_tmp23_ = g_strdup (_tmp22_);
		_g_free0 (self->priv->_toStringCache);
		self->priv->_toStringCache = _tmp23_;
		components = (g_free (components), NULL);
		_g_free0 (seperator);
		_g_string_free0 (sb);
	}
	_tmp24_ = self->priv->_toStringCache;
	_tmp25_ = g_strdup (_tmp24_);
	result = _tmp25_;
	return result;
}


/**
         * AddRef
         *
         * @returns entitas.Entity
         */
BoscoECSEntity* bosco_ecs_entity_base_addRef (BoscoECSEntityBase* self) {
	BoscoECSEntity* result = NULL;
	gint _tmp0_ = 0;
	BoscoECSEntity* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_refCount;
	self->priv->_refCount = _tmp0_ + 1;
	_tmp1_ = _dark_matter_ref0 (G_TYPE_CHECK_INSTANCE_CAST (self, BOSCO_ECS_TYPE_ENTITY, BoscoECSEntity));
	result = _tmp1_;
	return result;
}


/**
         * Release
         *
         */
void bosco_ecs_entity_base_release (BoscoECSEntityBase* self, GError** error) {
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_refCount;
	self->priv->_refCount = _tmp0_ - 1;
	_tmp1_ = self->priv->_refCount;
	if (_tmp1_ == 0) {
		BoscoECSEntityReleased* _tmp2_ = NULL;
		_tmp2_ = self->priv->_onEntityReleased;
		bosco_ecs_entity_released_dispatch (_tmp2_, G_TYPE_CHECK_INSTANCE_CAST (self, BOSCO_ECS_TYPE_ENTITY, BoscoECSEntity));
	} else {
		gint _tmp3_ = 0;
		_tmp3_ = self->priv->_refCount;
		if (_tmp3_ < 0) {
			const gchar* _tmp4_ = NULL;
			const gchar* _tmp5_ = NULL;
			GError* _tmp6_ = NULL;
			_tmp4_ = self->priv->_id;
			_tmp5_ = self->priv->_name;
			_tmp6_ = g_error_new (BOSCO_ECS_ECS_EXCEPTION, BOSCO_ECS_ECS_EXCEPTION_EntityIsAlreadyReleased, "%s:%s", _tmp4_, _tmp5_);
			_inner_error_ = _tmp6_;
			if (_inner_error_->domain == BOSCO_ECS_ECS_EXCEPTION) {
				g_propagate_error (error, _inner_error_);
				return;
			} else {
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return;
			}
		}
	}
}


gint bosco_ecs_entity_base_get_creationIndex (BoscoECSEntityBase* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_creationIndex;
	result = _tmp0_;
	return result;
}


const gchar* bosco_ecs_entity_base_get_name (BoscoECSEntityBase* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_name;
	result = _tmp0_;
	return result;
}


const gchar* bosco_ecs_entity_base_get_id (BoscoECSEntityBase* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_id;
	result = _tmp0_;
	return result;
}


gboolean bosco_ecs_entity_base_get_isEnabled (BoscoECSEntityBase* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_isEnabled;
	result = _tmp0_;
	return result;
}


gint bosco_ecs_entity_base_get_refCount (BoscoECSEntityBase* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_refCount;
	result = _tmp0_;
	return result;
}


BoscoECSEntityReleased* bosco_ecs_entity_base_get_onEntityReleased (BoscoECSEntityBase* self) {
	BoscoECSEntityReleased* result;
	BoscoECSEntityReleased* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_onEntityReleased;
	result = _tmp0_;
	return result;
}


BoscoECSEntityChanged* bosco_ecs_entity_base_get_onComponentAdded (BoscoECSEntityBase* self) {
	BoscoECSEntityChanged* result;
	BoscoECSEntityChanged* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_onComponentAdded;
	result = _tmp0_;
	return result;
}


BoscoECSEntityChanged* bosco_ecs_entity_base_get_onComponentRemoved (BoscoECSEntityBase* self) {
	BoscoECSEntityChanged* result;
	BoscoECSEntityChanged* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_onComponentRemoved;
	result = _tmp0_;
	return result;
}


BoscoECSComponentReplaced* bosco_ecs_entity_base_get_onComponentReplaced (BoscoECSEntityBase* self) {
	BoscoECSComponentReplaced* result;
	BoscoECSComponentReplaced* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_onComponentReplaced;
	result = _tmp0_;
	return result;
}


static void bosco_ecs_entity_base_class_init (BoscoECSEntityBaseClass * klass) {
	bosco_ecs_entity_base_parent_class = g_type_class_peek_parent (klass);
	((DarkMatterClass *) klass)->finalize = bosco_ecs_entity_base_finalize;
	g_type_class_add_private (klass, sizeof (BoscoECSEntityBasePrivate));
}


static void bosco_ecs_entity_base_instance_init (BoscoECSEntityBase * self) {
	self->priv = BOSCO_ECS_ENTITY_BASE_GET_PRIVATE (self);
	self->db_id = 0;
	self->ic = 0;
}


static void bosco_ecs_entity_base_finalize (DarkMatter* obj) {
	BoscoECSEntityBase * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, BOSCO_ECS_TYPE_ENTITY_BASE, BoscoECSEntityBase);
	_g_free0 (self->priv->_name);
	_g_free0 (self->priv->_id);
	_bosco_ecs_entity_released_unref0 (self->priv->_onEntityReleased);
	_bosco_ecs_entity_changed_unref0 (self->priv->_onComponentAdded);
	_bosco_ecs_entity_changed_unref0 (self->priv->_onComponentRemoved);
	_bosco_ecs_component_replaced_unref0 (self->priv->_onComponentReplaced);
	_dark_matter_unref0 (self->priv->_world);
	_g_free0 (self->priv->_toStringCache);
	self->priv->_componentsCache = (_vala_array_free (self->priv->_componentsCache, self->priv->_componentsCache_length1, (GDestroyNotify) dark_matter_unref), NULL);
	self->priv->_componentIndicesCache = (g_free (self->priv->_componentIndicesCache), NULL);
	DARK_MATTER_CLASS (bosco_ecs_entity_base_parent_class)->finalize (obj);
}


GType bosco_ecs_entity_base_get_type (void) {
	static volatile gsize bosco_ecs_entity_base_type_id__volatile = 0;
	if (g_once_init_enter (&bosco_ecs_entity_base_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BoscoECSEntityBaseClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) bosco_ecs_entity_base_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BoscoECSEntityBase), 0, (GInstanceInitFunc) bosco_ecs_entity_base_instance_init, NULL };
		GType bosco_ecs_entity_base_type_id;
		bosco_ecs_entity_base_type_id = g_type_register_static (TYPE_DARK_MATTER, "BoscoECSEntityBase", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&bosco_ecs_entity_base_type_id__volatile, bosco_ecs_entity_base_type_id);
	}
	return bosco_ecs_entity_base_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



