/* Exceptions.c generated by valac 0.34.4, the Vala compiler
 * generated from Exceptions.gs, do not modify */


#include <glib.h>
#include <glib-object.h>


typedef enum  {
	BOSCO_ECS_EXCEPTION_ECS
} BoscoECSException;
#define BOSCO_ECS_EXCEPTION bosco_ecs_exception_quark ()
typedef enum  {
	BOSCO_ECS_ECS_EXCEPTION_EntityIsNotEnabled,
	BOSCO_ECS_ECS_EXCEPTION_EntityAlreadyHasComponent,
	BOSCO_ECS_ECS_EXCEPTION_EntityDoesNotHaveComponent,
	BOSCO_ECS_ECS_EXCEPTION_EntityIsAlreadyReleased,
	BOSCO_ECS_ECS_EXCEPTION_SingleEntity,
	BOSCO_ECS_ECS_EXCEPTION_Matcher,
	BOSCO_ECS_ECS_EXCEPTION_WorldDoesNotContainEntity
} BoscoECSEcsException;
#define BOSCO_ECS_ECS_EXCEPTION bosco_ecs_ecs_exception_quark ()


GQuark bosco_ecs_exception_quark (void);
GQuark bosco_ecs_ecs_exception_quark (void);


GQuark bosco_ecs_exception_quark (void) {
	return g_quark_from_static_string ("bosco_ecs_exception-quark");
}


GQuark bosco_ecs_ecs_exception_quark (void) {
	return g_quark_from_static_string ("bosco_ecs_ecs_exception-quark");
}



